### ISSUE TITLE
ensure complete context tracing from endpoints

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1075]
A pass should be done through the code to ensure that contexts received by endpoints are passed on / modified and then passed on to further functions down the stack. In other words, `context.Background()` may be suitable only for CLI and unit tests.

This allows observable tracing of contexts/call stack.

**Comment by amoore877** [comment]
Ideally we also have unit testing that injects something into context at an endpoint and inspects the context at each layer of calls (or at least the very end of the stack, usually datastore for server) to ensure the context is kept

**Comment by azdagron** [comment]
This should more or less be done? Is there a particular code path you are worried about?

I've audited all of the non test code are there are very few places that use context.Background(), all of which seem justified (like interfaces where a context can't be threaded through or otherwise obtained), truly background tasks, etc.

**Comment by amoore877** [comment]
sounds good to me; just wanted to make sure some eyes went out to audit it
