### ISSUE TITLE
Near-term release plan

### ISSUE THREAD

**Issue by mbyczkowski** [spiffe/spire#1090]
It has been a while since the last release and there were a lot of changes since then. As SPIRE is approaching 1.0 stability, it might be beneficial to cut releases more often to encourage adoption and testing (especially ensuring that bumping either SPIRE server or agent is safe to do). This should also help with planning potential schema changes that were discussed in #1083.

I think we should cut 0.9 soon and then continue with 0.x releases (on a regular cadence) until there's a consensus that SPIRE is ready for 1.0. I'd be happy to hear counter-arguments, though.

**Comment by evan2645** [comment]
Thank you for opening this @mbyczkowski 

I fully agree that we need a tighter release cadence. The project as a whole targets monthly releases, but lately we have been falling behind, mostly due to the overhead involved in manual testing. I opened https://github.com/spiffe/spire/issues/1038 which is related.

I was hoping to get a release cut in the next week or two, and have been targeting 704e79534d283bfa83a4a24977f89f0a49410dc4 as the candidate. This would be 0.8.2, and perhaps the last of 0.8 assuming nothing significant pops up.

In the meantime, we should probably prioritize #1038 and related works so we can grease things up a little.

**Comment by evan2645** [comment]
Closing this out as stale. We got over the release hump, and we've been releasing on a regular cadence now for about one year.

@mbyczkowski please let us know if this does not meet your expectations, or if you feel that there are still unaddressed problems with the SPIRE release process.

**Comment by mbyczkowski** [comment]
Agreed @evan2645. We've been updating regularly and SPIRE has been doing very well. Great work y'all! 🙌
