### ISSUE TITLE
Improve agent behavior when server is under heavy load

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1091]
There is currently little outward indication when SPIRE server is overloaded, aside from massively elevated response times. Agents hang around forever waiting for an answer, and don't log much so long as they eventually receive one.

Agents should be capable of backing off when appropriate. I am not sure exactly what the ideal solution is here, but I suspect that it will involve timeouts/deadlines set in the context on the agent side, the server responding with an error code when certain load conditions are met, or perhaps both of those things. When this happens, we should log warnings or errors.

**Comment by evan2645** [comment]
@azdagron has https://github.com/spiffe/spire/pull/1182 has addressed this fully, or do you think that there is still room for improvement? @APTy indicated that he might implement backoff in the agent sync poller... are there other things we want to do here too?

**Comment by APTy** [comment]
#1182 is a really important part, but backoff is still needed in order for the system to self-heal. We opened #1241 recently to start tracking that effort - which may be somewhat duplicative of this issue.

**Comment by rturner3** [comment]
Another improvement opportunity around this is to add backoff and retry behavior into SPIRE Agent during initial node attestation. If node attestation fails on the Agent due to heavy Server load, it will cause the Agent process to exit.

It is a likely scenario that during an initial rollout of SPIRE Agent, there will be heavy load upon the Server with many Agents attempting to attest concurrently. It would be better if the Agent itself was intelligent enough to handle this retry/backoff to smooth out the load handled by the Server and allow the Agent to gracefully come up without external intervention needed to restart the Agent process.
