### ISSUE TITLE
spire-agent api fetch:rpc error: code = PermissionDenied desc = no identity issued on spire-agent

### ISSUE THREAD

**Issue by zanghao2** [spiffe/spire#1108]
* **Version**: 
0.8.1
* **Platform**: 
docker/kubernetes
* **Subsystem**: 
spire-server spire-agent

1. I deploy spire-server and spire-agent according to https://github.com/spiffe/spire/tree/master/examples/k8s.
2. The spire-server and spire-agent are healthy.
3. Then ,I create a new registration entry for the node and a new registration entry for the workload.
```
$ kubectl exec -n spire spire-server-0 -- /opt/spire/bin/spire-server entry create \
    -spiffeID spiffe://example.org/ns/spire/sa/spire-agent \
    -parentID spiffe://example.org/spire/server \
    -selector k8s_psat:cluster:example-cluster \
    -selector k8s_psat:agent_ns:spire \
    -selector k8s_psat:agent_sa:spire-agent \
    -node
```
```
$ kubectl exec -n spire spire-server-0 -- /opt/spire/bin/spire-server entry create \
    -spiffeID spiffe://example.org/ns/default/sa/default \
    -parentID spiffe://example.org/ns/spire/sa/spire-agent \
    -selector k8s:ns:default \
    -selector k8s:sa:default
```
4. I deploy the workload.yaml in examples/k8s file.
5. Next I do the following. 
```
kubectl exec -ti worklad sh
./bin/spire-agnt api fetch -socketPath /run/spire/sockets/agent.sock
```
I get following output
```
SPIFFE ID:		spiffe://example.org/ns/default/sa/default
SVID Valid After:	2019-09-10 02:22:27 +0000 UTC
SVID Valid Until:	2019-09-10 03:22:37 +0000 UTC
CA #1 Valid After:	2018-05-13 19:33:47 +0000 UTC
CA #1 Valid Until:	2023-05-12 19:33:47 +0000 UTC
CA #2 Valid After:	2019-09-08 19:44:01 +0000 UTC
CA #2 Valid Until:	2019-09-09 07:44:11 +0000 UTC
CA #3 Valid After:	2019-09-09 01:44:01 +0000 UTC
CA #3 Valid Until:	2019-09-09 13:44:11 +0000 UTC
CA #4 Valid After:	2019-09-09 07:44:01 +0000 UTC
CA #4 Valid Until:	2019-09-09 19:44:11 +0000 UTC
CA #5 Valid After:	2019-09-09 13:44:01 +0000 UTC
CA #5 Valid Until:	2019-09-10 01:44:11 +0000 UTC
CA #6 Valid After:	2019-09-09 19:44:01 +0000 UTC
CA #6 Valid Until:	2019-09-10 07:44:11 +0000 UTC
CA #7 Valid After:	2019-09-10 01:44:01 +0000 UTC
CA #7 Valid Until:	2019-09-10 13:44:11 +0000 UTC
```
6. Then I enter the spire-agent and use the same commad.
```
kubectl exec -ti spire-agent-sfe2f sh -n spire
./bin/spire-agnt api fetch -socketPath /run/spire/sockets/agent.sock
```
I get the follow output
```
rpc error: code = PermissionDenied desc = no identity issued
```

Question:
1. I want to know whether spire-agent can get imformation about the workload and how spire-agent get it's own SVID?
2. Is there any error in my deployment process?

**Comment by evan2645** [comment]
This looks like it's working as intended. On step 5, we can see that you successfully retrieved the workload SVID. Step 6 is expected because there is no registration entry for a process running in the agent's container. While there is a node entry placing the agent into a group (snippet 1 in step 3), this SPIFFE ID is not actually issued to anyone by the agent. It is used only internally.

If you want to be able to retrieve an SVID via the Workload API from inside the agent's pod/container, then you will need an additional registration entry using selectors like `k8s:ns:spire` and `k8s:sa:spire-agent`.

> I want to know whether spire-agent can get imformation about the workload and how spire-agent get it's own SVID?

The SVID that is issued directly to the agent isn't exposed to workloads. Instead, the agent's SVID and SPIFFE IDs associated with node entries are for internal use only (e.g. when the server is authenticating the agent).

> Is there any error in my deployment process?

Nope, looks good to me! As mentioned above, you'll need an additional registration entry if you want a workload inside the spire-agent pod (e.g. the CLI utility) to be able to receive an SVID.

**Comment by evan2645** [comment]
@zanghao2 I'm going to close this issue for now as we've not heard back yet and the condition you're describing is expected. Please let us know if you are still encountering problems and I will re-open this issue.
