### ISSUE TITLE
Spire breaks with newer docker versions

### ISSUE THREAD

**Issue by TSkrebe** [spiffe/spire#1135]
Currently, spire is using docker version from March `v0.7.3-0.20190312165151-258edd715d46` , however in April docker introduced a [breaking change](https://github.com/moby/moby/commit/e6c0d19c3a5ebd0d719bb21c29b9d2395c7c3719) which affects spire:
```
cannot use opts (type []func(*client.Client) error) as type []client.Opt in argument to client.NewClientWithOpts
```

This causes a bit of a headache as a bunch of other libraries are using newer docker versions and because `go mod` uses the oldest allowed version, it becomes tricky to support multiple libraries with different docker versions.

**Comment by ZymoticB** [comment]
That change exists only on master.

I understand it's difficult to support multiple versions of a library but its a big ask to bump to an untagged commit with breaking API changes. I don't think that's a good idea.

**Comment by evan2645** [comment]
@TSkrebe I am curious to hear more about what you're doing that this has become a problem?

I am far from an expert in go modules, however some cursory research suggests that this pain is related to the fact that the dependency is not using go modules. I further found this issue on the Moby repo https://github.com/moby/moby/issues/39056

If that sounds right, I might suggest that you +1 the Moby issue to get some attention. I can see that others have forked for this reason.

**Comment by abhinav** [comment]
Hey,

Since Docker isn't tagging Go module releases, libraries like spire have no
option but to pin to untagged commits on master. Spire is currently pinned to,
https://github.com/moby/moby/commit/258edd715d46. Unless I'm misreading this,
that commit is no different from the current master commit in terms of tagged
releases. Unless Docker begins tagging Go module releases, this is going to be
unavoidable.

For spire, the issue is that it fails to compile with newer versions of
docker/docker. This means that if you're using spire and another library that
consumes a newer version of docker/docker, your code will fail to compile.

An example of this, and the instance that @TSkrebe ran into is with
[golang-migrate/migrate/v4][1] which is pinned to a [newer version][2] of
Docker -- one that spire does not compile with.

Looking at the error message, the fix is likely just:

```diff
-       var opts []func(*dockerclient.Client) error
+       var opts []dockerclient.Opt
```

[1]: https://github.com/golang-migrate/migrate/blob/fc060940b49cdd5b74f8057e248e4f493222012c/go.mod#L1
[2]: https://github.com/moby/moby/commit/4760db040282

Hope this helped.
