### ISSUE TITLE
pkg/common/log doesn't support logrotate

### ISSUE THREAD

**Issue by ZymoticB** [spiffe/spire#1152]
Currently, if you log to a file, `pkg/common/log` opens it once and assumes that FD will always be valid.

if you use a system such as l[ogrotate(8)](https://linux.die.net/man/8/logrotate) (as is suggested in the logrus README) you must use the `copytruncate` option, which is racy and can drop log entries.

Ideally, `pkg/common/log` would support re-opening its file when it receives a signal (HUP, USR1, and USR2 are popular options). This would enable a system like `logrotate(8)` to safely rotate logs.

**Comment by zmt** [comment]
I have WIP for this working now, hard-coded to use HUP, but am leaning towards USR2 since USR1 is already in use for the inmem telemetry (via https://github.com/armon/go-metrics/blob/master/const_unix.go#L11) and we could leave HUP free to signal config file reload.

Incidentally, while working on this, I noticed that logrus is in now in maintenance mode and the maintainers recommend migrating to something like zap (see https://githubhelp.com/sirupsen/logrus). That said, handling a signal to rotate log files still seems like a must to avoid loss with copytruncate.

**Comment by zmt** [comment]
> I have WIP for this working now, hard-coded to use HUP, but am leaning towards USR2 since USR1 is already in use for the inmem telemetry (via https://github.com/armon/go-metrics/blob/master/const_unix.go#L11) and we could leave HUP free to signal config file reload.
> 
> Incidentally, while working on this, I noticed that logrus is in now in maintenance mode and the maintainers recommend migrating to something like zap (see https://githubhelp.com/sirupsen/logrus). That said, handling a signal to rotate log files still seems like a must to avoid loss with copytruncate.

See #1087 or follow-up on larger discussion about changing underlying logging library.
