### ISSUE TITLE
Include TLS exported key material in challenges

### ISSUE THREAD

**Issue by balasanjay** [spiffe/spire#1154]
Hey, I am considering adopting Spire so I can stop manually rotating certs between my home server and the cloud, and https://github.com/spiffe/spire/issues/1096 interested me because my home server occasionally disconnects for a couple of days (when I don't notice windows has randomly restarted due to updates), so I was wondering whether I'd have to resynchronize trust bundles everytime this happens.

It sounds like the proposed flag (insecure_bootstrap) would work for me, but I wanted to understand what about this flag was insecure.

Assuming that I only use one of the proof-of-presence checks (e.g. "sshpop") for node attestation (and not a bearer token based method like a jointoken) it seems like an attacker could act as a MITM between the Spire agent running on my home server and the Spire server running in the cloud. It could then relay the challenge and response back and forth, thereby convincing the Spire server that it is in fact my home server, when its really an attacker. Is that the concern causing this to be labelled as insecure?

If that's accurate, have you considered deriving some of the entropy for the proof-of-presence challenge from exported key material from the TLS connection (see https://tools.ietf.org/html/rfc5705 and https://godoc.org/crypto/tls#ConnectionState.ExportKeyingMaterial)?

In essence, instead of sending a random challenge `C`, and having the other side response with just `Signature(C)`, you could have the other side respond with `Signature(EKM(C))`. Since the exported-key-material depends on the TLS master secret, it'll be different for the link between the agent and the MITM than the one between the MITM and the server. In this way, even if the MITM tries to respond to the challenge by relaying the value from the client, it will not match.

Thoughts?

(You'd probably want to still label this insecure in case the node attestor cannot bind to connection properties; also, we should probably get the opinion of a crypto expert)

(Also, this should probably require TLS 1.3, to guarantee that the two secrets are legitimately always distinct)

**Comment by evan2645** [comment]
Hello @balasanjay!

> my home server occasionally disconnects for a couple of days (when I don't notice windows has randomly restarted due to updates), so I was wondering whether I'd have to resynchronize trust bundles everytime this happens

You will only have to do this if the CA certificate(s) have rotated out since your home server last checked in. New CA certificates are prepared in advance (at 50% of the current certificate's lifetime). If you configure your ca_ttl to something like one or two weeks, you should be OK.

> It sounds like the proposed flag (insecure_bootstrap) would work for me, but I wanted to understand what about this flag was insecure.

The concern here is less about "this is a malicious agent" and more about "this is a malicious server". The server informs the agent of CA certificate updates/rotations, so if an attacker could insert themselves between the server and the agent, they could inject their own CA certificates (which would then be used by workloads attached to that agent).

> If that's accurate, have you considered deriving some of the entropy for the proof-of-presence challenge from exported key material from the TLS connection

Hmm, that is pretty interesting! I don't think it addresses the "did I reach the server I intended to" problem, but it's definitely a neat trick that we might be able to use elsewhere

**Comment by balasanjay** [comment]
Ah, that makes sense. I hadn't realized that the trust bundle is also used by the workload, but that is obvious in retrospect. 

Thanks!
