### ISSUE TITLE
ACM PCA upstream CA root rotation requires server restart

### ISSUE THREAD

**Issue by bcelenza** [spiffe/spire#1183]
* **Version**: https://github.com/spiffe/spire/commit/a5a32a85fe4f61faf87ce3a3e0498f5f65fb84fd
* **Platform**: All
* **Subsystem**: Server (AWS Certificate Manager PCA Upstream CA plugin)

With the merge of #1172, users of SPIRE can use a CA stored in AWS Certificate Manager to sign the server's intermediate CA.

However, one problem which came up during PR review was the following, which is noted in the docs:

> A Private Certificate Authority from ACM cannot have it's private key rotated and maintain the same ARN. As a result, restarting SPIRE server is currently required to change which CA from ACM is signing the intermediate CA for SPIRE. It's recommended to use a persisting key store for SPIRE so that existing intermediate signing certificates are maintained upon restart.

This issue has been filed to look into alternative approaches to changing the server's parent CA from ACM PCA without requiring a restart of the server.

**Comment by evan2645** [comment]
Thank you for filing this @bcelenza 

When a root rotates, it is important for SPIRE to receive the new root in advance so that it may be distributed prior to its use. In normal operation, SPIRE prepares a new certificate well in advance of actually switching to it. This gives time for propagation to occur before SVIDs chaining up to the new root are issued.

If one is using `KeyManager "memory"` however, and a restart is required to obtain a new root via `UpstreamCA "aws_pca"`, the new root will be used immediately. This is the problem that @bcelenza is referring to.

One option is to switch to a persisting keymanager prior to rotating the root. Another option is to introduce a warmup period or something similar. And yet another one is to augment the `spire-server bundle` CLI utility to allow an operator to manually inject the new root into the bundle prior to switching to it.
