### ISSUE TITLE
Agent should re-resolve DNS names more aggressively

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1192]
The default gRPC re-resolution interval is 30 minutes. This is far too slow for most dynamic environments. Dial the resolution interval down to something much more aggressive, perhaps one minute or thirty seconds.

@ZymoticB any preferences on a reasonable value here?

Here are a couple spots that will probably be relevant to this change:
https://github.com/spiffe/spire/blob/41eb0c78bdeee83b11e13fdcc8b4a6e55620b318/pkg/agent/client/dial.go#L69

https://github.com/grpc/grpc-go/blob/7c8e60372e19da88fb3fe8ac6a8de781eef7f547/naming/dns_resolver.go#L34

**Comment by ZymoticB** [comment]
I'd like 5 minutes as an upper bound, configurable would be best. The most important hunk here is ensuring that agents jitter themselves within that time to spread the load.

https://github.com/grpc/grpc-go/blob/7c8e60372e19da88fb3fe8ac6a8de781eef7f547/naming/dns_resolver.go#L34 this is particularly annoying because it isn't configurable at all and as far as I know the only way to do what we want is to vendor that resolver object and register as a custom resolver (https://github.com/grpc/grpc-go/blob/master/resolver/resolver.go#L42) and then we'll have to modify this https://github.com/spiffe/spire/blob/e6efacc174d6506adc4877837e2aaac8e826827d/cmd/spire-agent/cli/run/run.go#L218 to construct a target which uses that custom resolver type.

Given that grpc target isn't exposed to the user via configuration its *ok* but it will make configuration subtler if we wanted to expose that in the future (e.g. if you wanted to support a custom DNS resolver. grpc supports this with a target like `dns://8.8.8.8/target.host.name`)

**Comment by evan2645** [comment]
> this is particularly annoying because it isn't configurable at all and as far as I know the only way to do what we want is to vendor that resolver object and register as a custom resolver

I did some brief research here when opening this issue, and it seemed like it would be possible to accomplish this by creating a Round Robin Balancer and explicitly passing in a resolver (which can be created by calling `NewDNSResolverWithFreq`. I didn't see the _exact_ path forward, so perhaps something is still missing there.

We'll have to put some thought into the jitter. DNS queries are relatively inexpensive hence my leaning towards minute or sub-minute. You really think that's too aggressive? One option is to choose a random number between 30 and 60 when instantiating the balancer :)

**Comment by ZymoticB** [comment]
I was being conservative, I'd also prefer something like a minute of sub-minute, that's why I said 5 minute upper bound :)

**Comment by bharaththiruveedula** [comment]
Can I work on this?

**Comment by evan2645** [comment]
@bharaththiruveedula that would be great! I'll assign this to you - let me know if there's anything we can do to help

**Comment by APTy** [comment]
excited for this one!

**Comment by APTy** [comment]
I looked at this a bit more and posted a question upstream about it: https://github.com/grpc/grpc-go/issues/3170. Response from one of the maintainers:

> DNS re-resolves any time any connection fails, and you can cause this to happen regularly by setting [max connection age](https://godoc.org/google.golang.org/grpc/keepalive#ServerParameters).

We'll need to think about the tradeoffs some (clients disconnecting regularly vs. polling dns regularly), but it seems like a reasonable direction to try. I do somewhat prefer using the lib's preferred APIs over vendoring a bunch of internal code..

**Comment by evan2645** [comment]
I think this has been fixed in #1265 which will be released tomorrow. Going to close this issue for now
