### ISSUE TITLE
Please use 'v0.0.0' format for release git tags 

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#1343]
https://github.com/golang/go/wiki/Modules#modules says:

> Modules must be semantically versioned according to semver, usually in the form v(major).(minor).(patch), such as v0.1.0, v1.2.3, or v1.5.0-rc.1. The leading v is required. If using Git, tag released commits with their versions.

Right now our go.mod looks like:

	github.com/spiffe/spire v0.0.0-20200109225108-b07708daa818
	github.com/spiffe/spire/proto/spire v0.0.0-20200109225108-b07708daa818

but we'd prefer to use tagged versions like

	github.com/spiffe/spire v0.9.2
	github.com/spiffe/spire/proto/spire v0.9.2

**Comment by azdagron** [comment]
I've done this for v0.9.2. Please re-open if you need another older version tagged this way. We'll need to update our release process to tag things this way for future releases.

For future reference, due to the multi-module nature of the repository, `go get`-ability required creating two tags:
- `v0.9.2`
- `proto/spire/v0.9.2`

**Comment by mcpherrinm** [comment]
It works!  Thanks, we've now upgraded to 0.9.2 with a nicely clean go.mod.
