### ISSUE TITLE
keep version tag format consistent

### ISSUE THREAD

**Issue by bobo333** [spiffe/spire#1344]
* **Version**: 0.9.2

This is kind of nitpicky, and I apologize for that. However, it would be helpful if the git tag format was consistent across versions.

Previously it was `0.9.1`, `0.9.0`, etc
Now it is `v0.9.2`

This causes the url of the released tarball to change on github, which can break builds if users are relying on those urls to stay consistent in their build pipelines.

**Comment by bobo333** [comment]
Also related, there are a few inconsistencies with the released files vs previous releases

- the tarball used to have a top-level directory, ex: `spire-0.9.1/`
- the filename previously was lower-case `linux`, now it's upper case `Linux`

**Comment by azdagron** [comment]
The tarball release inconsistencies were introduced with the Makefile overhaul. I'll put in a fix.

The git tag version change was an unfortunate necessity in order to allow for more ergonomic go module dependency tracking for projects consuming SPIRE. Additionally, best practices suggest the v-prefix anyway, so at least we're moving in the right direction.

It is unfortunate that the version in the asset URL no longer matches the tag. I can probably manually fix this for 0.9.2 (now v0.9.2).

**Comment by azdagron** [comment]
Also, always feel free to nitpick :) Suggestions are always welcome.

**Comment by bobo333** [comment]
Thanks for the quick response! Having a v-prefix is fine, especially if it's best practice. Just hoping whatever is chosen can stay as consistent as possible (within reason) moving forward :)

**Comment by bobo333** [comment]
closing this, sounds like you guys are on top of it, thanks again
