### ISSUE TITLE
x509pop attestation shouldn't allow re-attestation by default

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1434]
The x509pop node attestor plugin has traditionally allowed re-attestation because it asserts that agents are still in possession of the private key. However, this ability to re-attest has caused confusion where operators assume they can deploy the same key pair to multiple agents. This causes problems since the last agent to attest with the key pair is the only agent that will continue to function. The rest of the agents will stop being able to sync until they are restarted, at which point they will re-attest, and subsequently break the other agents. The problem becomes even worse when we consider proposals to have the agent more aggressively attempt re-attestation, since that would cause all impact agents to get stuck in a re-attestation cycle.

The benefits of automatic re-attestation might not be worth the potential for misconfiguration. We should consider disabling re-attestation by default. If this feature is currently critical to some deployments, we could introduce a new configurable to opt-in to re-attestation and follow proper deprecation procedures to introduce the new behavior.

**Comment by APTy** [comment]
IMHO the primary reason that aws IID and gcp IIT attestors disable re-attestation is because there is no access control on the IID/IIT (since they're available on the host's network interface), and so we implement trust-on-first-use.

Conversely, x509pop and sshpop attestors rely on files, which can have tightly controlled access on the host. An operator can ensure that access to the x509pop keypair is equivalent to the access to spire-agent's data directory. In other words, trust-on-first-use isn't needed, since accessing the x509pop keypair implies access to the spire-agent keypair.

I can understand that the ability to re-attest by default causes some confusion to operators who wish to use the same keypair across many hosts, but I'd also posit that is a misuse of the x509pop plugin to begin with. In any event, we should make using this plugin safer without completely breaking the present behavior, and I'd be open to disabling re-attestation by default with a configurable to allow re-attestation for those who need it.
