### ISSUE TITLE
api/v2: X509SVIDClient doesn't use `context.Context` given in `Start(ctx)`

### ISSUE THREAD

**Issue by aybabtme** [spiffe/spire#1436]
In contrast with to the non-v2 API, v2  takes a `context.Context` in the [`Start`](https://github.com/spiffe/spire/blob/master/api/workload/v2/workload.go#L123) and [`Stop`](https://github.com/spiffe/spire/blob/master/api/workload/v2/workload.go#L214-L215) methods. However, it doesn't respect these `ctx` and [uses its own `context.Background`-derived context](https://github.com/spiffe/spire/blob/master/api/workload/v2/workload.go#L98). This is a problem since:
- the contexts used by the client should be provided externally by the application; the [`NewX509SVIDClient`](https://github.com/spiffe/spire/blob/master/api/workload/v2/workload.go#L97) function should receive it's background context from the caller).
- one would expect that a context provided to `Start(ctx)` is going to be used, and similarly by the `Stop(ctx)` method.
- it seems that current functionality would work just fine (especially given the requirement to call `Start` only once) if the client was using provided contexts.

This is a problem because it removes control over blocking/IO related lifetimes from the user, and also breaks propagation of contexts and their values (this is a moot point since nothing about the gRPC connection is currently exposed to users). These problems prevent possible integrations with telemetry/observability tools, such as tracing.

**Comment by azdagron** [comment]
Thanks for filing this @aybabtme! The Workload API client code (both V1, and V2) are slowly being deprecated in favor of the implementation in the [go-spiffe](github.com/spiffe/go-spiffe) repository.

The v2 version was ported over to go-spiffe some time ago. At that time the contexts on both `Start()` and `Stop()` were removed since they were unused and unsupported means of stopping the client. The design of the client was that `Start()` would block until `Stop()` was called. If a caller was interested in tying the lifetime of the client to a context, they could kick off their own goroutine which ran `Start()`, wait for context cancellation, and then call `Stop()`.

All that being said, go-spiffe is getting it's own v2 revamp. Work is ongoing but the scaffolding is in place. The equivalent functionality is much less cumbersome and will be blocking until the passed in context is canceled.

https://github.com/spiffe/go-spiffe/blob/v2-api/v2/workloadapi/convenience.go#L35

**Comment by aybabtme** [comment]
Cool. Whether used for stopping or not, I think context should be weave through to all I/O producing calls. Not just for timeouts (which are valid use cases) but also to add things like distributed tracing to the project in the future. 

Similarly it should probably be possible to provide grpc.Conn decorators/hooks down the line, but that's another topic.

**Comment by azdagron** [comment]
> I think context should be weaved through to all I/O producing calls.

Agreed!

> Similarly it should probably be possible to provide grpc.Conn decorators/hooks down the line, but that's another topic.

This is possible with the v2 stuff being worked on:
https://github.com/spiffe/go-spiffe/blob/v2-api/v2/workloadapi/option.go#L21

**Comment by azdagron** [comment]
In light of the fact that we're deprecating the workload API client code in the SPIRE codebase, and that plumbing the context through constitutes a breaking change (since a context passed into Start() that is canceled would now cause the call to return), I think we'll close for now. Workloads should favor the new go-spiffe work when it is available (hopefully in very short order).
