### ISSUE TITLE
JWT SVIDs always have 5 minute lifetimes; should be configurable

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#1438]
It appears that SPIRE currently hard-codes JWT SVIDs to have a 5 minute lifetime:

This is the default value set in the CA config in pkg/server/ca/ca.go:162, in the NewCA function.  The NewCA function is called in pkg/server/server.go:245 in newCA with no JWTSVIDTTL argument, thus it is not plumbed in from any configuration.

The SPIRE Server's API does allow a TTL to be set in the API, however, the Spire agent never sets a value:  The only use of the client's FetchJWTSVID at pkg/agent/manager/manager.go:168 does not specify a TTL.

I would have expected, from the documentation, that the SVID TTL would apply to both x509 and JWT svids.

If that behavior is desired, I believe a patch like this would fix it:

```
--- pkg/server/server.go
+++ pkg/server/server.go
@@ -247,6 +247,7 @@ func (s *Server) newCA(metrics telemetry.Metrics) *ca.CA {
                Log:         s.config.Log.WithField(telemetry.SubsystemName, telemetry.CA),
                Metrics:     metrics,
                X509SVIDTTL: s.config.SVIDTTL,
+               JWTSVIDTTL:  s.config.SVIDTTL,
                JWTIssuer:   s.config.JWTIssuer,
                TrustDomain: s.config.TrustDomain,
                CASubject:   s.config.CASubject,
```

Otherwise, a separate configuration option should be made, and the documentation should be updated.  I'm up for any of those options, what do folks think is best?

**Comment by evan2645** [comment]
This is something we waffled on in the initial JWT-SVID implementation and settled for a (decidedly insufficient) compromise.

TTL is part of the registration entry as very early on in SPIRE development, it was understood to be a function of the identity. For instance, this particular identity is more sensitive than others, and thus we would like to limit the lifetime of identity documents issued for it. At the time that made good sense, but with the introduction of JWT-SVID, the assumption kind of fell apart.

Since JWT-SVID is a bearer token, we prefer to err on the side of a much shorter TTL than we would for an X509-SVID. So while setting TTL on an entry may indicate its relative importance/value or whatever, using it as an absolute value for document lifetime regardless of the document type is inappropriate.

At the same time, we have until now resisted extending registration entry with anything that is specific to a certain type of SVID. Adding two TTLs (one for X.509 and one for JWT) doesn't seem great. The idea of releasing JWT-SVID functionality that uses the entry TTL (which in most cases is likely on the order of hours) also did not feel great. The simple solution at the time was to pin to 5 minutes.

I definitely think this is something we need to address, though I haven't yet found a good solution. I don't know if a server configurable is granular enough... a more radical idea could be to move away from explicit TTL altogether in favor of some more abstract sensitivity metric that we use to determine TTL for various SVID types.
