### ISSUE TITLE
[RFC] Agent determination of when to renew a workload X509-SVID

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1447]
The agent recently gained to ability to request X509-SVID renewal in response to changes to DNS names and TTL settings on workload registration entries (#1441). Before this change was merged, the agent only renewed when the X509-SVID was missing or near expiration. The PR brought up a larger discussion of how the agent should determine when to renew an X509-SVID going forward.

This issue lays out a few proposals:

## Proposal 1: Determine by Agent Inspecting Entry Fields
This proposal is a continuation of the pattern adopted by #1441. The agent's inspect the fields on the registration entries and determine if a given field will impact the minted X509-SVID. If so, the agent issues a renewal.

Pros:
1. No server side changes required

Cons:
1. Knowledge about how registration entries impact X509-SVID properties leaks from the server to the agent.
2. Efforts to minimize wire bandwidth consumption by clearing out of registration entry fields otherwise unused by the agent before sending them to the agent are thwarted (#1361), since the agent would presumably need to be aware of most fields.

## Proposal 2: Add a Generation Number to the Entry
This proposal changes the registration entry to contain a version or generation number. Whenever the entry is updated, the generation number is changed. The agent would simply keep track of the generation an X509-SVID was minted for and if the generation changes, it would issue a renewal.

Pros:
1. Agent needs no knowledge of individual field impact on the X509-SVID.
2. Changes to remove unneeded fields from entries in responses to the agent to reduce bandwidth consumption can be introduced at leisure.

Cons:
1. Server has to manage generation numbers when updating entries. This should be fairly trivial however.
2. Any update to any field, whether it would impact the resulting X509-SVID, would trigger a renewal.

## Proposal 3: Server Provides Hash of Impactful Fields
This proposal changes the server to hash fields that impact the signed X509-SVID using a non-cryptographic performant hash (e.g. [xxHash](https://cyan4973.github.io/xxHash/)).  The agent could use the hash value to determine if an impactful field had changed and renew the X509-SVID.

Hashing could be done at near RAM speed, meaning it's likely the hash could be calculated as needed and not stored. However, if performance was negatively impacted by the many hashing operations, it might mean the datastore has to store the hash for each entry.

Pros:
1. The hash only updates when a pertinent field changes, minimizing renewals when a benign field is updated on an entry.

Cons:
1. Server rollouts that change the fields that are hashed could cause some renew cycles if an agent ends up cycling between the server it is contacted before all servers have the new code.
2. If the hash has to be stored, because of performance concerns, updating the hash out of an entry update for whatever reason would be costly.

## Request for Comments

Of the above proposals, what sounds the most attractive and why?

Are there alternate proposals that we haven't considered?

**Comment by evan2645** [comment]
It's probably worth noting that Proposal 1 is congruent with the current behavior.

> Proposal 2: Add a Generation Number to the Entry
> ...
> Cons:
> ...
> 2. Any update to any field, whether it would impact the resulting X509-SVID, would trigger a renewal.

I don't think this is strictly true? Bumping the number could also be made conditional in core or otherwise.

> Proposal 3: Server Provides Hash of Impactful Fields
> ...
> However, if performance was negatively impacted by the many hashing operations, it might mean the datastore has to store the hash for each entry.

IMO this seems unlikely - every TLS'd packet that comes in or goes out gets cryptographically hashed. Given the right choice in hashing algorithm, this seems like it should be fairly low overhead

> Pros:
> 1. The hash only updates when a pertinent field changes, minimizing renewals when a benign field is updated on an entry.

Perhaps given my above comment, this pro is moot as it's shared with Proposal 2?

I think another pro here is "no changes to registration entry data model required"

> Cons:
> 1. Server rollouts that change the fields that are hashed could cause some renew cycles if an agent ends up cycling between the server it is contacted before all servers have the new code.

This feels like it's going to end up being very significant at scale. IIRC, gRPC libs do round robin, meaning it might be impossible to fully converge given one half of servers on one field set and the other half on another. With sync interval at 5s, with 8 servers and 5k workloads per agent... I think we're into 15k CSRs/minute/agent... and that's in the best case (i.e. the "bottom" 4 servers are upgraded and the "top" 4 are not, and all agents somehow agree on the same ordering).

> Request for Comments
> Of the above proposals, what sounds the most attractive and why?

I'd prefer Proposal 2, pretty strongly I think. Proposal 1 doesn't make allowances for reducing data on the wire, which we know is a real problem at scale. Proposal 3  also seems untenable as it relates to maintenance and the introduction of new features - it's hard to believe that we will _never_ introduce a new field that we'd want to consider for this purpose. When that time comes, it will take many releases to introduce the controls necessary to do it safely.

![Change My Mind](https://i.imgflip.com/3szwzl.jpg)

**Comment by azdagron** [comment]
I'm also leaning pretty heavily towards Proposal 2.

**Comment by mcpherrinm** [comment]
I like proposal 2, with one extra request: I would like a way to simply increment the counter, to force a re-issue, probably as a CLI/API, without having to otherwise change the entry.
This would have been useful in some of our testing SVID rotation in our workloads, and is not easily accomplished with the other options.

Should SPIRE grow revocation support in the future, you could increment the counter, wait some threshold period, and then revoke the now-hopefully-unused old SVID.

**Comment by rturner3** [comment]
I am also in favor of Proposal 2, for many of the same reasons mentioned above. I think it opens the door to potentially significant improvements in minimizing data sent over the wire from the Server to the Agent. It's also pretty simple to grasp and implement, with little to no down side IMO.

**Comment by azdagron** [comment]
Part one of this change was done as part of PR #1459. Part two has been documented in issue https://github.com/spiffe/spire/issues/1460. After that work has been done, and 0.11 has been released, we can do the agent changes.

**Comment by azdagron** [comment]
This work was completed by #1716.
