### ISSUE TITLE
Workload occasionally fails to receive update when an entry changes

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#1461]
@faisal-memon reported to us that a [recent enhancement](https://github.com/spiffe/spire/pull/1441) which allowed SPIRE Agent to proactively request a new SVID when some of its details have changed (e.g. DNS name) works only occasionally.

He observes that after updating an entry to add a DNS name, his workload receives the entry only "about 1 in 5" times.

See https://github.com/spiffe/spire/pull/1441#issuecomment-600936043 for more information.

@faisal-memon would you mind posting steps to reproduce here?

**Comment by faisal-memon** [comment]
I think I found the race condition. It happens if the update comes in between the two calls to `m.fetchUpdates(...)` (lines 30 and 85) in pkg/agent/manager/sync.go. The call to `m.cache.Update(update, nil)` (line 90) will contain the updated entry in the list of `update.RegistrationEntries`.  `c.updateOrCreateRecord(newEntry)` will be called to update the entry, but the cache won't be updated because `checkSVID` is nil and the updated entry is not in `update.X509SVIDs[]` map. 

The patch below fixes the issue though I'm not sure if that's the correct solution going forward:
```
diff --git a/pkg/agent/manager/cache/cache.go b/pkg/agent/manager/cache/cache.go
index 026f2937..96833b02 100644
--- a/pkg/agent/manager/cache/cache.go
+++ b/pkg/agent/manager/cache/cache.go
@@ -255,7 +255,15 @@ func (c *Cache) Update(update *Update, checkSVID func(*common.RegistrationEntry,
                clearStringSet(fedAdd)
                clearStringSet(fedRem)
 
+               if checkSVID == nil  && update.X509SVIDs[newEntry.EntryId] == nil {
+                       continue;
+               }
+
````

**Comment by evan2645** [comment]
Awesome, big thank you for helping to track this down @faisal-memon. We will try to get a fix in time for the upcoming release.
