### ISSUE TITLE
[RFC] SPIRE break-glass mode

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#1542]
## Background
SPIRE is a critical component in any production system that relies on SPIRE to provide identities to workloads. As a result, if SPIRE is not able to properly provide new SVIDs or renew existing ones, that will result in service interruptions.
Considering the criticality of SPIRE in such infrastructures, there is a need to provide mechanisms that allow SPIRE to continue providing identities even in states where a failure would prevent SPIRE from issuing SVIDs. These mechanisms may include relaxing certificate verifications, including ignoring certificate expiration times when the break-glass mode is active.
The main aspects to define how this will work are:
- What are the conditions that must be achieved in order to allow the possibility of entering in break-glass mode.
- How SPIRE is instructed to enter in break-glass mode
- How SPIRE is instructed to exit the break-glass mode.

## Failure conditions
We need to identify the different failure conditions that can make SPIRE to be in a state where it can enter in break-glass mode. Some examples of these conditions are:
- Connectivity failure between servers and agents until server and agent certificates expire.
- The upstream authority becomes unavailable.
- Datastore goes into read-only mode.

## Possible solutions
Any solution should include clear logging of when the break-glass mode is initiated as well as what actions are being allowed and performed only because SPIRE is in break-glass mode and otherwise would be rejected. Monitoring of this situation should be easy from an operator standpoint. The solution should also aim to facilitate that the time window that the system is in break-glass mode is as short as possible, disallowing being in break-glass mode indefinitely.
Some possibilities to configure the brake-glass mode are:
- Implement a config-reload mechanism for the server and agent. It would require a lot of work to make all the configuration settings work with on-the-fly configuration changes, making current and future configuration settings more difficult to maintain. One option could be to only detect changes related to the break-glass mode configuration, ignoring any other changes until the server or agent is started again. This could be a simple path to manage this, although it would be inconsistent with the way that other configuration settings are handled.
- Implement a special control of some kind (out of the server and agent configs) solely for controlling the break-glass mode.
- Change configurations and require a hard reset of both server and agent so they take effect. This implies that the agent cache will be lost in the restart, as will the live gRPC connection to the server.

## Request for comments
This is a very security sensitive feature and hence broad consensus is needed in regards to the solution and the implementation of the solution. Any feedback is greatly appreciated, especially regarding:
- Other failure conditions not covered here.
- Alternative mechanisms to achieve and exit the brake-glass mode.
- Any aspect that you think that is important to discuss and has not been covered.

The first step is to obtain consensus on the approach for this mode, so we can have a detailed proposal based on the discussion and feedback received.

**Comment by evan2645** [comment]
The change included in https://github.com/spiffe/spire/pull/1584 is probably relevant to this work, leaving the link here for future reference

**Comment by hiyosi** [comment]
> The upstream authority becomes unavailable.

If I understand correctly, when Upstream Authority is unavailable until SPIRE's  CA certificates expire, SPIRE Server can not issue valid SVIDs anymore. In that case, is there any way to continue providing identities on break-glass mode?

**Comment by amartinezfayo** [comment]
Hi @hiyosi, there are a lot of challenges that the break-glass mode is aiming to solve. Upstream Authority unavailability is one of them.
When the Upstream Authority is not available, the server SVID validity will be limited by validity of the last successful rotation. The break-glass mode should allow agents to continue to communicate with servers even if the server SVID is expired.

> is there any way to continue providing identities on break-glass mode?

Yes, the break-glass mode would allow agents to continue be running and exposing the Workload API, so issuing SVIDs would be possible. Issuing _valid_ SVIDs to workloads would still be a challenge since the SVID expiration would be limited by the intermediate certificates. I think that this would still be a "best effort" approach, where the workloads would be able to access the Workload API, but we cannot warrantee the validity of the issued SVIDs.
There are a lot of aspects of this that we need to figure out.
Any thoughts are welcome!

**Comment by rturner3** [comment]
There are a couple points related to the scenario when the server JWT signing key expires and fails to rotate that were identified as part of the review of #2115 that are probably also worth mentioning here.

The current behavior of SPIRE in this scenario is that the server will continue to sign JWT SVIDs, but the SVIDs will be expired at the time of minting (JWT `exp` claim is before current server time). There are some side effects that will happen as a result of this:

1. _Workloads will continue to "successfully" get JWT SVIDs from the agent Workload API, but these SVIDs will always be invalid w.r.t. the server time, which should be reasonably close to the workload's host time._

It is unlikely that workloads that get their identity from SPIRE would be validating whether the SVID they received is expired or not. Most likely the issuance of expired SVIDs would result in authentication failures that in a callee workload that validates the identity. Since the validation of the SVID is done by a separate workload than the one who received the SVID from SPIRE, this can lead to debugging challenges where there are multiple levels of investigation required to trace back the issue to SPIRE. A workload owner may also mis-diagnose the issue as a problem with application caching of the SVID.

2. _Agents will request rotated workload JWT SVIDs every time they sync with the server (currently every 5 seconds)._

This can lead to large load spike on server instances that start performing a lot of wasteful signing operations of expired SVIDs.

I think these are both compelling reasons for having some sort of breakglass mode.
