### ISSUE TITLE
API Refactor: explore the implementation of a datastore cache

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#1631]
The current Node API handler has a datastore caching capability.
As part of the API refactor, the RPCs that would manipulate the cache are no longer in a single service handler, which makes the implementation of a cache more complex.
This issue is to explore / implement a datastore cache in the new APIs.

**Comment by marcosy** [comment]
I have been looking into the current API cache implementation. If I understand correctly, we are currently keeping a cache for bundle and registration entries.

I believe we should keep at least these two caches, which were introduced to fix actual performance issues in #1483 and #1350. In addition, we could think about caching other entities like federated bundles or agents. But I'm not sure if that makes sense since those resources are not called so aggressively and there has not been related performance issues reported so far.

**Registration Entries**

For the registration entries case (`GetAuthorizedEntries` RPC), we could re-use the implementation that lives in the [regentryutil package](https://github.com/spiffe/spire/tree/master/pkg/server/util/regentryutil). The entry service is already using an entry fetcher, so it seems to me that reusing this cache should be pretty straightforward.

**Bundles**

For the bundle case (`GetBundle` RPC), we could implement a cache at the service level. Perhaps something similar to [the one that already exists for the old API](https://github.com/spiffe/spire/blob/master/pkg/server/endpoints/node/cache.go). It may be nice to include a new parameter `tolerateStale` in the `GetBundleRequest` to select whether to use the cached bundle version or not.

I'd love to hear thoughts and suggestions

**Comment by amartinezfayo** [comment]
This proposal looks good to me.
I'm not sure if `tolerateStale` would be an appropriate name. I guess that we want to use the cache by default? Maybe a parameter like `disable_cache` defaulting to false would be a better choice? Although I'm not really sure how useful would be to provide this functionality in real terms.
@azdagron any thoughts on this?

**Comment by marcosy** [comment]
Using the cache by default sounds good to me. I've been looking a bit deeper into the current implementations and it looks like we should be able to re-use them almost without change. We only would have to move it to a common package (so the old API can still use it).
I can push a draft PR so we can have a general idea of how would it look and validate the approach.

**Comment by azdagron** [comment]
I wonder if we might be able to get away with not adding a request parameter and use the cached copy by default but reduce the chance of it returning stale information, at least relative to a single server, by invalidating the cache in response to  bundle modifying actions (AppendBundle and PruneBundle mostly).

**Comment by marcosy** [comment]
I like that option too. If we use the current design (where the cache is at the service level), we could invalidate the bundle in `AppendBundle` and `PublishJWTAuthority` RPCs but not when the bundle is pruned. We don't have an RPC for pruning the bundle in the service in the new API.

If that is not acceptable, I believe the options are to create a `PruneBundle` RPC in the service, or to push the cache down to the datastore layer.
