### ISSUE TITLE
[RFC] Reconsider registration entry "uniqueness" checks

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#1653]
# Introduction

This RFC discusses the possibility of no longer enforcing entry "uniqueness".

## Background

SPIRE server identifies registration entries via the entry ID (a UUID randomly generated by the server when the entry is created). However, when created, entry _uniqueness_ is enforced across the `(parent-id,spiffe-id,selectors)` tuple.

This enforcement seems a reasonable protection against an operator accidentally registering the same information twice, but doesn't otherwise seem to otherwise be necessary. It could be very problematic to have runaway registration creating duplicate registration entries that could negatively impact the performance of entry lookup, the size of agent responses, and the number of SVIDs an agent needs to cache.

However, the uniqueness check also negatively impacts the following:
1) Introduces undue complexity into registrars, which may have multiple resources that end up mapping to the same `(parent-id,spiffe-id,selectors)` tuple (even temporarily). The registrars have to maintain extra state around the `N:1` mapping so the backing registration entry isn't removed prematurely (i.e. removed when at least one resource still needs it).
2) Disallows handing out multiple SVIDs to the same workload with different properties. For example, an operator may wish to give a workload two SVIDs with different DNS names, TTLs, admin bits, etc.

I'd also like to point out that the "uniqueness" check implementation is prone to races in the current implementation, as the check isn't done within the same transaction as the create with proper isolation levels. UpdateEntry also does not enforce "uniqueness", which is an oversight.

## Proposed Change

The proposal is to remove the "uniqueness" check to CreateEntry and allow duplicate registration entries to be created.

## Request For Comments

1. Are there additional arguments for maintaining "uniqueness" of entries outside of errant registration?
2. Are there pragmatic, realistic scenarios where a workload would need two or more SVIDs with the same SPIFFE ID but otherwise different properties?

**Comment by APTy** [comment]
Will this proposal change the behavior of `CreateEntryIfNotExists`? IMHO, registration bridges will need to re-create much of the "uniqueness" checks, to ensure that duplicate entries aren't being created. Is it possible to encapsulate that logic into an API somehow?

**Comment by azdagron** [comment]
It seems like the uniqueness checks help some registration strategies and hurt others. When we added CreateEntryIfNotExists, we debated just adding a `allow_duplicates` flag to the current `CreateEntry` RPC instead. I don't remember the details of that conversation though.

**Comment by amartinezfayo** [comment]
I think that there are some things that we need to consider as part of this decision.
Do we want to allow to issue SVIDs with the same SPIFFE ID and different attributes like the DNS names, TTL, etc.? What's the use case for this?

I have the feeling that allowing issuing SVIDs with the same SPIFFE ID and different attributes can introduce certain complexity for workloads receiving the SVIDs and difficulty in tracing issues when the duplication of entries is not intentional.
I see somehow controversial to provide two SVIDs with the same SPIFFE ID and different attributes. From my perspective, the SPIFFE ID is the heart of the _identity document_ provided and if you need different attributes then you most likely need different identities. Like a person with multiple nationalities each one carrying different attributes, you don't have the same ID across different passports, but each passport with its own ID.

Cases like having two entries with the same SPIFFE ID, one with the admin bit set and the other one without it makes me think about the usage of the SPIFFE ID. The admin bit is not something that we issue as part of the SVID, but it's stored in the registration entry only. So we have to deduce if the presented SVID is an admin workload based on the SPIFFE ID of the SVID. Then if the SPIFFE ID is mapped to two entries, one with the admin bit and the other one without it, should we treat the SVID as an admin or not? In the current implementation we just iterate through all the entries found and if any has the admin bit set, then is an admin SVID. But I think that the correctness of that logic may depend on the context. Deciding whether it's an admin SVID or not may actually require to look at other attributes, but then this gets more complex. It just feels more natural to me to provide different SPIFFE IDs in this case, one for the admin use and the other one for the non-admin.

At the same time, I acknowledge the problems that this uniqueness check introduces to registrars. In the event that we decide to remove this check, I think that we should also consider the ability of choosing/knowing the entry ID at entry creation time.

**Comment by JonathanO** [comment]
Regarding 1:
At present the crd registrar relies on the uniqueness check to recover from an error while trying to persist a newly created Entry ID back to the k8s resource (for example, getting disconnected from the k8s API, or getting killed.) If such an error occurs then the registrar will (in all but a small corner case) attempt to re-reconcile the same resource, CreateIfNotExists will return the previously created entry, and it'll recover correctly.

The reconcile registrar has its own definition of uniqueness, however it does uses the existing uniqueness check to detect a misconfiguration resulting in multiple registrars running simultaneously without leader election.

If the uniqueness check is removed then both will create duplicate entries in these situations. This isn't a problem for reconcile as it will simply remove one of the duplicates next polling cycle. For the crd registrar it would be hard to fix in a race (and corner-case) free way, but a solution which only occasionally leaves orphaned entries behind will be probably be good enough.

Digressing a bit, what would be really useful for the registrars, especially if the uniqueness constraint is removed, would be to have a field identifying the "Creator" of an entry, and additionally an arbitrary ID field, ideally with a unique constraint on creator+id. This would allow the crd registrar to populate the new ID field with the name of the k8s resource the entry belongs to, making it possible to handle the above situations in a race free way.

Regarding 2:
I could imagine circumstances where you might want one x509 SVID with DNS names, and one without. The former might be used to serve some https endpoints, the latter might be used as a client certificate to authenticate to legacy services that have  opinions on how to interpret names on certificate (etcd maybe?) I don't have a concrete use case for this though.

**Comment by bleggett** [comment]
```
SPIRE server identifies registration entries via the entry ID (a UUID randomly generated by the server when the entry is created). However, when created, entry uniqueness is enforced across the (parent-id,spiffe-id,selectors) tuple.
```

The other ergonomic problem with EntryIDs is that you can't delete entries except by EntryID, which is a value generated and owned by the SPIRE server, which means you cannot do the "obvious" thing in client code and delete entries by SPIFFE ID - you have to query by SPIFFE ID to get the EntryID and then use that to delete, which feels clunky.

```
Disallows handing out multiple SVIDs to the same workload with different properties. For example, an operator may wish to give a workload two SVIDs with different DNS names, TTLs, admin bits, etc.
```

IMO this cuts against the purpose of uniquely and securely identifying workloads and I'm not sure it needs to be supported - Would it not be simpler and more obvious to say that uniqueness is defined **solely** by (parent-id,spiffe-id), and disallow creating duplicate entries with the same (parent-id,spiffe-id)?

```
I could imagine circumstances where you might want one x509 SVID with DNS names, and one without. The former might be used to serve some https endpoints, the latter might be used as a client certificate to authenticate to legacy services that have opinions on how to interpret names on certificate (etcd maybe?) I don't have a concrete use case for this though.
```

Wouldn't it be better in that scenario to generate a new SVID with a different SPIFFE-ID (perhaps with the "main" SVID's SPIFFE ID as the `parent-id`)?

**Comment by azdagron** [comment]
This idea hasn't gained traction for a few years now. Closing for now.
