### ISSUE TITLE
Configurable SVID Rotation Frequency

### ISSUE THREAD

**Issue by aybabtme** [spiffe/spire#1754]
SVID rotation frequency is currently [a hardcoded function of a registration entry's TTL](https://github.com/spiffe/spire/blob/master/pkg/common/rotationutil/rotationutil.go#L39-L43). This logic makes the rotation (or refresh frequency) happen whenever a SVID is at 50% of its expiry time. e.g. for a 7 days TTL, the refresh happens after 3.5 days.

We'd like to be able to configure how often a SVID is rotated so that we could have more control over our reaction/remediation duration (having more time on our hands to react to problems with our Spire deployment), without having to increase the TTL of registrations.

## example

We want 7 days TTLs for most of our SVIDs. We want to have 6 days available for remediation before the expiry of a SVID. Therefore, we want the refresh period to be no longer than every 1 day. This way, if for some reason, spire-agent or spire-server are unavailable, we have 6 days to bring it back up, or manually install replacements x509 certs. With 6 days, we can be reasonably sure that we'll have a full business week available to us to respond and handle the incident. On the other hand, 3.5 days (status quo) could easily land on a Friday before a long weekend.

## suggested implementation
The current code for rotation logic lives in the Agent. However, the configuration of refresh frequency seems to be a per-registration entry concern, similar to where the TTL lives. As such, while I believe the easiest way to get this implemented is to provide a config option in the agent's config, I believe the proper place to do this is on the registration entry itself. I suggest that we provide [a `refresh_strategy` field on the registration entries next to the TTL](https://github.com/spiffe/spire/blob/master/proto/spire/common/common.proto#L68-L69), which would be a nullable `oneof` value, with (to start) a single strategy named `fraction_of_ttl` that would allow configuring the `0.5` fraction of TTL to be some other floating value. The default value, if no `refresh_strategy` is provided, would use the current rotation algorithm.

### additional notes: thundering herds

We noticed that there doesn't seem to be any randomization/jitter applied to the refresh frequency. We envision that this could lead to unexpected synchronization of refreshes and then lead to thundering herds. I think part of this work should introduce a random jitter to rotations/refreshes.

* * *

Discussion [in Slack](https://spiffe.slack.com/archives/C7XDP01HB/p1595611089447300)

**Comment by amartinezfayo** [comment]
Thank you @aybabtme for filing this issue, I think that having a configurable SVID rotation frequency would be a good thing to have.
I feel that a per-workload attribute in each registration entry may be overkill. I believe that most of the time you would want to have an uniform policy and not be as granular as per-workload.
What do you think about having a global configurable in the agent's config? Would that be sufficient for your needs and the use case that you have?

**Comment by azdagron** [comment]
I wonder if we would be providing a very sharp edge that operators can (mis)use? TTL and rotation strategy in general has non-trivial ripple effects that can be hard to diagnose when things go wrong. There could also be indirect consequences like signing load on servers. This could be reflected in per-op costs for folks who are using the KeyManager plugin against some sort of key management API. The configurable could also  contribute to increased database/disk activity at some point when we get to adding stuff like SVID issuance audit logs and the like.

TTLs are very much an availability v.s. security tradeoff. Could you get roughly the same availability by doubling your TTL to 2 weeks (making the repair window 5 days)?. Is the 1-week SVID TTL some sort of hard requirement?

Even if this was scoped to just workloads and not agent/server SVIDs, that could have impact on downstream SPIRE servers who obtain "downstream" workload identities in order to authenticate with upstream SPIRE. 

All that being said, I don't think this is necessarily an unreasonable ask by any means. My concern is that a fraction is somewhat open ended. I wonder if there is another strategy that can either 1) be applied automatically or 2) is simpler than a fraction. As an example, @APTy reminded me that SPIRE server has a clamping strategy that caps the rotation interval to 30 days so that in the face of a much higher CA TTL, we still keep things fresh roughly once a month. Maybe we can do something similar to that? Either by automatically setting a maximum refresh interval or providing a configurable for a minimum number of days or something?

**Comment by mcpherrinm** [comment]
One minor detail:

If we have a completely arbitrary percentage or ratio, it's possible there's values that could be troublesome.  For example, if the ratio is way too small, we may have some internal assumptions about things like timers that won't hold, leading to bugs.

We could clamp (say, allowing percentages between 10 and 90), or we could have something like a set of enum values that represent strategies (say:  early, middle, late; as 25%/50%/75% - but possibly even other strategies too like "daily")

**Comment by aybabtme** [comment]
I think a clamp strategy instead of a ratio would work best for our immediate use case, and cause the least amount of weird edge cases. I like this idea! I mentionned the `ratio` idea has a starting point, I'm definitely not married to it.

> I feel that a per-workload attribute in each registration entry may be overkill. I believe that most of the time you would want to have an uniform policy and not be as granular as per-workload.
> What do you think about having a global configurable in the agent's config? Would that be sufficient for your needs and the use case that you have?

Since the TTL is configured per-workload, it seems to follow that the rotation of the workload would probably be a per-workload too. I think having global defaults enforced somewhere (I'd think on the spire-server or the DB) would make sense, with the ability to override it per-workload. However it would be weird to have this config or default defined on the agents: it could lead to the same workload on a different host having the same TTL but a different rotation strategy.

I do agree that adding this config knob to the agent is the easiest approach, but I can't help but think it's also the least-right location in the grand scheme of things.

> There could also be indirect consequences like signing load on servers. This could be reflected in per-op costs for folks who are using the KeyManager plugin against some sort of key management API. The configurable could also contribute to increased database/disk activity at some point when we get to adding stuff like SVID issuance audit logs and the like.

That is true, but the same is true from configuring TTLs. I'm not so concerned about this, since arguably operators of a spire installation are going to have this in mind and have monitoring in place to track health and performance.

> TTLs are very much an availability v.s. security tradeoff. Could you get roughly the same availability by doubling your TTL to 2 weeks (making the repair window 5 days)?. Is the 1-week SVID TTL some sort of hard requirement?

We want to be aggressive with TTLs while still having enough time to mitigate a large outage. As such, we chose 1 week as the shortest value that is still likely to cover a period large enough to accommodate staff going vacations, long weekends, statutory holidays. Arguably there's always someone on call that would answer, but I think everybody can see where a 3.5 day expiry window, with an outage happening Friday evening of a long weekend - as they always do - isn't going to make for a happy and effective crew 😅. So I wouldn't say that 1 week is a hard requirement, there's nothing that mandates it. It's a very pragmatic number from our point-of-view, balancing aggressive TTLs with our human reality.

**Comment by azdagron** [comment]
Awesome, a coarse grained configurable sounds like a good tradeoff to me.

**Comment by aybabtme** [comment]
@azdagron just to summarize and make sure we're on the same page before I go ahead and implement the change:

- Use a "clamp strategy" instead of a "ratio strategy"
- Put the rotation strategy as a configurable on the registration entries, not in the server or the agent's configs.
- (maybe) Adding jitter to the rotation? I think it'd be a very good idea.

**Comment by azdagron** [comment]
> Use a "clamp strategy" instead of a "ratio strategy"
Yep :+1: 

> Put the rotation strategy as a configurable on the registration entries, not in the server or the agent's configs.
We discussed this a little bit during our maintainer call. I think the general consensus was that while per-entry configuration here might be desired eventually that maybe we start with an agent-side global configuration to see how things panned out. If at some point we decided to do a per-entry configurable, we'd be going into it with some experience that might shape the design. If what we implement (i.e. "clamp strategy") ends up not being exactly what we want, it's potentially easier to migrate an agent configurable than per-agent registrations. In other words, let's start small and see how well this fits.

> (maybe) Adding jitter to the rotation? I think it'd be a very good idea.
I also think jitter is good, probably only for larger intervals though. I'm not sure what the threshold should be but jitter on a small TTLs (like those we set in integration tests) could lead to SVID expiration due to all of the internal timings of things. Maybe 1m? 5m? I'm open to debate here.

**Comment by joewilliams** [comment]
> We discussed this a little bit during our maintainer call. I think the general consensus was that while per-entry configuration here might be desired eventually that maybe we start with an agent-side global configuration to see how things panned out.

I think the main caveat with the agent-based config for the rotation strategy is with multi-tenant deployments. When we have multiple SVIDs to a single agent we can only tune the rotation at the host-level rather than the workload. For our kube based workloads this is probably a non-starter.

> I also think jitter is good, probably only for larger intervals though. I'm not sure what the threshold should be but jitter on a small TTLs (like those we set in integration tests) could lead to SVID expiration due to all of the internal timings of things. Maybe 1m? 5m? I'm open to debate here.

I think we can avoid this by making jitter default to `false`maintaining existing behavior. Additionally, jitter could follow a similar clamping pattern to the rotation strategy. Where it is additive to the cert lifetime, rather than plus or minus. To be suitable for short TTLs this would likely need to be set to a limit of a percentage of the TTL (i.e. 30s TTL with 0.5 jitter would mean certs would get refreshed between 30 and 45s).

**Comment by joewilliams** [comment]
> To be suitable for short TTLs this would likely need to be set to a limit of a percentage of the TTL (i.e. 60s TTL with 0.5 refresh frequency 0.5 jitter would mean certs would get refreshed between 30 and 45s).

One point of clarification, this would need to be clamped at some value lower than the TTL. 

```
60s TTL
60s * 0.5 refresh = 30s
30s * 0.5 jitter = 0 to 15s
refreshes every 30 to 45s
```

Chatting with @aybabtme we probably want to limit the jitter to allow for a minimum of two refresh attempts before the TTL expires. If we were to make that guarantee we'd need to either put a limit on the maximum jitter as a portion of the TTL and refresh rate, to ensure two refresh attempts can always fit within the TTL, or do some sort of tricky negative exponential back off with each refresh attempt.

**Comment by aybabtme** [comment]
What I have in mind is make the "maximum rotation duration" be like:
```hcl
rotation_clamp: 1d
rotation_jitter: -0.05 # -5% of clamp
ttl: 7d
```
with the jitter, the effective value for `rotation_clamp` would then be a uniform random pick within `(0.95 day, 1 day]`

**Comment by joewilliams** [comment]
> with the jitter, the effective value for rotation_clamp would then be a uniform random pick within (0.95 day, 1 day]

Bounding it on the rotation clamp makes a lot of sense to me :+1:

**Comment by hiyosi** [comment]
We would like to have this feature in our environment. 
Is this work going?

**Comment by aybabtme** [comment]
I personally am not working on this.

**Comment by azdagron** [comment]
There hasn't been any interest in this in over a year. We also have struggled to see how we can support this with a good user experience. I'll go ahead and close for now. We're happy to consider a feature like this. Please open a new issue if interested.
