### ISSUE TITLE
Add SPIFFE ID to CN of SubjectName instead of first DNS

### ISSUE THREAD

**Issue by blaggacao** [spiffe/spire#1795]
Coming from: https://github.com/spiffe/spire/pull/1761#discussion_r471055634

It is not well documented as to what motivation lead to the implementation of using the first DNS record as the _CommonName_ within the _DistinguishedName_. Therefore, I can imagine, that at the time of implementation, it was just assumed to be the right thing to do.

However, X509 elaborates about the _SubjectName_ attribute to be a _DistinguishedName_ of [X500](https://tools.ietf.org/html/rfc1779#section-2.3), which in turn defines the below BNF, the quid of which is resumed in the following quote:
> The quoting mechanism is used for the following cases:
    o  Strings containing ",", "+", "=" or """ , \<CR\>, "<", ">", "#", or ";".
    o  Strings with leading or trailing spaces
    o  Strings containing consecutive spaces

Hence, `spiffe://trust.domain/path/to/identity` — even without quoting — is a perfectly valid string for a `CN`:
`CN=spiffe://trust.domain/path/to/identity, OU=SPIFFE, C=US`

Some implementations are not (yet) capable of inducing identity from the SAN list (e.g. OpenLDAP), those still rely on the SubjectName attribute. So if both, subjectAlternativeName.URI[0] and SubjectName convey identity, I'd argue it would make more sense to represent those identities by the same string identifier. See also: https://github.com/spiffe/spire/issues/1793

```bnf
   <name> ::= <name-component> ( <spaced-separator> )
          | <name-component> <spaced-separator> <name>

   <spaced-separator> ::= <optional-space>
                   <separator>
                   <optional-space>

   <separator> ::=  "," | ";"

   <optional-space> ::= ( <CR> ) *( " " )

   <name-component> ::= <attribute>
           | <attribute> <optional-space> "+"
             <optional-space> <name-component>

   <attribute> ::= <string>
           | <key> <optional-space> "=" <optional-space> <string>

   <key> ::= 1*( <keychar> ) | "OID." <oid> | "oid." <oid>
   <keychar> ::= letters, numbers, and space

   <oid> ::= <digitstring> | <digitstring> "." <oid>
   <digitstring> ::= 1*<digit>
   <digit> ::= digits 0-9

   <string> ::= *( <stringchar> | <pair> )
            | '"' *( <stringchar> | <special> | <pair> ) '"'
            | "#" <hex>


   <special> ::= "," | "=" | <CR> | "+" | "<" |  ">"
            | "#" | ";"

   <pair> ::= "\" ( <special> | "\" | '"')
   <stringchar> ::= any character except <special> or "\" or '"'


   <hex> ::= 2*<hexchar>
   <hexchar> ::= 0-9, a-f, A-F

```
/cc @JonathanO

**Comment by faisal-memon** [comment]
Are you proposing to duplicate the ID in the CN field or to drop the URI field altogether?

**Comment by blaggacao** [comment]
**Duplicate**, since if I recall correctly, subjectName is alreay kr on its way ro deprecation...

**Comment by evan2645** [comment]
Hello @blaggacao 

SAN URI field, in particular, was chosen to carry the SPIFFE ID for X509-SVID because we wanted it to be clear that the SPIFFE ID is _not_ a network locator (note URI not URL). One of the original SPIFFE assertions was that workload (and/or service) identity is distinct from "network" identity (e.g. IP address or DNS name does not suffice for workload identity).

In practice, CN field is used when performing web PKI auth by matching CN value to the locator used when initiating the connection (see [RFC 6125](https://tools.ietf.org/html/rfc6125) for more detail). This means that typically, a DNS name is expected as the value for CN in the context of web authn. I realize that this may not be the universal case (especially when considering client authentication), but it is by far the most prevalent case.

Adding support for CN in SPIRE was done with a nod in this direction. For example, my off-the-shelf load balancer may not understand SPIFFE auth, but the workloads it's sending traffic to are SPIFFE-enabled workloads. The load balancer needs a way to validate the SPIFFE cert it encounters, and populating the workload's DNS name in the CN field (or DNS SAN) accomplishes that. This specific case was the motivating factor for this feature.

As for "the first DNS name is the CN" - we recognized that a single workload may serve traffic for more than one DNS name, and multiple DNS SANs may be specified on a single certificate, however there can only be one CN. So, we simply chose the first specified DNS name as the CN value.

This overloading of Common Name (is it the name of the thing? Or the DNS name? Or the IP address?) is one of the primary reasons for CN deprecation in favor of typed SANs.

It is a little difficult for me to reason about putting SPIFFE IDs in the CN field (regardless of whether it's syntactically allowed or not), but I'd still like to hear more about your specific use case. I briefly read through the conversation in the linked PR, but I still don't think I quite grok the situation.

**Comment by blaggacao** [comment]
@evan2645 I hear you. I suspected the choice was historically based on those common (llegacy) practices in the Server TLS environment.

> This overloading of Common Name (is it the name of the thing? Or the DNS name? Or the IP address?) is one of the primary reasons for CN deprecation in favor of typed SANs.

Cannot agree more.

> The load balancer needs a way to validate the SPIFFE cert it encounters, and populating the workload's DNS name in the CN field (or DNS SAN) accomplishes that.

Since deprecation of subjectName _for that purpose_, most implementations will probably validate via DNS SAN. In my use case (LDAP), this is actually the case.

So, having presented a valid certificate for any given hostname out of possible hostnames, we are left with the problem of extracting the _identity_ out of the certificate for authC. LDAP is only able to look at the _entire_ DN (SubjectName). So LDAP regards the entire DN (CN + O + CO) of the SubjectName as the trusted identity.

Therefore, SubjectName's DN (outside of https TLS), may have been originally conceived as the identity carrier (and https TLS just made a dirty hack out of it).

In this regard, it does _not_ seem wrong to expose the SPIFFE ID as URI SAN, but it _does_ seam wrong not to _also_ convey the identity in the DN (with SPIFFE's configurable `O` & `CO` - that's perfectly fine). To satisfy the https hackery of the past: stowed away behind an option for originals like LDAP and the like - which use X500 DNs as they where meant.

**Comment by azdagron** [comment]
This kind of behavior will be customizable with the introduction of the [CredentialComposer](https://github.com/spiffe/spire/issues/3253) plugin. Closing this issue in favor of that work.
