### ISSUE TITLE
Support multiple CA bundle files in x509pop NodeAttestor configuration

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#1819]
When multiple NodeAttestors of the same type, e.g. `x509pop`, are specified in the configuration for SPIRE Server, the Server only enables the first one specified in configuration and silently ignores the remaining NodeAttestors specified in configuration.

In a heterogenous environment, there may be more than one "class" of node within the infrastructure, where nodes in different classes present different node attestation material of the same type, i.e. two nodes attesting using X.509 certificates with different chains of trust. It seems like the only way one could assign nodes in these different classes identities in the same trust domain would be to configure separate instances of SPIRE Server with different NodeAttestor configurations and configure SPIRE Agents running on nodes in "class A" to point to "class A" SPIRE Server instances, nodes in "class B" to point to "class B" SPIRE Server instances, etc. This significantly complicates deployment of SPIRE, and seems unnecessary.

It would be useful to be able to configure a single instance of SPIRE Server to treat these different classes of nodes as part of the same trust domain in order to simplify SPIRE deployment.

**Comment by evan2645** [comment]
Thank you very much for opening this @rturner3. SPIRE Server is definitely intended to be able to load multiple node attestors at once. The behavior you describe sounds like a bug.

**Comment by azdagron** [comment]
If I'm reading this correctly, you want two `x509pop` attestors for example. SPIRE only allows one attestor for each name because the name is used to route the incoming attest request to the right plugin. If we want to support this, we either need to find a new way to marry up the agent attestation stream with the correct server attestor or provide a way to "alias" a plugin name (e.g. assign an the `x509pop` plugin the name `x509pop_foo`). Agents would also need to be configured with the same alias in order for the current routing strategy to continue as-is.

**Comment by azdagron** [comment]
The end result seems like a very reasonable request. I think we can come up with a decent solution.

**Comment by azdagron** [comment]
I'm a little curious though, for this specific circumstance, the file pointed to by `ca_bundle_path` in the server configuration cannot contain roots for both "class A" and "class B"? The selectors added to the attested agent would still uniquely identify which root the agent's chain was verified by...

**Comment by evan2645** [comment]
Ah sorry, yes... @azdagron is right, I misread the original post.

There are other attestors that are capable of this kind of functionality without having to load an additional instance of the same plugin. For example, the k8s attestor can be configured to attest agents in multiple k8s clusters.

**Comment by rturner3** [comment]
Dumping all the trusted roots into a single file does seem like a possible solution here. It is just a little inconvenient because the CA files for "class A" and "class B" nodes (as an example) can be independently managed, so in my case I would need to write some custom code to merge the contents of both CA files into a single file before startup of SPIRE Server.

Perhaps another possibility could be for the `x509pop` NodeAttestor to support configuring multiple CA bundle files?

**Comment by amoore877** [comment]
> Perhaps another possibility could be for the x509pop NodeAttestor to support configuring multiple CA bundle files?
I think this could be the solution with the least changes needed:
- version 1- allow the plugin to take both the single CA bundle file field it does today + a list of CA bundle files. Log a warning if the single file field is set that this will be deprecated. Append the single field (if filled out) to the list in the plugin.
- version 2- get rid of the single file field, use only list.

**Comment by amoore877** [comment]
To point out another use case of this, when rotating CAs or CA bundles it may make more sense to maintain the new bundles as new files, rather than appending to the old:
- change controlling PEM block files is not very user friendly. A human can't tell 100% without decoding what is what.
- we will want to keep the ability to still allow the old bundle for some time (maybe all the way to expiry), while still being secure in the knowledge the old bundle is unchanged- we have not appended to it, so behavior should be the same
