### ISSUE TITLE
Can k8s-workload-registar works with k8s_SAT node attestor?

### ISSUE THREAD

**Issue by PriyaKatkade** [spiffe/spire#1825]
Can k8s-workload-registar works with k8s_SAT node attestor?
I have gone through https://github.com/spiffe/spire/tree/master/support/k8s/k8s-workload-registrar this documentation but didn't find   where I can use this with k8s_SAT node attestor or not.

**Comment by azdagron** [comment]
The registrar does not work with k8s_sat attestation. At the time it was authored, we'd hoped to deprecate `k8s_sat` shortly since it has some unwanted security properties. As such, only `k8s_psat` was considered for the registrar. However, at the time, there were a number of managed Kubernetes providers that didn't support PSAT. It is more widely supported now. There would be some work involved to adapt the registrar for `k8s_sat` since the available selector set is reduced, so before adding any support there we'd want to make sure we'd still be supporting `k8s_sat` for some time. #1827 has been opened to help determine what that timeline looks like and if any effort would be worth it.

Does your Kubernetes environment not support PSAT? https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection

**Comment by PriyaKatkade** [comment]
Okay and Thanks @azdagron 
WE are using EKS cluster. To use k8s_PSAT we need to configure it to support PSAT.

**Comment by azdagron** [comment]
Awesome. I believe EKS gained support for projected tokens for clusters running 1.13+ some time late last year.
