### ISSUE TITLE
support "does not exist" selector type

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1833]
In a complex deployment environment, some workloads may be only meaningfully differentiated by the existence or non-existence of an env/label attribute.

For instance, a workload scheduler `A` may deploy some service `foo` with:
```
docker:env:SERVICE_NAME=foo
docker:env:ENVIRONMENT=production
```

now let's say `foo` is also deployed by a new scheduler `B`.
`B` workloads are considered to have a different level of security or required access, so we want a different identity for `foo` A and `foo` B, without unnecessarily changing `foo` or `A`'s behavior.

For `B` deployment selectors:
- Using the same selectors as above, both the A and B deployments would get both A and B identities.
- Using a superset of the selectors above, `foo` B would get both A and B identities.
- Altering the values of the selectors above, we may wind up altering `foo`'s behavior (they are environment variables).

But what if `B` applies a meaningful container config (eg, `docker:env:DEPLOYER=I'm B`) that `A` does not apply to its own container deployments? We could alter the `A`-type registrations by adding a "not exists" selector:
A-
```
docker:env:SERVICE_NAME=foo
docker:env:ENVIRONMENT=production
docker:**no_env**:DEPLOYER
```
B-
```
docker:env:SERVICE_NAME=foo
docker:env:ENVIRONMENT=production
docker:env:DEPLOYER=I'm B
```

**Comment by evan2645** [comment]
I worry about the edge cases that could open up by introducing selector negation. For instance, if a selector is asserted by a workload attestor, we have a very high degree of confidence that it is true. The same cannot be said for the absence of a selector however, because absence can be true absence or it can also be caused by a workload attestor failure (misconfiguration, a timeout, etc). We actually see this a fair bit in the wild, and when it does occur, it could lead to the inappropriate issuance of an identity which is a very big problem. My main point here is that it is not as simple as adding negation and moving on.

The docker workload attestor produces not just `env` selectors, but also `label` selectors. One solution to the problem you're describing is to add a label to both A and B variants of `foo` in order to distinguish them. Another solution could be to use docker selectors in addition to selectors from a different attestor for differentiation. And yet a third solution could be to leverage Parent ID arrangements to distinguish the two. To me personally, these routes seem much less complicated and error prone than evaluating the addition of selector negation.

**Comment by jkanywhere** [comment]
> because absence can be true absence or it can also be caused by a workload attestor failure (misconfiguration, a timeout, etc). . We actually see this a fair bit in the wild,

You're saying that SPIRE cannot tell the difference between attestor success and failure? Perhaps because a dependency always exits 0 even on failures?

> To me personally, these routes seem much less complicated and error prone than evaluating the addition of selector negation.

Each consumer of SPIRE may evaluate the tradeoffs differently.

>  One solution to the problem you're describing is to add a label to both A and B variants of foo in order to distinguish them. 

We considered this and are pursuing it. However it is non-trivial to add a label to every container in the fleet. It requires modification of multiple systems.

> And yet a third solution could be to leverage Parent ID arrangements to distinguish the two.

We're currently registering workloads to clusters of servers. A and B variants are registered to the same Parent ID.
Even if we were registering with a specific server as Parent ID, this would require the scheduler ensure A and B are never co-located.

> Another solution could be to use docker selectors in addition to selectors from a different attestor for differentiation.

We can look into it.

**Comment by evan2645** [comment]
> You're saying that SPIRE cannot tell the difference between attestor success and failure? Perhaps because a dependency always exits 0 even on failures?

Current SPIRE behavior is to do best-effort attestation. If we received an error from a workload attestor, we still collect the selectors we can from other attestors and attempt to match the workload to an identity. There are other cases where things like this can occur - for example, an agent could have a workload attestor erroneously excluded from its configuration. There are even cases where an attestor could appear to succeed but still return zero selectors - the k8s attestor does this if it believes that the caller is not a k8s workload.

I think that, in the end, proving a negative can be tricky.

This issue was briefly discussed in the last SIG-SPIRE call, which called my attention back to it - so, apologies for the late reply, I had missed your comments.

**Comment by azdagron** [comment]
This issue is a bit stale and there has been little interest. Closing for now.
