### ISSUE TITLE
Cleaner importing of spire

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#1839]
Built-in plugins bring in dependencies on AWS, GCP, Kube, etc. libraries. While it is very nice to have some "default" functionality available in SPIRE, these dependencies can have some drawbacks.
- In trivial case, repositories importing SPIRE must now be dependent on non-conflicting libs that they are making no use of, but nothing else occurs.
- In a more problematic case for developers, the dependencies lead to conflict within a large repository.
- Another problematic case is if the direct dependencies of SPIRE itself do not conflict, some other dependencies further down the tree do conflict or otherwise introduce breaking functionality. https://github.com/etcd-io/etcd/issues/12124 is a real world example.

The only resolutions are to either ask this project (or other upstream projects + this one) to change its dependencies/code, or to change the internal dependency(ies) for the org, and it's possible that neither is a tractable solution.

Importing of SPIRE should be made as minimalist as possible. We already have a separate module for `proto`. I suggest carrying this forward further by removing specialized "built-in" plugins as their own repos/modules.

**Comment by azdagron** [comment]
I'm not sure I'm following how the proposed solution would solve anything. Even if you made the built-in plugins their own go module, since the plugins are built-in and not compiled separately, SPIRE would need to import those modules, and therefore would still transitively bring in the dependencies those plugins require.

We've considered moving commonly imported machinery into its own repo, for example, plugin scaffolding and API client code. Doing so should reduce the need to import anything from the main SPIRE repo for normal use cases.

Can you share what you are importing from SPIRE?

**Comment by amoore877** [comment]
The context of this discussion has been internally lost, and is moot in face of our new route to make importing of SPIRE into our monorepo more manageable (our own fork).
I think this can be closed.
