### ISSUE TITLE
Allow SPIRE Server to run in mode without registration Unix Domain Socket

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#1842]
SPIRE Server allows clients to perform CRUD operations on registration entries in one of two modes:
1) Anonymously via a Unix Domain Socket created by SPIRE Server
2) With an admin X.509 SVID used as the client certificate in an mTLS connection to the SPIRE Server TCP endpoint.

The first mode offloads the responsibility of controlling who can access the registration APIs to the administrators of the host through Unix permissions (i.e. who can access the host and who can access the socket on the host). Many times, the full set of administrators of a host can include users who are not themselves directly responsible for operating SPIRE, i.e. infrastructure administrators. It may not be possible to restrict control over the Unix Domain Socket to only a subset of these host administrators (i.e. SPIRE operators).

Registration API requests over the Unix Domain Socket are also not audited and are treated as anonymous admin users in SPIRE. This creates operational burden on SPIRE administrators to bolt on host-level auditing controls for this particular set of registration APIs.

For these reasons, it may be worthwhile to provide a way to start SPIRE Server in a mode that does not expose a gRPC registration API server listening on a Unix Domain Socket.

Running SPIRE Server without the UDS server presents another problem though, since in order for any "admin registrant" workload to create registrations in SPIRE Server over the TCP endpoint, it needs to present an admin X.509 SVID during the TLS handshake. And in order for the SPIRE Agent workload API to deliver that admin X.509 SVID to the "admin registrant", there needs to be some existing registration for that admin identity in SPIRE Server.

To solve that problem, SPIRE Server could potentially accept as optional configuration some static set of registrations that are created upon startup. These static "admin registrant" registrations could bootstrap an ecosystem of workload registrants, who then create the full set of registrations needed in SPIRE Server for the environment.

Running SPIRE Server in this mode admittedly complicates the bootstrapping of SPIRE, but it seems like a reasonable tradeoff to me considering the benefits of a more tightly-controlled access control mechanism (along with a solution to #716) and the possibility of registration entry operation auditing in SPIRE.

**Comment by amartinezfayo** [comment]
Thank you @rturner3 for bringing up this problem.
I'm a little concerned about the implications of the proposed solution, both in terms of security and usability.
Having statically configured registrations opens the possibility of having multiple views of the set of registrations across the running SPIRE servers, which propones a challenge to maintain the consistency of the data. The consistency of registration entries is security sensitive, and particularly registrations with the admin bit set. Some questions that I have are around how this would be managed. Those statically configured entries would live only in memory? Would SPIRE Server try to persist those entries in the datastore? What happens when there are multiple servers trying to register an entry with the same SPIFFE ID, parent ID, selectors and a different attribute like the TTL? Looks like there are a lot of race conditions to consider here. It also expands the attack surface that admin entries are exposed.
The above mentioned challenges also impact on the user experience, having more ways to register entries and opening the possibility to have a misconfigured system.

I'm not negating the existence of the problem. I just want to bring up some initial thoughts about the proposed solution to start a discussion around this.

Before going down the path of exploring these changes it may worth thinking about why SPIRE does not facilitate the control/audit of the registration operations. Is there something in SPIRE that makes difficult to set the proper ACL to the registration socket? Maybe we can do a better job at auditing the registration calls?

**Comment by rturner3** [comment]
These are really good questions, @amartinezfayo . There is definitely some complexity around management of static registrations, another case being how do you update a static registration safely?

Reflecting on it a bit more, I think the primary concern that was driving this issue for me is the auditing piece. One solution  that was being discussed today is having some "attestation" mechanism where the registration endpoint server discovers the effective Unix `uid` of the process connecting to the Unix Domain Socket by examining `procfs`, exactly how the Agent `unix` workload attestor plugin functions today. Having this functionality would enable #1207 for the registration UDS server. This is something that could probably be enabled relatively quickly and doesn't result in any significant design challenges that I can think of.

I still think supporting a mode without the registration UDS has some value, but some more thought needs to be directed towards a workable solution for it. Perhaps that can be addressed as a second step.

**Comment by blaggacao** [comment]
Pre-Shared Key Solution:
- A single initial admin join token? (without TTL, and immediate expiry after consumption)
