### ISSUE TITLE
Determine how we should do signed releases

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#1860]
This should include research into best practices for how other projects accomplish this today.

**Comment by APTy** [comment]
In looking at some other CNCF projects that do signed releases, I came across [TUF's release process](https://github.com/theupdateframework/tuf/blob/7cc41c6fee69bf805bfef3f5842a50f712e2fc7f/docs/RELEASE.md), which uses GPG to sign releases. This seems like a good approach (and what many other projects from libcurl to in-toto seem to follow). But as it turns out, TUF (The Update Framework) itself provides tooling for securely upgrading software. This seems like a really powerful approach, but also involves deploying some services, and I wonder if it would be easier to just go the GPG route and host the public keys on a static page.

**Comment by evan2645** [comment]
Thank you @APTy for looking into this!

I feel there are at least three questions that we need to answer as part of this issue:
* Exactly what threats are we trying to mitigate through the use of release signing
* What technology should be used to actually accomplish the signing
* How are the keys associated with the signature(s) managed/stored/accessed

The answer to the first question is likely to inform the shape of the answer to the second two, so I think it makes sense to start there?

@anvega has asserted that we need to mitigate release tampering for air-gapped consumers, or consumers that utilize internal (non-GitHub) software repositories. That makes good sense to me. I wonder though if there are other (similar?) threats that we should be trying to mitigate as well? For example, do we also want to mitigate the impact of compromised developer accounts/credentials? That could certainly be used as a vector for release tampering, and is decidedly much harder to solve than the first concern alone.

I am not certain of the answer here just yet. In answering it though, we should choose the threats we wish to mitigate carefully. Otherwise, the cost of mitigation could be prohibitive, or mitigation could be ineffective if the threats aren't well understood.

I'm curious to hear from others on this point in particular. There is likely a practical approach that mitigates some but not all of these threats, and so long as it is clearly communicated, that's probably the right path forward (for now).

**Comment by colek42** [comment]
I could not find any documentation that stated GCR supports signed images.  However, I noticed you have a Docker hub account that could be used for this purpose with GCR as a mirror.  https://docs.docker.com/engine/security/trust/

DataDog wrote about their secure software delivery pipeline here:  https://www.datadoghq.com/blog/engineering/secure-publication-of-datadog-agent-integrations-with-tuf-and-in-toto/ .  Managing the PKI in the aforementioned architecture with SPIFFE/SPIRE would be an interesting additon.

**Comment by azdagron** [comment]
There have been many advances in this field since this issue was opened (e.g. sigstore, etc.). I think we have several options for this if/when we go down this path.
