### ISSUE TITLE
Spire image running as root

### ISSUE THREAD

**Issue by janssk1** [spiffe/spire#1862]
I'm trying to deploy spire server (latest version) in a kubernetes cluster that requires all pods to run as nonRoot. 
However, since the spire docker image runs as root, its not allowed to start. As a workaround, i can give some special rights to the spire service account, but i would like to prevent that.

Any reason for spire to run as root ? 

 Normal   Pulled     18s               kubelet, node5     Successfully pulled image "gcr.io/spiffe-io/spire-server:0.11.0"
 Warning  Failed     3s (x3 over 18s)  kubelet, node5     Error: container has runAsNonRoot and image will run as root

**Comment by azdagron** [comment]
Thanks for opening this @janssk1. @rturner3, can you look into this?

**Comment by rturner3** [comment]
Hi @janssk1 , overall, executing SPIRE as a non-root user seems like something SPIRE should support. There shouldn't be any specific reasons why SPIRE itself must run as `root`, and I believe it doesn't require any elevated privileges for Linux capabilities. As to the reason why the Docker images are using the `root` user today, I believe this is mostly an artifact of the default behavior of Docker to execute Unix containers as the `root` user.

I did some experimentation with the Dockerfile to set up a dedicated user + group for the SPIRE images in this branch - https://github.com/rturner3/spire/commit/d3c301108e023a2a68333ef273dab763fd1e6ed4

Unfortunately, it looks like there are currently some problems using images generated from that Dockerfile in k8s deployments because of the way Kubernetes handles shared volume mounts. This can be reproduced from my branch by running:

```
$ make images
$ cd test/integration
$ ./test-one.sh suites/k8s
```

What I noticed is that Kubernetes creates `hostPath` volumes with `root:root` owner on the node's filesystem and mounts them into the containers in the pod using the same owner/file permissions as on the node's disk. I experimented with using `fsGroup` in the [PodSecurityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod), but it didn't seem to work for me. The only workaround I could find was to add an init container to my deployment that ran as root which performed a `chown` on the directory referred to in the `hostPath` volume. It sounds like this wouldn't work for your use case since the pod's security context is enforcing that containers within the pod don't run as `root`. Example of this workaround: https://serverfault.com/a/907160

The reason why this volume mount problem is an issue for SPIRE is because SPIRE Server needs to expose the registration Unix domain socket outside of its container, and SPIRE Agent needs to do the same for the Workload API Unix socket. Given that Kubernetes is a common environment for running SPIRE in Docker containers, I would like to see some solution for this volume mount ownership problem in Kubernetes before changing SPIRE's Dockerfile. Just for reference, I found what appears to be the relevant issue for this in the Kubernetes project, and it has been open for a very long time (since 2014): https://github.com/kubernetes/kubernetes/issues/2630

**Comment by janssk1** [comment]
AFAIK, hostPath is meant to expose files from host to pods, and is considered deprecated. Seems you are using it in a creative way to share a unix socket. There are probably different ways of implementing secure communication between agent and server that don't require hostPath. But i haven't investigated it in detail...

**Comment by rturner3** [comment]
I couldn't find any Kubernetes documentation suggesting that `hostPath` is a deprecated volume type. But it does appear that it doesn't suit this particular scenario of sharing a Unix socket with multiple pods running containers as non-root users.

@janssk1 Do you have any experience with sharing host-local files like this between Kubernetes pods? I looked into other volume types in Kubernetes, but I didn't see any clear-cut alternative for this use case.

**Comment by janssk1** [comment]
I recently discovered the kubernetes bound service account token feature (https://docs.openshift.com/container-platform/4.4/authentication/bound-service-account-tokens.html). Its kind of an identity service provided by native kubernetes. It can be used to setup trust between different services.  I guess you could consider using that as a way to authenticate the sidecars towards the deamonsets. But if you already get a secure identity token, there might be little value left for spire..

**Comment by jkevlin** [comment]
@rturner3 Have you been able to make any progress on this?

**Comment by rturner3** [comment]
> I recently discovered the kubernetes bound service account token feature (https://docs.openshift.com/container-platform/4.4/authentication/bound-service-account-tokens.html). Its kind of an identity service provided by native kubernetes. It can be used to setup trust between different services. I guess you could consider using that as a way to authenticate the sidecars towards the deamonsets. But if you already get a secure identity token, there might be little value left for spire..

The problem here is actually not the Agent to Server communication path (this is done over a TCP socket), it is the communication between identity registrants and SPIRE Server. The registration APIs are accessible either over TCP or over the registration Unix socket, so there might be some approach where SPIRE can run in a fashion in Kubernetes such that all registrants only use the TCP socket. See https://github.com/spiffe/spire/issues/1842 for a related issue that discusses the possibility of SPIRE Server running in a mode that does not expose the registration Unix domain socket.

I haven't had a chance to experiment with this myself, but I believe a solution would most likely require some changes in the [k8s-workload-registrar](https://github.com/spiffe/spire/tree/master/support/k8s/k8s-workload-registrar) because that depends on the registration Unix socket today. I haven't evaluated the feasibility of k8s-workload-registrar working in this mode yet though.

I probably won't have time in the near future to explore this in detail because of KubeCon this week and holidays next week, but @janssk1 I'm happy to continue discussing the issue here if you have any more thoughts on this.

**Comment by jkevlin** [comment]
@rturner3 I can confirm that adding the init container works. This solves my problem for the time being as I can get an exception for the initcontainer.
          initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /run/spire/sockets"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets

**Comment by jheiss** [comment]
Rather than hostPath I would use an emptyDir to share the socket between containers in a pod.

https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

**Comment by jkevlin** [comment]
I found this blog post on the perils of hostPath with root access.
https://mauilion.dev/posts/kind-pvc-localdata/
The post also suggest using a [persistent-volume](https://mauilion.dev/posts/kind-pvc-localdata/#persistent-volumes)

**Comment by azdagron** [comment]
This issue highlights several reasons why the SPIRE image currently runs as root. The hostPath issue has been largely solved through the use of the [SPIFFE CSI Driver](https://github.com/spiffe/spiffe-csi). We certainly want to continue exploring ways to reduce the permissions needed to execute SPIRE. I'd invite further conversations about this topic to happen in new issues.

**Comment by tebo-ernstberger** [comment]
Hi, 
I was following [this tutorial](https://spiffe.io/docs/latest/try/getting-started-k8s/) on a cluster where a psp with MustRunAsNonRoot was set. Since I'm running a POC I just used the following workaround in `server-statefulset.yaml`:
```yaml
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
```
Posting it here in case it helps.
Cheers!
