### ISSUE TITLE
False negative error message is printed when turning off attest limit

### ISSUE THREAD

**Issue by yangmarcyang** [spiffe/spire#1898]
PR #1870 replaced attest limit configurable with on/off switch. But when turning it off (`ratelimit` block with `attestation = false`), an error message would be printed saying something like "`Rate limiter used unexpectedly; this is a bug caller-addr="127.0.0.1:59633" method=AttestAgent service=agent.v1.Agent subsystem_name=api`". If turning off is a valid operation, then this error message is kind of misleading.

**Comment by azdagron** [comment]
Thanks for opening this @yangmarcyang. Until #1870 was merged, individual RPCs were either rate limited or not. RPC implementations that were rate limited were expected to invoke a function to apply the rate limiting after they had parsed the request and determined the "ordinality" of the request (e.g. signing 10 certificates has an ordinality of 10). The middleware layer knows which RPCs are rate limited and has some sanity checks to make sure that RPCs that _SHOULD_ be rate limiting are in fact invoking the rate limiter. It also has sanity checks that RPCs that _SHOULDN'T_ be invoking the rate limiter are in fact not.

The AttestAgent RPC is unequivocally invoking the rate limiter because it has no insight into the fact that rate limiting has been disabled at the middleware layer. This leads to the middleware logging that the rate limiter was invoked when it didn't expect it to. The (lack of) rate limit is being properly applied, but as you've noted, it's filling the logs with this misleading, and false, message.

Fixing this will probably require giving up the check that a RPC does not invoke the limiter when it isn't expected to, unless we want to educate individual RPCs about whether or not they should be rate limiting, which actually might be ok depending on how we go about it. I'll give this some thought.

**Comment by azdagron** [comment]
Talking with @evan2645 offline, he also suggested while we're at it, adding a rate limiting to these kind of log messages, so they don't flood the log, which I think is a fantastic suggestion.

**Comment by azdagron** [comment]
I'll file a separate issue to rate limit the log messages.

**Comment by azdagron** [comment]
Filed #1900 to track the log message rate limiting.
