### ISSUE TITLE
Feature Request: 'k8s:host-ip' selector

### ISSUE THREAD

**Issue by hiyosi** [spiffe/spire#1935]
* **Version**: 
* **Platform**: 
* **Subsystem**: Workload Attestor 'k8s' plugin

If the workload deal with the Admin SVID, we want to make it difficult to get the Admin SVID from another Node, even if the Agent SVID or Node Attestation Data is stolen.

One way to realize this is to restrict the nodes which the workload or the agent can launch.

#1273
I think what I'm thinking about is similar to this issue.
However it has not yet been discussed.

If the workload runs on K8s, currently the Workload Attestor 'k8s' plugin provides the k8s:node-name selector that references the .spec.nodeName of Pod Object as a way to restrict the Node.
But it seems to be a less recommended way of restricting nodes.
(See: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename)
More common way, Taint/Toleration and Affinity/AntiAffinity might be used.
Also, K8s Node name is relatively easy to spoof, so if an Agent's SVID/Attestation Data is stolen, the Node name restriction can be easily breached.

So, as another way of restricting the nodes, I would like the k8s plugin to provide the `k8s:host-ip` selector.
The workload attestor 'k8s' plugin generates `k8s:host-ip` from Pod's `.status.hostIP` field.
In a limited environment where IP spoofing is difficult and RegistrationEntry can be managed at the IP level, this can be useful.
Ideally, it would be nice to be able to specify a range with CIDR or something like that, but it would be difficult with the current implementation of Workload Attestor.

**Comment by hiyosi** [comment]
If this request is approved, I'll send a PR.

**Comment by evan2645** [comment]
Hey @hiyosi, thank you for opening this and sorry for the delay in my response.

This issue has drawn my attention to the `k8s:node-name` selector you referenced... It's a pretty weak assertion coming from the agent - instead, we probably want to assert this through node attestation, especially if the purpose is to limit the exposure of a workload entry. Which brings me to `k8s:host-ip`

From what I can tell in this issue, the concern is primarily around mitigating the danger of having an admin SVID since these SVIDs are pretty powerful. To me, it seems like a big part of that consideration is limiting the agents that can request and issue an admin SVID, and it also looks like that is what we're trying to accomplish here... however, we can only control the scope of the agent authorization through the use of parent ID, and thus, node selectors.

I guess what I'm getting at here is that by specifying `k8s:host-ip` workload selector, we can more tightly control the conditions under which an agent will give out an admin SVID, however agents on nodes other than the node with the declared IP address would still be able to ask for the admin SVID. To ensure that only the agent with the named node IP can request an admin SVID, the property needs to be part of node attestation and not workload attestation.

I think we'd be happy to accept a feature that emits a `k8s:host-ip` selector as a node selector - ideally, discovered from the k8s api server. Further, I have [opened an issue](https://github.com/spiffe/spire/issues/1955) to deprecate the `k8s:node-name` selector in favor of using existing node selectors emitted from the k8s_psat node attestor for the same reason.

Ultimately, I think this problem boils down to two aspects: the admin SVID is too powerful, and because of that, the node and workload attestation mechanisms must be very strong... perhaps the current security posture of the node attestor in use does not meet your requirements. In the long run, we are exploring options for more granular permissions on the administrative APIs that SPIRE Server exposes... so hopefully this might help to reduce some of the risk associated with admin SVIDs, and in turn alleviate the pressure on the security posture of the attestation mechanisms.

In the short term, one option could be to switch to a stronger node attestation mechanism. Or if you are using k8s_psat attestor, to use node name or similar as a node selector (rather than using the k8s workload selectors). Another option could be to colocate you admin workloads with SPIRE Server (e.g. run them in the same pod).

I'm not sure if any of these suggestions will work for you though... I'm also not sure how helpful this is to you :-D. What are your thoughts on all this?

**Comment by hiyosi** [comment]
@evan2645 Thank for comment.

> I think this problem boils down to two aspects: the admin SVID is too powerful, and because of that, the node and workload attestation mechanisms must be very strong.

Yes, that's right.
For example, we want to implement dynamic registration of a RegistrationEntry, but the current Admin SVID has the authority to issuean arbitary  SVIDs , in addition to the RegistrationEntry operation. This makes it difficult to handle SVIDs.
The ability to issue an arbitrary SVID represents the ability for an attacker to spoof anyone(also it can renew the Admin SVID), so stronger defenses are required.

Minimizing privileges may eliminate the need for such strict node authentication.

> In the long run, we are exploring options for more granular permissions on the administrative APIs that SPIRE Server exposes... so hopefully this might help to reduce some of the risk associated with admin SVIDs, and in turn alleviate the pressure on the security posture of the attestation mechanisms.

so, I am very interested in this consideration.
This may eliminate the need for the k8s:host-ip selector in a protective sense, but it may be used in other ways.

From here, focus about k8s:host-ip.

> I guess what I'm getting at here is that by specifying k8s:host-ip workload selector, we can more tightly control the conditions under which an agent will give out an admin SVID, however agents on nodes other than the node with the declared IP address would still be able to ask for the admin SVID. To ensure that only the agent with the named node IP can request an admin SVID, the property needs to be part of node attestation and not workload attestation.

Yes, I agree that risk is still there for sure.
I'm thinking of using a different Node Attestor plugin for Nodes that handle the Admin SVID to mitigate the risk.

> I think we'd be happy to accept a feature that emits a k8s:host-ip selector as a node selector - ideally, discovered from the k8s api server. Further, I have opened an issue to deprecate the k8s:node-name selector in favor of using existing node selectors emitted from the k8s_psat node attestor for the same reason.

Thanks you for accepting this feature request.
I want to proceed to implement the `k8s:host-ip` Selector.

>  Another option could be to colocate you admin workloads with SPIRE Server (e.g. run them in the same pod).

If the admin workload and the SPIRE Server can be operated under the same demarcation, then this idea sounds like a good one. I'd like to consider this as well.

**Comment by hiyosi** [comment]
Sorry, I was wrong about the comment.
I have updated about some comments.

**Comment by hiyosi** [comment]
> I guess what I'm getting at here is that by specifying k8s:host-ip workload selector, we can more tightly control the conditions under which an agent will give out an admin SVID, however agents on nodes other than the node with the declared IP address would still be able to ask for the admin SVID. To ensure that only the agent with the named node IP can request an admin SVID, the property needs to be part of node attestation and not workload attestation.

Yes, I agree that risk is still there for sure.
I'm thinking of using a different Node Attestor plugin for Nodes that handle the Admin SVID to mitigate the risk.
Because, in my environment, the SPIRE Server can't access the K8s API server. The SPIRE Server is placed out side of k8s cluster and the API is not exposed.

**Comment by hiyosi** [comment]
My team's disscussed this consideration,  It's not going to be easy to apply to our environment,.

> I think we'd be happy to accept a feature that emits a k8s:host-ip selector as a node selector 

Therefore what should we do about this?
Should we not implement it until we have specific users who need it?

Anyway, If you are okay, I'll close this issue.
Thank you @evan2645 , I've been able to consider security more.

**Comment by evan2645** [comment]
> so, I am very interested in this consideration.

Awesome :-D

You can follow some of the progress in https://github.com/spiffe/spire/issues/716 and https://github.com/spiffe/spire/issues/1975

It is still early, but I expect development to begin relatively soon.

> We've considered this again.
As a result, we'll be able to use Node Attestor k8s psat in our own environment.
So I'm thinking of creating a PR to add a Host IP Selector to the k8s_psat plugin.

Great! I saw the PR come through, I will review it soon. Thank you very much for this @hiyosi. If we were able to address your concern, then we can close this issue once your PR is merged. Thanks again!

**Comment by evan2645** [comment]
Closing this as #1979 has been merged. Please let me know if we need to re-open it @hiyosi
