### ISSUE TITLE
Production Hardened Docker Images

### ISSUE THREAD

**Issue by jkevlin** [spiffe/spire#1972]
* **Version**: 0.11.2
* **Subsystem**: all

A production security product, should have as small of a threat surface as possible.  The gold standard for a secure docker image is a compiled executable running in a scratch image (ideally as non-root).  I believe that the default docker image should be a FROM scratch image.  If an alpine images is required for dev work, then an alternative should be available, but the default images should be as hardened as possible.

**Comment by jkevlin** [comment]
Here is a Dockerfile that seemed to work on the agent.

`FROM golang:1.15.5-alpine as builder
RUN apk add build-base git mercurial
RUN apk add --no-cache ca-certificates

ADD go.mod /spire/go.mod
ADD proto/spire/go.mod /spire/proto/spire/go.mod
RUN cd /spire && go mod download
ADD . /spire
WORKDIR /spire
RUN make build
RUN PATH=/spire/.build/linux-x86_64/go/1.15.5/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin CGO_ENABLED=0  go build -ldflags "-s -w"  -o bin/spire-agent-scratch ./cmd/spire-agent

FROM scratch  AS spire-agent-scratch
# Import from builder.
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /spire/bin/spire-agent-scratch /opt/spire/bin/spire-agent
WORKDIR /opt/spire

EXPOSE 8080 8443
ENTRYPOINT ["/opt/spire/bin/spire-agent", "run"]
CMD []
`

**Comment by rturner3** [comment]
Hi @jkevlin, thanks for looking into this!

I agree that having bare-bones SPIRE images is worthwhile from a security perspective. Since we already release images based on Alpine today, perhaps these scratch images should be delivered as a second image option, since there may be users that are implicitly dependent on software installed in the Alpine images. It's also helpful for local testing and debugging to keep the existing Alpine Dockerfile definitions.

**Comment by jkevlin** [comment]
@rturner3 the first thing I wanted to prove was that it was possible to run the agent as a scratch image. Now that I have gone through the exercise and seen what the build pipeline looks like and thought about the plugin system,  I have come to the conclusion that having a detailed discussion and examples of how you might go about hardening for production, would be better than modifying the build system.  Everyone is going to want to have different plug-ins and so will want a custom build. So I think a Prepare for Production section of the documents might be a better approach.

**Comment by rturner3** [comment]
@jkevlin Most users will probably generate their own images, but I do think it would be useful to provide base SPIRE images that are the stripped down versions based on scratch, and not Alpine, with only the SPIRE release binaries and necessary image host configuration so that users don't have to rebuild SPIRE themselves in their build processes. Users would be free to extend that image in any way they'd like, e.g. installing a config file, plugin binaries, upstream certificate files, etc.

It looks like #1987 is a step towards achieving that, or did I misunderstand the intent of the PR?
