### ISSUE TITLE
The readiness endpoint for health checking is not implemented

### ISSUE THREAD

**Issue by ryysud** [spiffe/spire#1980]
* **Version**: v0.11.2
* **Platform**: All
* **Subsystem**: server and agent

In the latest version, the readiness endpoint for health checking over HTTP is not implemented and has no functional difference from the liveness endpoint.

- https://github.com/spiffe/spire/blob/v0.11.2/pkg/server/server.go#L382-L385
- https://github.com/spiffe/spire/blob/v0.11.2/pkg/agent/agent.go#L231-L234

It would be great to implement the same logic as the `spire-server|spire-agent healthcheck` command to the endpoint.

- https://github.com/spiffe/spire/blob/v0.11.2/cmd/spire-server/cli/healthcheck/healthcheck.go#L70-L106
- https://github.com/spiffe/spire/blob/v0.11.2/cmd/spire-agent/cli/healthcheck/healthcheck.go#L69-L110

**Comment by ryysud** [comment]
I implemented the readiness endpoint, the diff is https://github.com/spiffe/spire/compare/master...ryysud:impl-readiness-endpoint.

**Comment by ryysud** [comment]
@rturner3 Should I create a PR?

**Comment by rturner3** [comment]
Hey @ryysud, thanks for bringing this up. Health reporting is definitely something that could use some improvements.

I looked at your commit, and I do see that it brings parity between the `healthcheck` CLI commands and the HTTP `/ready` endpoints, which is a good step in the right direction. For SPIRE Agent, this is probably a good enough check for now.

Assessing the health of SPIRE Server is a little more complex. There's been some discussion about this subject in the past (captured in #730). SPIRE primarily integrates with external systems through its plugin architecture. It would be useful to have some way to get the health of any given configured plugin and report the health of each Server "subsystem" via some health API implemented by each plugin. Introducing a new "health" plugin API would be a breaking change to the interface though, so that has downstream impact for external plugins.

All that being said, what you've implemented seems like a strict improvement over what we have today, so I think it makes sense to send a PR for it. In that PR, would you mind trying to cover these HTTP health endpoints in one of the existing integration tests or as a separate integration test? Ideally we should test them in Kubernetes since I think that was the original motivation for adding the separate HTTP APIs.

**Comment by ryysud** [comment]
Thank you for your reply, @rturner3.

> Assessing the health of SPIRE Server is a little more complex. There's been some discussion about this subject in the past (captured in #730). 

I checked the issue. Just as you commented, we need to implement a mechanism like the Health API in SPIRE Server to check that the server is completely ready.

> All that being said, what you've implemented seems like a strict improvement over what we have today, so I think it makes sense to send a PR for it.

OK, I will add the test and create a PR. Thanks.
