### ISSUE TITLE
SPIRE SDS implementation doesn't supply CertificateValidation info to Envoy

### ISSUE THREAD

**Issue by bleggett** [spiffe/spire#1988]
* **Version**: 1957ad64210704c0792c4b8fc3f7d431a420ae4c 
* **Platform**: Linux
* **Subsystem**: agent, SDS

Original slack discussion: https://spiffe.slack.com/archives/C7XDP01HB/p1606942307145100

Basically, I want to use SPIRE as the SDS server for Istio's deployment of Envoy, largely because Istio's SDS is hardcoded to only authorize k8s workloads via the service account they're running under and I want more expressive and granular workload attestation than that model provides (good context: https://developer.ibm.com/components/istio/articles/istio-identity-spiffe-spire/)

Now just replacing Istio's SDS with SPIRE's SDS as a drop-in replacement isn't too hard (largely just a grpc socket change) and works well on SPIRE's `master` since the SDSv3 API changes have been rolled in, however there's one catch:

Since Istio defaults to service-account scoped SPIFFE IDs, it (understandably) emits this default Envoy TLS context config for every cluster:

```
                "transportSocket": {
                    "name": "envoy.transport_sockets.tls",
                    "typedConfig": {
                        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
                        "commonTlsContext": {
                            "tlsCertificateSdsSecretConfigs": [
                                {
                                    "name": "default",
                                    "sdsConfig": {
                                        "apiConfigSource": {
                                            "apiType": "GRPC",
                                            "transportApiVersion": "V3",
                                            "grpcServices": [
                                                {
                                                    "envoyGrpc": {
                                                        "clusterName": "sds-grpc"
                                                    }
                                                }
                                            ]
                                        },
                                        "initialFetchTimeout": "0s",
                                        "resourceApiVersion": "V3"
                                    }
                                }
                            ],
                            "combinedValidationContext": {
                                "defaultValidationContext": {
                                    "matchSubjectAltNames": [
                                        {
                                            "exact": "spiffe://example.org/ns/default/sa/proxy"
                                        }
                                    ]
                                },
                                "validationContextSdsSecretConfig": {
                                    "name": "ROOTCA",
                                    "sdsConfig": {
                                        "apiConfigSource": {
                                            "apiType": "GRPC",
                                            "transportApiVersion": "V3",
                                            "grpcServices": [
                                                {
                                                    "envoyGrpc": {
                                                        "clusterName": "sds-grpc"
                                                    }
                                                }
                                            ]
                                        },
                                        "initialFetchTimeout": "0s",
                                        "resourceApiVersion": "V3"
                                    }
                                }
                            },
                            "alpnProtocols": [
                                "istio-peer-exchange",
                                "istio"
                            ]
                        },
                        "sni": "outbound_.8001_._.proxy-api.default.svc.example.org"
                    }
                }
            },
```

The important bit is the `matchSubjectAltNames` block in the ValidationContext 

- Istio constructs valid SANs for all cluster configs dynamically in SPIFFE format, **based on the cluster's target service account** - this means that any cert issued by SPIRE SDS that doesn't generate SPIFFE IDs in this exact service-account-scoped format will be rejected by the client Envoy proxy 
- Which in practice means you can't use SPIRE's SDS server to attest workloads for mTLS at a granularity higher than the service account level with Istio 
- Which means it's not much practical use as an SDS server unless you're handrolling your Envoy deployment and configuration. 

[The Envoy SDS spec accounts for this though - the `combinedValidationContext` above indicates that whatever ValidationContext payload the SDS server returns will be merged with the 'defaultValidationContext' and will override it.
](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/tls.proto#envoy-api-field-auth-commontlscontext-combined-validation-context)

This would solve everything - regardless of what the "default" SNI matching config was, SPIRE SDS could emit it's own SNI match info which would take precedence over any default configs, which makes sense - SPIRE SDS issues certs and tracks what certs are mapped to which workloads, and ought to know which SPIFFE IDs map to which certs for client cert validation purposes.

Unfortunately, SPIRE SDS doesn't emit CertificateValidationContext info so this doesn't work. Should it?

To avoid making decisions about what certs a client should accept, should SPIRE SDS simply emit a ValidationContext that matches against a preconfigured SPIFFE ID prefix based on trust zone? 

Something like:
```
                                "validationContext": {
                                    "matchSubjectAltNames": [
                                        {
                                            "prefix": "spiffe://example.org/ns/default"
                                        }
                                    ]
                                }
```

I know we want to avoid doing authZ - but if you're using SPIRE as your SDS server, SPIRE is the _only_ oracle for up-to-date SAN->cert mappings, so it feels weird to not support the part of the Envoy SDS spec that recognizes and accounts for that.

**Comment by azdagron** [comment]
Thanks for opening this @bleggett! When SDS support was first introduced into SPIRE agent, at least @evan2645 and myself mused on if/how we should support adding other fields to the ValidationContext. Unfortunately, it wasn't clear (and still isn't?) what this kind of support would look like.

> SPIRE SDS issues certs and tracks what certs are mapped to which workloads, and ought to know which SPIFFE IDs map to which certs for client cert validation purposes.

Yes, SPIRE registration entries allow operators to describe what their workloads look like, so SPIRE can hand out identity to those workloads (by embedding the SPIFFE ID URI SAN). From an Envoy SDS perspective, this allows us to reasonably give back an X509-SVID to Envoy with an embedded workload identity. However, SPIRE's registration model does not allow an operator to define which workloads are authorized to talk to which other workloads (i.e. authorization).

Ultimately, for SPIRE agent to populate the `match_subject_alt_names` for the ValidationContext returned for a given workload, it needs to be programmed with the policy information for that workload. SPIRE agent configuration comes from two sources: 1) a static HCL configuration file, and 2) registration information returned from the SPIRE server. The 1st option seems like a non-starter, as encoding workload specific information into the agent configuration file is not very scalable, would require tight integration with workload scheduling, and would complicate agent deployment. The 2nd option, while simpler from an operational perspective, starts to shift fundamental portions of the design away from the authn mandate. Adding a way of expressing authorization decisions in the registration entries would open a big can of worms, particularly since, outside of SDS, there is no blessed SPIFFE way for authorization policy to be conveyed to workloads.

There is another option, which is for SPIRE agent to gain some sort of plugin that could be consulted for authorization policy. The SDS implementation could query that plugin in order to retrieve the SANs a workload was authorized to peer with. However, at least in my mind, this has some of the same risk as extending the registration entries with (even basic) authorization policy.

I'm curious if there is an avenue to pursue in getting a change into upstream Istio that allows for some customization of the validation context without having to replace the Envoy configuration wholesale...

**Comment by bleggett** [comment]
```
I'm curious if there is an avenue to pursue in getting a change into upstream Istio that allows for some customization of the validation context without having to replace the Envoy configuration wholesale
```

Yeah - the crux of the matter is that the SDS spec itself expects the SDS server implementation to supply the ValidationContext config.

I'm pursuing getting Istio to remove their hardcoded SDS ValidationContext, and instead emit it from their built-in SDS server as per the spec - while that would make it easier to alter the config it doesn't really solve the problem of that config needing to come from the SDS server.

**Comment by georgi-lozev** [comment]
Hello SPIRE friends.

Is there any additional feedback to the issue discussed here?

The proposal @bleggett makes looks quite reasonable to me and also aligned with my use cases.

**Comment by azdagron** [comment]
I think this proposal is superseded by the support for the SPIFFECertValidator extension that SPIRE now populates in the ValidationContext. The SPIFFECertValidator already scopes authentication of an SVID from a particular trust domain to use only the bundles for that trust domain, eliminating the possibility of an SVID from another trust domain from being validated against a different trust domain bundle.

See [SPIFFE Certificate Validator](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls_spiffe_validator_config.proto).

Does that work for you?

**Comment by bleggett** [comment]
Been a while since I've looked at this, but yes I think it does.

Good with closing this, thank you!

**Comment by azdagron** [comment]
Awesome! Thanks!
