### ISSUE TITLE
Warning log for CA_TTL is not clear

### ISSUE THREAD

**Issue by hiyosi** [spiffe/spire#2000]
* **Version**: 0.11.2
* **Platform**: *
* **Subsystem**: server run command

Depending on the values of `ca_ttl` and `default_svid_ttl`,  warning log will be output even if `ca_ttl` is more than 6 * `default_svid_ttl`.

- ca_ttl=1008h , svid_ttl=168h(7 x 24h): the log will not be output.
- ca_ttl=1152h , svid_ttl=192h(8 x 24h): the log will be output.

```
The configured SVID TTL cannot be guaranteed in all cases - SVIDs with shorter TTLs may be issued if the signing key is expiring soon. Set a CA TTL of at least 6x or reduce SVID TTL below 6x to avoid issuing SVIDs with a smaller TTL than specified
```

My understanding is that if default_svid_ttl is grater than 7 days, it is possible to happen that SVIDs with shorter than svid_ttl will be issued even if ca_ttl is 6 times grater than default_svid_ttl.

**Comment by evan2645** [comment]
Hi @hiyosi - thank you for opening this, and happy new year!

There are many things I dislike about this log message... First, as soon as we change the rotation timing algorithm, this message will be instantly outdated. Second, it requires the user to do math in order to figure out the magic TTL values that will stop the warning :-D and finally, I think the message itself is a little confusing.

Frankly, I think the entire TTL configuration experience needs an overhaul. If you have ideas/suggestions on how to reduce the cognitive overhead of managing TTLs, I'd love to hear more. The less timing-related stuff that our users have to deal with, the better.

In the meantime, maybe a quick fix to this message could be to 1) use the actual rotation timing algorithm to understand what the maximum default_svid_ttl is/should be, 2) provide the user with that number in the message itself, and 3) shorten and clarify the message. For example:
`The default_svid_ttl is too high for the configured ca_ttl value. SVIDs with shorter lifetimes may be issued. Please set default_svid_ttl to XXX hours or less, or ca_ttl to YYY hours or more, to guarantee the default_svid_ttl lifetime.`

What do you think?

**Comment by hiyosi** [comment]
@evan2645  Happ new year! Thanks for reply.

>  First, as soon as we change the rotation timing algorithm, this message will be instantly outdated. Second, it requires the user to do math in order to figure out the magic TTL values that will stop the warning :-D and finally, I think the message itself is a little confusing.

I agree 👍 

> In the meantime, maybe a quick fix to this message could be to 1) use the actual rotation timing algorithm to understand what the maximum default_svid_ttl is/should be, 2) provide the user with that number in the message itself, and 3) shorten and clarify the message. For example:

It looks good!
There is one more thing I confused,  the message `SVIDs with shorter TTLs may be issued if the signing key is expiring soon` is output at the same message as the TTL values warning.  I think it's better to separate logs or remove it.

**Comment by evan2645** [comment]
> There is one more thing I confused, the message SVIDs with shorter TTLs may be issued if the signing key is expiring soon is output at the same message as the TTL values warning. I think it's better to separate logs or remove it.

I'm not quite sure what you mean here, but we should aim for just one log line about the configured TTL

**Comment by hiyosi** [comment]
The log  has two messages.

a. The configured SVID TTL cannot be guaranteed in all cases - SVIDs with shorter TTLs may be issued if the signing key is expiring soon. 
b. Set a CA TTL of at least 6x or reduce SVID TTL below 6x to avoid issuing SVIDs with a smaller TTL than specified

If I configured the TTLs as ca_ttl=1152h(192h x 6) , svid_ttl=192h(8 x 24h), above log would be output.
In that case, the log (a) is correct, but the log (b) is not.
The message that ca_ttl should be set to 6x even though I set ca_ttl to 6x confuses me.

Supplement for (a):
If the SVID TTL is configured as 8 days and the remaining validity of the CA Key is 7 days, a new SVID may be issued with an expiration date of 7 days.
c.f. https://github.com/spiffe/spire/blob/af8427924e705da88ec42dfde7cd94b09fa31915/pkg/server/ca/ca.go#L186

> we should aim for just one log line about the configured TTL

Anyway, I agree with the above.

**Comment by evan2645** [comment]
Just wanted to check in @hiyosi and make sure that I answered all of your questions?

**Comment by hiyosi** [comment]
@evan2645  Yes, thank you.

**Comment by evan2645** [comment]
> I'm sorry that I couldn't explain the issue clearly.

Not to worry :) I don't think it's your fault.
