### ISSUE TITLE
docker WorkloadAttestor Agent plugin documentation incomplete

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#2023]
There is a plugin configuration parameter called `container_id_cgroup_matchers` that is not documented in https://github.com/spiffe/spire/blob/master/doc/plugin_agent_workloadattestor_docker.md

**Comment by APTy** [comment]
Originally this was added as an "undocumented" (experimental) config, so that we could change it without "breaking" the API. That said, it's been around for a while and could probably use some documentation, since it probably won't be changing any time soon. The best existing docs about this value are probably here: https://godoc.org/github.com/spiffe/spire/pkg/agent/plugin/workloadattestor/docker/cgroup#NewContainerIDFinder

I can take a stab at documenting this, unless @ZymoticB has time to drop some knowledge 😉
