### ISSUE TITLE
unix attestation logic should not drop errors on failed group look up

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#2040]
ref. https://github.com/spiffe/spire/blob/a90c73d26fd37de47dc20c461f38eed92df5a3c1/pkg/agent/plugin/workloadattestor/unix/unix.go#L265

```
func (p *Plugin) getGroupName(gid string) (string, bool) {
	g, err := p.hooks.lookupGroupByID(gid)
	if err != nil {
		return "", false
	}
	return g.Name, true
}
```
If there is an error looking up groups, we simply drop the error.

The caller of this function also does not even log the "false" return as a problem:
```
	if group, ok := p.getGroupName(gid); ok {
		selectors = append(selectors, makeSelector("group", group))
	}
```

Improvements:
- We should log the actual error with details.
- Should unix attestation fail if group lookup fails?

**Comment by amoore877** [comment]
There is a similar issue with user lookup, which follows exactly the same pattern. Whatever we do for groups we should also do for user.

**Comment by azdagron** [comment]
I think logging failure to obtain auxilliary information about the process (i.e. group name or user name) is a good thing. I'd welcome that PR.

In terms of failing attestation, this is related to the discussion underway in (@2036). SPIRE tries hard to give-you-what-we-can. I don't see a good reason to not return any selectors for the process if we couldn't determine the group or user name, particularly since that can easily happen in containerized workloads when they are run under a specific uid/gid that does not have a corresponding entry in whatever `/etc/passwd` or `/etc/group` file that the agent is consulting. So my vote would be to log the error and continue attesting.

**Comment by azdagron** [comment]
>
