### ISSUE TITLE
Health checks errors may be shown at startup

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#2063]
There could be a race at startup time where the health checks can be executed before the server is serving. In that case, throwing an error is inappropriate and could be confusing.
This can happen both in SPIRE Server and SPIRE Agent.

* **Version**: 277aabfa24c2e222d280f0a8a17cc0cb234acee4

**Comment by hiyosi** [comment]
Hi! 
I'm not sure I understand the problem on this issue.
If I understand correctly,  the endpoint respond as to whether the server is ready or not.
So I think it is natural that the endpoint responds error if the server is not serving yet.

It should be run the health checking after server is serving?

**Comment by ryysud** [comment]
After closing the above PR, I considered another fix to start the health check subsystem after the server and agent are running. But I could not fix this issue because the subsystems are concurrently executed by "util.RunTasks":
https://github.com/spiffe/spire/blob/277aabfa24c2e222d280f0a8a17cc0cb234acee4/pkg/server/server.go#L167-L175

Therefore, it is difficult to fix this issue without implementing a mechanism to execute the subsystems in order in the server and agent...

**Comment by amartinezfayo** [comment]
> Hi!
> I'm not sure I understand the problem on this issue.
> If I understand correctly, the endpoint respond as to whether the server is ready or not.
> So I think it is natural that the endpoint responds error if the server is not serving yet.
> 
> It should be run the health checking after server is serving?

@hiyosi Right, the endpoint responds appropriately, but we shouldn't start checking if we know that the server hasn't started yet.

**Comment by amartinezfayo** [comment]
@ryysud Thank you for your time spent on a possible fix! I've assigned myself #2015.

**Comment by hiyosi** [comment]
@amartinezfayo 

Thanks for reply! Now I understand:)
