### ISSUE TITLE
Serverless support: add a field in the registered_entries table to identify exportable identities

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#2081]
In preparation to support SVIDStore plugins, we need to add a bool field in the registration entry to identify if the issued identity is exportable to a store and the selectors must be consumed by an SVIDStore plugin.

A possible name for the field can be `exportable_identity`.

**Comment by azdagron** [comment]
Thanks for opening this @amartinezfayo and putting up the PR @MarcosDY .

I've been thinking on the name. Here are some alternatives:
```
export_svid
publish_svid
```
I thought a verb might be nice here, since there is an action definitely being taken, i.e. the agent will remove the entry from consideration from workload attestation and (attempt to) store it via a plugin.

I also thought `svid` might be better than `identity` since the former is a more concrete representation of what is being exported.

Thoughts anybody?

**Comment by MarcosDY** [comment]
what do you think about `store_svid`? since our plugin type is called SVID Store?

**Comment by azdagron** [comment]
I'd be fine with either of those. Curious if anybody else has strong opinions on this.

**Comment by amartinezfayo** [comment]
I'm also fine with either `export_svid` or `store_svid`, although I'm a little inclined to `store_svid`, since _export_ may have some inherent connotation of _export to a different format than the native format_ which may cause some confusion.

**Comment by evan2645** [comment]
No strong opinions from me... I can't say that I love any of the options, and as unattractive as it sounds we do always have the option of column name mismatch if/when we come up with a better name for it in the coming weeks. If I had to choose one, I guess I'd choose `store_svid` due to the consideration that @amartinezfayo has called out

**Comment by APTy** [comment]
I also like `store_svid` because it has symmetry with the `svidstore` plugin name 😄
