### ISSUE TITLE
Remove the experimental allow_agentless_node_attestors server configurable

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#2094]
As of 1.0, the allow_agentless_node_attestors server configurable is marked as deprecated. In preparation for 1.1 release, we can remove the support for this configurable.

**Comment by evan2645** [comment]
IMO we can probably remove this any time we want since it's experimental. @azdagron informed me that the new server APIs don't have this functionality, in which case the flag probably doesn't even do what it was meant to ever since we swung the agents over. I'll be curious to hear other thoughts though, if we should be having better compat support around experimental features.

**Comment by azdagron** [comment]
We've traditionally deprecated experimental flags (i.e. federation stuff) but those were for features for sure in use by folks in non-experimental environments (probably a signal we should have probably graduated them sooner). I think there is no reason to break the world by just ripping out experimental flags, but then again, what would be the point of having "experimental" other than a self documenting way of showing a feature may not be ready for prime time.

In any case, this flag was baked in more or less for a POC integration that never took flight. I would be utterly and completely surprised if it was set anywhere by anybody. I'm OK with removing it outright.
