### ISSUE TITLE
SPIRE allows trust domains with over 255 characters

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#2103]
* **Version**: 1549503d212dad47811218a1eca23ca204d5f208
* **Platform**: All
* **Subsystem**: Server, Agent

[SPIFFE](https://github.com/spiffe/spiffe/blob/master/standards/SPIFFE-ID.md#23-maximum-spiffe-id-length) requires that trust domains (host component of SPIFFE ID URI) be no longer than 255 characters in order to comply with [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.2.2). SPIRE [Server](https://github.com/spiffe/spire/blob/master/doc/spire_server.md#server-configuration-file) and [Agent](https://github.com/spiffe/spire/blob/master/doc/spire_agent.md#agent-configuration-file) currently accept trust domains through the `trust_domain` configuration field that are longer than 255 characters.

**Comment by ryysud** [comment]
@rturner3 we can close this issue?

**Comment by rturner3** [comment]
The current behavior is that we log a warning on server startup when a configured trust domain is too long, but I think we can go one step further by preventing new deployments from being able to use a trust domain longer than 255 characters. We should be able to detect on startup of the server whether or not we are performing the initial database migration. Before the initial migration is performed, we can validate that the configured trust domain is longer than 255 characters, and if so, fail server startup and not perform the database migration.

I would like to see that enforcement for new deployments introduced before considering this issue closed.

**Comment by amoore877** [comment]
> We should be able to detect on startup of the server whether or not we are performing the initial database migration. Before the initial migration is performed, we can validate that the configured trust domain is longer than 255 characters, and if so, fail server startup and not perform the database migration.

By "initial database migration", do you mean for the case where essentially a new control plane is coming up, so the DB is being initialized for the first time?
I think this would hinder existing deployments greatly in being able to both:
- stay up-to-date with SPIRE code
- horizontally scale alongside their organizations capacity through adding new control planes to their operations
without first refactoring their operations to have a shorter trust domain, which may be a large endeavor.

In principle no one should have a trust domain that long, since it is against SPIFFE spec, and I would question the value of a domain of that length. But it remains that someone out there could be in this case regardless.

**Comment by rturner3** [comment]
Backward compatibility for existing deployments will need to be considered if SPIRE ever rejects trust domains greater than 255 characters. It is probably unlikely that deployments would use such long trust domain names, but I agree we would want to solicit some feedback from the community to try to assess this in advance.

If any users have trust domain names exceeding the maximum length in the specification, we may be able to provide an opt-in configuration as an escape hatch to continue accepting trust domain names exceeding 255 characters. I would prefer not to add that configuration initially unless we know of specific users that are still dependent on the existing behavior, but it's an option we can consider if needed to support existing deployments.
