### ISSUE TITLE
Develop a pattern for platform-specific integration testing

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#2168]
There is currently a lack of integration test coverage for some of the builtin `NodeAttestor` plugins in SPIRE. Existing `NodeAttestor` builtin plugin integration test coverage:

- `join_token` -> `node-attestation` integration test
- `x509pop` -> `node-attestation` integration test
- `k8s_psat` -> `k8s` integration test

`NodeAttestor` builtin plugins without integration test coverage:

- `aws_iid`
- `azure_msi`
- `gcp_iit`
- `k8s_sat`
- `sshpop`

Ideally all the `NodeAttestor` builtin plugins should have integration tests, even if they are not run as part of CI due to infrastructure or billing-related concerns (e.g. funding for a project AWS account). If users are leveraging these attestors, automated integration tests will at least enable them to verify behavioral correctness in their environment before attempting a production SPIRE deployment.

**Comment by evan2645** [comment]
This would be awesome. I wonder what it would look like though? I think the terraform project has some prior art here.

**Comment by rturner3** [comment]
Spun off https://github.com/spiffe/spire/issues/3953 to capture the `aws_iid` implementation since AWS integrations are more feasible to test today than other public clouds.

**Comment by rturner3** [comment]
This needs a plan that includes:

- Which node attestor plugins we want to support with integration tests
- When these integration tests should be run and in what environment

**Comment by rturner3** [comment]
We should also consider platform-specific KeyManager plugins in this scope as well.

**Comment by guilhermocc** [comment]
Hi Ryan, I would like to propose some standards for implementing this kind of integration test on SPIRE.

I believe the main focus of platform-specific integration tests is to provide the user the flexibility for running a set of assertions (that will vary according to the plugin being tested) in different types of infrastructure. The significant complexity of this kind of test is to wire up an existing infrastructure with the coded assertions of the implemented test; that being said, I would like to bring the following approach to discussion.

### Infrastructure setup

Every platform-specific integration test must have documented all the required infrastructure for running the test. For example, a node attestor test would need at least a compute instance running in the cloud platform; a key manager test would require at least a service account with correct permissions for managing keys.

Besides the documentation, every platform-specific test should provide a terraform template for creating the required infrastructure resources. Even if it is not used directly, it can serve as a guide to which resources are required for that scenario.

Every test will have e cost involved varying with the type of resources it needs to use; each terraform plan should try to minimize this cost by only defining resources that are essential for making the target assertions.

The user can have two options regarding the infrastructure setup:
1. Users can opt to run platform-specific tests on an existing infrastructure created before the test execution so that the user will be responsible for creating and purging those resources.
2. Users can delegate the resource creation to the test itself, in which the test would execute the `terraform plan` and apply for setting up the environment, and then execute the `terraform destroy` during the test teardown. Here the user would still be responsible for providing the required credentials, so the terraform can have the permissions for creating the infrastructure resources.

### Assertions setup

Platform-specific tests should provide two options for connecting to SPIRE agent and server so that assertions can be made based on its behavior:
1. Remote connections: every test assertion will execute locally against results obtained from a remote compute instance so that every inspection made in the spire server or agent would occur through an ssh connection.
2. In-place connections: in a case where the test script is being executed inside a compute instance already configured, or if the spire server and agent are not required to run in a cloud environment, every test assertion will execute locally against results obtained from the spire agent and server processes running locally.

### Tests structure
```
├── suites
│   ├── plugins
│   │   ├── server
│   │   │   ├── keymanager
│   │   │   ├── nodeattestor
│   │   │   │   └── awsiid
│   │   │   │       └── terraform
│   │   │   │           ├── main.tf
│   │   │   │       ├── conf
│   │   │   │       │   ├── agent
│   │   │   │       │   └── server
│   │   │   │       ├── 01-run-server-agent
│   │   │   │       ├── 02-assert-attestation
│   │   │   │       ├── README.md
│   │   │   │       ├── teardown
│   │   ├── agent
│   │   ├── common.sh
```
Here is an example of how a test for `awsiid` node attestor plugin would look like, in which all plugins it tests are defined inside `plugins` directory. Each plugin test define it's own terraform file and the set of assertions with shell script steps like we do today. The `common.sh` file rooted at the `plugins` directory would contain all common logic for plugin tests, like running terraform `plan` and `apply` if requested, creating keypairs for remote connections, starting spire agent and server (locally or remotely), executing commands on spire server and agent (locally or remotely) to retrieve its states, etc.

Another option is to group tests by platform:

```
├── suites-platform-specific
│   ├── aws
│   │   ├── terraform
│   │   ├── plugins
│   │   │   ├── server
│   │   │   │   ├── nodeattestor
│   │   │   │   │   └── awsiid
│   │   │   │   │       ├── conf
│   │   │   │   │       │   ├── agent
│   │   │   │   │       │   └── server
│   │   │   │   │       ├── 01-run-server-agent
│   │   │   │   │       ├── 02-assert-attestation
│   │   │   │   │       ├── README.md
│   │   │   │   │       ├── teardown
│   │   │   ├── agent

│   ├── gcp
│   ├── azure
│   ├── common.sh
```
In this case, all tests are grouped by the `cloud provider`, and the terraform templates would be rooted in the cloud provider dir, containing all resource definitions required by the tests.

Regardless of the structure of the tests, SPIRE should provide means for running the entire test suite of a specific cloud provider utilizing common resources already created by other tests in the suite, minimizing the number of resources needed for running it entirely.

### Which plugins should we test?

- Which node attestor plugins do we want to support with integration tests?
As long as we provide clear documentation about the infrastructure required and the estimated cost involved in running a test, I believe it is possible to have integration tests for all node attestor plugins. We could start prioritizing the ones most commonly used by the community (and therefore would have a greater impact in regression scenarios), but I'm unsure if we have this data.
- When these integration tests should be run and in what environment
We should maintain flexibility so we can set up and run these tests locally or in a CI pipeline. Thinking about the pipeline, it wouldn't make sense to run these tests in every opened PR workflow. Instead, we could configure it into a manual pipeline step that can be triggered every time we detect changes in parts of the code that can affect platform-specific built-in plugins.

**Comment by rturner3** [comment]
Hi @guilhermocc, thank you so much for the proposal and for your patience on the response.

This looks great to me overall. The only part that may need a little more thought is the directory organization of the integration tests that require usage of a paid service/cloud compute. I feel it would be nice to have a top-level directory such as `suites-external-platform` for all these tests under `test/integration` that is separate from the existing `test/integration/suites` directory to more easily manage when they are executed.

Other than that, I am generally more in favor of your suggestion to group the individual tests under that top-level directory by cloud provider/platform. That will simplify managing the Terraform since I imagine many tests using different services from the same cloud provider will have common resources, such as VMs and virtual networking. However, I'm not sure I see a need to further subdivide between `server` vs. `agent` under that level because usually integration tests will be covering end-to-end flows, e.g. the NodeAttestor plugin requires both the Server and Agent.

Taking what you proposed, here's the slight tweak I would suggest for the subdirectory structure so that it's more generally aligned with how the other integration test suites are organized:
```
├── suites-external-platform
│   ├── aws
│   │   ├── terraform
│   │   ├── suites
│   │   │   ├── awsiid-nodeattestor
│   │   │   │   ├── conf
│   │   │   │   │   ├── agent
│   │   │   │   │   └── server
│   │   │   │   ├── 01-run-server-agent
│   │   │   │   ├── 02-assert-attestation
│   │   │   │   ├── README.md
│   │   │   │   ├── teardown
│   ├── azure
│   ├── common.sh
│   ├── gcp
```
