### ISSUE TITLE
do not append self-signed upstream CA to SVID chains

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#2237]
Scenario:
There is some SPIRE Server cluster which uses a common upstream CA. This upstream CA is self-signed.

All workload SVIDs signed by this cluster will include a chain like:
`workload1 -> ServerB -> upstreamCA`

The purpose of a chain is to help the workload establish trust with other processes. These other processes fall into one of two categories:
- The process *does not* trust the self-signed upstream CA. There is no parent CA to the upstream CA that the process could be trusting that would change this situation. There was no point in having the upstream CA be in the chain.
- The process *does* trust the self-signed upstream CA. Since the process trusts the upstream CA, the SVID's chain could have just been `workload1 -> ServerB` and still the workload would have been verified.

Proposal:
Including an unnecessary certificate in the SVID chains increases network overhead at scale.
If SPIRE Server detects that its upstream CA is self-signed, it should not include that CA in SVID chains.

**Comment by azdagron** [comment]
The SVID chain should not include the upstream root. This has been the case for quite some time (at _least_ back to v0.9). Can you elaborate on the exact version or commit on which you are experiencing this behavior?

**Comment by evan2645** [comment]
> Can you elaborate on the exact version or commit on which you are experiencing this behavior?

And which UpstreamAuthority plugin you're using?

**Comment by amoore877** [comment]
We are using the `disk` upstream authority, on version v0.10.1 though we will be upgrading soon to v0.11 and beyond. Examining a SPIRE Agent SVID, it's chain is:
- itself
- the issuer SPIRE Server
- the self-signed root

**Comment by evan2645** [comment]
I built 0.10.1 locally and configured the UpstreamAuthority disk plugin, and did not observe the self-signed root being included in the chain being sent to workloads. A workload SVID fetched from the workload API included only the leaf and the SPIRE Server intermediate.

Looking at the [docs](https://github.com/spiffe/spire/blob/v0.10/doc/plugin_server_upstreamauthority_disk.md#server-plugin-upstreamauthority-disk), they have this to say about the `cert_file_path` configurable:
`
If SPIRE is using a self-signed CA, cert_file_path should specify the path to a a single PEM encoded certificate representing the upstream CA certificate.
`

Can you verify that there is not more than one certificate in the `cert_file_path` file?

**Comment by amoore877** [comment]
> A workload SVID fetched from the workload API included only the leaf and the SPIRE Server intermediate.

what about an agent SVID? maybe there's a disconnect there in implementation?

> Can you verify that there is not more than one certificate in the cert_file_path file?

confirmed

**Comment by evan2645** [comment]
> what about an agent SVID? maybe there's a disconnect there in implementation?

I checked the agent SVID that is cached on disk, and it contains exactly one certificate.

Could you please provide some more information? I think that workload and agent SVID take the same codepaths through the CA logic...

**Comment by amoore877** [comment]
where is the associated code that should be doing this special logic for self-signed? wondering if our fork is somehow missing that logic.

**Comment by evan2645** [comment]
I'm not totally sure I follow, we don't really have any special logic for self-signed certs ... all root certs are self-signed. On the other hand, we of course distinguish between roots and non-roots so we know what goes in the bundle and what goes in the chain.

UpstreamAuthority plugins return these two things explicitly... a set of roots, and a chain. That happens here: https://github.com/spiffe/spire-plugin-sdk/blob/main/proto/spire/plugin/server/upstreamauthority/v1/upstreamauthority.proto#L44-L53

And here is where we handle the UpstreamAuthority interaction, you can see that we receive the CA chain and roots separately, and that they are handled separately: https://github.com/spiffe/spire/blob/main/pkg/server/ca/upstream_client.go#L130

So the only conclusion I can reach is that your UpstreamAuthority plugin is misusing this interface and returning your root as part of your CA chain. The built-in disk plugin does not do this if it is configured correctly, though it can do this if configured incorrectly. Since you have confirmed already that there is only one certificate present in cert_file_path, I don't know what else could cause this. Agent and workload SVIDs use the same signing paths.
