### ISSUE TITLE
move support applications into their own repo

### ISSUE THREAD

**Issue by amoore877** [spiffe/spire#2249]
https://github.com/spiffe/spire/tree/main/support contains two modules today: `k8s-workloads-registrar` and `oidc-discover-provider`.

These are neither SPIRE Server nor SPIRE Agent, and built as their own binaries. Out of a desire for:
- separation of concerns
- minimizing transitive `go.mod` imports due to importing the repo

I think each of these components deserves their own repo. As much as is practical, I think this repo should only be concerned with core SPIRE Server and SPIRE Agent.

#2153 proposes similar for plugins

**Comment by evan2645** [comment]
Thanks for opening this @amoore877 

I agree, I think that the ideal situation is that these tools have dedicated repos. That said, I feel that the biggest reason that they're still in the SPIRE repo is that splitting them out comes with a non-trivial amount of increased overhead. For example, with the new plugin and api repos, every time we do a SPIRE release, we now need to cut tags on these other repos as well. If we don't, it can get very hard to tell which versions of the SDKs work with which versions of SPIRE.

It's a tad bit easier with those repos though because they don't generate artifacts. These tools do, and so they'll need their own build and release pipelines etc, and we'll have to poke at them every time we want to release SPIRE.

The alternative is to decouple the versioning. This would free SPIRE maintenance of the burden, however it would then introduce the compatibility matrix problem (and ensuing user confusion) problem.

Release engineering is not one of my strengths, but if there are good solutions for these problems, I'd love to talk about them. For now, cost (bigger `go.mod` with more frequent modification) significantly outweighs the benefit (separation of concern but with added release overhead and/or confusing compatibility guarantees)

**Comment by amoore877** [comment]
Keeping versioning the same between SPIRE and its support tools could give the wrong impression if a support tool's version keeps going up without any changes beyond changing SPIRE dependency version, especially if there have been no breaking changes to SPIRE API in those versions. This is also the case today. It's not necessarily totally wrong, but IMO it doesn't feel totally right either.

I would view this simply as the right thing to do as a standard. Will we keep expanding the `support` directory with more tools, or are all future new tools going into their own repo? If the former, we are only going to be bogging down the repo more and potentially causing consumer version dependency headaches for things they may not even use. If the latter, we should be looking to follow the pattern for existing tools.

I don't know of tools that exist for the compatibility matrix problem, but I would presume that they are out there it's just we as non-experts don't know them.
Perhaps this could be the start of a general community call to see if we have some release engineers willing to provide instruction, or at least general pointers or names of tools/methodologies? As you said for plugin and API repos we are already going to be facing this sort of trouble, so assuming this problem will at the very least not shrink we should make sure it is being done in the least painful ways possible.

**Comment by rturner3** [comment]
`k8s-workload-registrar` is now deprecated, so this only applies to `oidc-discovery-provider`. Maintainers discussed the possibility of moving this out to another repository. We did not feel opposed to this happening, but at the same time don't see any urgency around this given that the `oidc-discovery-provider` has minimal dependencies. Since there is no urgency behind this and no one has volunteered to take this up, we are electing to close this issue for now.

If someone is interested in taking this up down the line, we are open to working with a contributor to separate out `oidc-discovery-provider` into a new repository.
