### ISSUE TITLE
"nodeattestor.proto" name conflicts when compiling external plugins

### ISSUE THREAD

**Issue by hiyosi** [spiffe/spire#2255]
* **Version**: v0.12.2
* **Platform**: x86_64 GNU/Linux, 
* **Subsystem**: node attestor plugins

An error occurs, when compiling external node attestor plugins.
```
panic: proto: file "spire/server/nodeattestor/nodeattestor.proto" has a name conflict over spire.agent.nodeattestor.NodeAttestor
        previously from: "github.com/spiffe/spire/proto/spire/agent/nodeattestor"
        currently from:  "github.com/spiffe/spire/proto/spire/server/nodeattestor"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

Since SPIRE v0.12.2, `google.golang.org/protobuf` is now v1.26.0. 
In `google.golang.org/protobuf` v1.26.0, name conflicts are now treated as errors.

We can specify that it is treated as warning as the previous version.
Please let me know if we can continue to ignore as warning.

**Comment by azdagron** [comment]
It is true that the server node attestor is in the wrong namespace (and has been since the beginning). We're fixing this for 1.0, where we've created a plugin SDK repository. The `v1` version of the server nodeattestor plugin has a corrected namespace (https://github.com/spiffe/spire-plugin-sdk/blob/main/proto/spire/plugin/server/nodeattestor/v1/nodeattestor.proto). External plugin authors will be able to use that SDK with SPIRE 1.0.

I take it from that message that you are compiling both the server and agent node attestor into the same binary?

**Comment by hiyosi** [comment]
> External plugin authors will be able to use that SDK with SPIRE 1.0.

Thank you! @azdagron 
I'll use the SDK when supporting v1.0.0.

> I take it from that message that you are compiling both the server and agent node attestor into the same binary?

No, each plugins are separated.

e.g.
```
cmd/
  agent/
    nodeattestor/
        main.go
  server/
    nodeattestor/
       main.go
```

**Comment by azdagron** [comment]
You might want to double check that you aren't unintentionally including both somehow (maybe in common packages?). The warning or panic happens when when there is a conflict during registration which happens at runtime during package initialization. If a binary doesn't include both, then only one or the other will be registered and no conflict will happen.

**Comment by hiyosi** [comment]
> You might want to double check that you aren't unintentionally including both somehow (maybe in common packages?)

You are right! I find out that the common package include both.
I can resolve this issue. 
Thank you very much! @azdagron

**Comment by hiyosi** [comment]
So I will close this issue :)
