### ISSUE TITLE
Federation Management API: define a strategy to persist changes done through the API

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#2260]
Changes done through the management API should be persisted. This presents some challenges considering the current implementation that manages federation through the SPIRE Server config file:
- How to reconcile data that is both in the config file and in the datastore? A federation relationship may be configured in the config file and in the datastore.
- How to propagate the changes to all servers? One option is to poll the database.

**Comment by evan2645** [comment]
This issue is tagged with the 1.0 milestone as we wanted to make sure the needed migrations were completed. That change has been merged already as part of https://github.com/spiffe/spire/pull/2359

The rest of this issue is concerned with reconciling differences between stored and configured relationships, which does not block 1.0, so I'll remove this issue from the 1.0 milestone.

**Comment by marcosy** [comment]
> How to reconcile data that is both in the config file and in the datastore? A federation relationship may be configured in the config file and in the datastore.

I have been thinking about this. One possible approach is to not persist into the database the entries loaded from the configuration file.

The API could query federation relationships from two sources:  

- The database
- The configuration file/memory

  Federation relationships configured from the config file would be read-only. They would be included in `ListFederationRelationships(...)` and `GetFederationRelationship(...)` RPCs but it wouldn’t be possible to update or delete them using the API. 

  Federation relationships created using the API would be stored in the database and would admit all defined RPCs. 

One tricky scenario would be the case of a user that uses the API to create a federation relationship to a trust domain that already exists in the configuration file. But I think we have a couple of options to address that problem (e.g: establishing precedence between entities in the database and in the configuration file).

I think this provides a good user experience by keeping the current behavior for federation entries configured from files and allows a smooth transition to an API-oriented federation configuration.

**Comment by marcosy** [comment]
Another option is to not reconcile the federation entries.

For example, we could include a new configurable called: `enable_federation_api`
 
- When it is set to false (by default) all continues working as it is now.
- When it is set to true, file-configured federation entries are ignored and federation relationships from database are used.

Then, each user can choose how to define federation relationships according to its own use case. 

It would be less flexible but simpler.

**Comment by azdagron** [comment]
> we could include a new configurable called: `enable_federation_api`

This is an idea, but IMO we should strive to have all APIs enabled by default. I think the API consumer experience is impacted negatively otherwise. I think it may also be likely that the same deployment would want both under some circumstances?

I think that the configuration file is and will remain a valuable mechanism to provision federation relationships (think of SPIRE server's deployed by and configured with traditional IT automation tools like ansible, chef, puppet, etc.). I think that our recommended best-practices would be that all SPIRE Server's in a cluster get the same federation configuration, but nothing prevents folks from diverging or configuring a specific server with the task of syncing a specific federated bundle. Considering each server can have diverging configuration, I don't think we want to try and load up and store static configuration into the datastore, since it seems that we'd have a hard time knowing when to remove it.

With that in mind, I think that leaves us with two distinct and independent sources, like you mentioned above, the configuration file and the datastore. That gives the following open questions:
1. how are relationships defined in the configuration file reflected in the API, if at all.
2. if the case of conflicts, which source takes priority?
3. can we handle the above in a way that allows for future flexibility (like changing the priority)?

For the sake of explanation, let's call the relationships defined in the file `static` and those by the API `dynamic`.

My proposal:
- static relationships are not reflected in the API by default, and otherwise they are read-only.
- static relationships can be returned by the API by special request (e.g. a "show_static" bool in the request) with an added field in the response that demarcates static v.s. dynamic relationships.
- static relationships override dynamic relationships by default (this preserves behavior in current deployments), however, we log a warning in SPIRE server when this is detected
- (optionally) add a configurable to the static configuration that allows it to be de-prioritized

**Comment by amartinezfayo** [comment]
Thank you @azdagron for your feedback. I agree that we should strive to have the API enabled by default, and I agree in general with the proposal.

>(optionally) add a configurable to the static configuration that allows it to be de-prioritized

This sounds like a useful thing thinking on a scenario where I want to start migrating from static definitions to a fully dynamic model. I may start creating all the relationships with the APIs and once I have all of them and want to test how that works, I can flip this configurable on, and even if I missed one, the static config will be a safety net. It would be a previous step before ripping them out of the config.
This is probably a good thing to have, although we may save some complexity if we don't implement this from the beginning and learn from the users if this is a demand or not?

I'm thinking what this proposal specifically means for each particular RPC, so we can identify issues before implementing:

- `ListFederationRelationships` and `GetFederationRelationship` RPCs are modified to be able to specify if static relationships are returned.
  - Add `bool show_static` in `ListFederationRelationshipsRequest` and `GetFederationRelationshipRequest` messages.
  - A `bool static` field is added in `spire.api.types.FederationRelationship` message, that's part of the response messages.

- `BatchCreateFederationRelationship`, `BatchUpdateFederationRelationship` and `BatchDeleteFederationRelationship` RPCs remain as they are today.
  - One possible question is if we need to provide any indication if a static relationship already exists when creating a new relationship. In particular, the `BatchCreateFederationRelationshipResponse` message may gain a field for that. Or we may log this situation in the server. I'm leaning towards the latter.

- No changes in `RefreshBundle` RPC.

**Comment by azdagron** [comment]
Hmm, `show_static` read ok to me when in the context of a "list" operation, but doesn't sound right for a "get". Maybe there is a name that sounds good with both?

- `include_static`?
- `allow_static`?
- other?

**Comment by amartinezfayo** [comment]
I like `include_static`.
