### ISSUE TITLE
Support custom URLs when configuring SPIFFE bundle endpoints in federation relationships

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#2278]
Currently, only address and port can be used to specify the SPIFFE bundle endpoint when configuring federation relationships with other trust domains.
This works well when the endpoint is served by a SPIRE Server, but is not flexible enough if the SPIFFE bundle endpoint is served by a custom implementation that may potentially serve the endpoint in a custom URL.

This is the current shape of a federation relationship configuration:
```
# federates_with "<trust domain>": configures the address of a bundle endpoint used to
# get a trust bundle for "<trust domain>". This section can be repeated per trust domain.
federates_with "domain1.test" {
    # bundle_endpoint: configuration of other server's bundle endpoint.
    bundle_endpoint {
        # address: IP or DNS name of the bundle endpoint that provides the trust
        # bundle to federate with `"<trust domain>"`.
        address = "1.2.3.4"

        # port: Port number of the bundle endpoint. Default: 443
        # port = 443

        # spiffe_id: Expected SPIFFE ID of the bundle endpoint server. This
        # is ignored if use_web_pki is true. Default: SPIRE Server SPIFFE ID
        # within the `"<trust domain>"`.
        # spiffe_id = ""

        # use_web_pki: If true, indicates that this server must use Web PKI to
        # authenticate the bundle endpoint, otherwise SPIFFE authentication is used.
        # Default: false.
        # use_web_pki = false
    }
}
```

`address` and `port` should be deprecated in favor of a unique setting that specifies a URL. The use of HTTPS must be enforced in the URL.

We can take the opportunity to make the configuration consistent with the language expressed in the SPIFFE Federation spec. To that effect, the following shape of config is proposed:
```
# federates_with "<trust domain>": configures the address of a bundle endpoint used to
# get a trust bundle for "<trust domain>". This section must be repeated for each
# federated trust domain.
federates_with "domain1.test" {
    # bundle_endpoint_url: Bundle endpoint URL. Default: "".
    bundle_endpoint_url = "https://example.com/global/bundle.json"

    # bundle_endpoint_profile "<https_web|https_spiffe>". Endpoint profile.
    bundle_endpoint_profile "https_spiffe" {
        # endpoint_spiffe_id: Expected SPIFFE ID of the bundle endpoint server. This
        # must be specified when using the https_spiffe profile. It's not valid in
        # the https_web profile.
        endpoint_spiffe_id = "spiffe://example.com/spire/server"
    }
}
```

Since we are replacing current configurable settings with a new structure, we will need to follow the usual deprecation path for those settings.

**Comment by azdagron** [comment]
Thanks @amartinezfayo ! This is looking pretty good.

One more thing I'd like to point out is that currently SPIRE defaults to the SPIFFE ID of the server in the trust domain that is being federated with as the endpoint SPIFFE ID. It enforces that the SPIFFE ID belongs to the trust domain being federated with. The federation spec allows for chaining of trust domains, i.e. using trust domain A to obtain the bundle for trust domain B, which because of this constraint in SPIRE, is not possible in today's implementation. It also fetches the bundle for the trust domain being federated with to authenticate the endpoint instead of the trust domain from the endpoint SPIFFE ID. As you pointed out in today's call, we should probably make the parameter explicit instead of defaulting to the ID of the server.
