### ISSUE TITLE
Allow for credential introspection in AWS for Database backends

### ISSUE THREAD

**Issue by caleygoff-invitae** [spiffe/spire#2283]
It currently is required to either pass in environment variables or hard code credentials for the database backends.
This might be a large ask but it would nice to not be confined to this. At least in kubernetes doing any of these is problematic. In AWS you can use IAM to Authenticate with RDS with MySQL or PostgreSQL. This is infinitely times better than having to get clever and attempt to pass in creds without leaking them. 

At least for AWS there is a Go tutorial on how to allow this with RDS
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.Go.html

I do not know what the equivalent is for GCP but it might be interesting to see if that is offered there too.

**Comment by evan2645** [comment]
Thank you for opening this @caleygoff-invitae ... yes, supporting this would be awesome :) though I'm not quite sure the best way to do it yet ... our datastore code would somehow have to know (via configuration?) that it was backed by RDS. We already have a dialect configurable you can select (e.g. mysql, postgres, etc), so this could be one of those, the only problem is that RDS supports both mysql and postgres!

Taking a step back, I think this is a more general issue as any/all datastore configuration needs some kind of login credential, and we currently don't have a way to separate it out from the main SPIRE config. This issue is related: https://github.com/spiffe/spire/issues/752
