### ISSUE TITLE
Cache miss in manager initialization for the 1st time agent

### ISSUE THREAD

**Issue by yangmarcyang** [spiffe/spire#2287]
* **Subsystem**: server

Co-authored by @poorkenny

When an agent finishes the node attestation, it will create a manager object by calling newManager, where a synchronization will be triggered in [initialization](https://github.com/spiffe/spire/blob/main/pkg/agent/manager/manager.go#L118) and authorized entries will be fetched from server's full in-memory cache. Then the agent will sync entries from server every 5 seconds as default sync interval. 
However, if it is the 1st time node attestation for this agent, the synchronization in manager initialization will always return 0 entry, due to the cache miss in server. The agent has to wait for a while to get entries in some synchronization thereafter. It will be great if the entries can be fetched in manager initialization for the 1st time agent.

**Comment by evan2645** [comment]
Thank you for opening this @yangmarcyang! It is a good point

Do you have any ideas on how to address it? One option could be to do a lookup on cache miss, however I worry about possible abuse.

**Comment by tihhoni** [comment]
Hi @evan2645

We've been running some performance tests on spire server and came to some bottlenecks around calls to GetBundle and GetAuthorizedEntries. So we were exploring for means to reduce the amount of calls.

This lead us to experimental config in spire agent sync_interval which controls how often those requests are made
https://github.com/spiffe/spire/blob/main/pkg/agent/manager/config.go#L36

However, that lead us to this issue here. In short:
- agent does node attestation
- agent requests authorized entries for the 1st time
- spire server cache has nothing about this agent yet until next cache is rebuild (lag period of 5 seconds)
- agent starts with its own cache empty and does nothing until next sync interval

So if we set sync period for e.g. 1h it makes agent useless until first clock sync is run

Possibilities that i can see for us:

- disable cache on server side so it will always go via DB (not sure if possible to configure) and use big sync_interval e.g. 24h
(considering that we want to reduce amount of calls to GetBundle and GetAuthorizedEntries it might not be that bad. But i understand cache is there exactly to guard against too many DB calls)

- have faster sync interval if 0 entries in cache then go with passed sync_interval
(will not solve initial cache empty but will help with bigger sync interval settings)

- block agent start (Initialize) until svid cache is not empty
(might not be what other customers want, so probably as a switch)

- server does DB lookup on cache miss (as you proposed)
(sounds reasonable and how typical "cache" should work)
