### ISSUE TITLE
SPIRE Agent Windows Support

### ISSUE THREAD

**Issue by colek42** [spiffe/spire#2342]
The SPIRE Agent should be extended to support attestation of Windows workloads.  The current version of Windows supports [UDS natively as of Windows 10 as of build 1809.](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/)  @azdagron Has done a POC using named pipes.

- What are the introspection capabilities through named pipes/windows UDS?
- How much does support of Windows users before build 1809 matter?
- User experience for OS-specific plugins, i.e. UNIX workload attestor.

* **Version**: n/a
* **Platform**: Windows
* **Subsystem**: Agent

**Comment by evan2645** [comment]
I don't have many answers, but I have some thoughts/observations :)

> How much does support of Windows users before build 1809 matter?

We could always start with UDS, and build support for other transports later on if we deem it necessary. One important thing to keep in mind is that if we introduce any transport other than TCP or UDS (e.g. named pipes), then we will need a change in the SPIFFE spec, which will take time.

> User experience for OS-specific plugins, i.e. UNIX workload attestor.

I'd like to suggest that we detect this at startup, and bail out.

This brings up another point which is, if we are going to launch windows support, we'd better have at least one attestor that works with it! So that work is probably in scope too.

@amartinezfayo has a bunch of other thoughts here too on scope and what all we'll need in order to support windows properly

**Comment by colek42** [comment]
Support for AF_UNIX was added in Go - https://go-review.googlesource.com/c/go/+/125456

**Comment by azdagron** [comment]
(SO_PEERCRED is not defined for Windows in Go's syscall package, I haven't tried to call this on Windows, myself)

**Comment by colek42** [comment]
Seems relevant:  https://github.com/golang/go/issues/41659

**Comment by colek42** [comment]
@Bradfitz looks like he is doing some work on this -- https://github.com/inetaf/peercred/blob/main/peercred_linux.go#L24 he may have some insight. 

Looks like grabbing the connection info from the TCP connection table might be a suitable path.

**Comment by amartinezfayo** [comment]
Thanks @colek42 for opening this issue!
Having Windows support in SPIRE is something that I personally think that would be very beneficial for the project, opening new avenues to grow the adoption of the project. I have the feeling that once we introduce at least a minimum support, we will start a path of more and more integrations with Windows.

The open questions raised are maybe the most important things to start looking at when considering this. At the same time, I think that there are some other aspects that need attention and should be part of the scope of this effort, so we don't miss them from the complete picture. Here are some thoughts:

- Deployment
There are different methods that may be supported, like just downloading the binary, use a package manager, an installer, etc. We should also think about how default paths are affected, including deployed config files.

- Privileges required
We need to figure out if the process running SPIRE Agent would need a special privilege that a non-admin user may not have.

- SPIRE Agent as Windows service
It may be desirable to run the agent as a Windows service. We need to consider if we may need to support registering it as a service.

- Development experience
Once we start supporting Windows in a way, developers will need to build it on Windows. We need to adapt our build tooling to support Windows.

- Changes needed in the CI
Consider the changes in the CI configuration to support building the Windows binary.

- Documentation
All the documentation that we have assumes Linux/Mac OS. We will need to update it as appropriate. I think that it will also be important to make a clear note of what is supported in Windows and what is not.

- Plugins supported
As mentioned by @evan2645, I think that at least one built-in workload attestor should be supported on Windows from the beginning, otherwise the support would be very confusing.

**Comment by amartinezfayo** [comment]
I forgot to mention that I would be very happy to help here :)

**Comment by ricardf** [comment]
We have some use casses that we could use the agent on windows to start using the project as for now we need to go for other solutions as we have linux/windows scenarios where we want to use the spire implementation.

**Comment by amartinezfayo** [comment]
@ricardf Thanks for your interest!
Could you elaborate on the use cases that you have? We are on the early stages of scoping the work, so knowing the details of your use cases would be very helpful.

**Comment by colek42** [comment]
I'd like to use SPIRE to provide certs to in-toto on windows build machines.

**Comment by ricardf** [comment]
> @ricardf Thanks for your interest!
> Could you elaborate on the use cases that you have? We are on the early stages of scoping the work, so knowing the details of your use cases would be very helpful.

Being able to deploy the agent and the helper into windows would allow to create different scenarios on windows.

One example can be on a kubeedge example:

![image](https://user-images.githubusercontent.com/16720621/132644642-f68e3161-70b4-498e-8bd4-b99b13421a44.png)

We have scenarios where the applications components is on windows, so at the moment we can run ghosttunnel on windows but not the helper.

I haven't tested, but it seems that envoy.exe could be used as a windows service, so this scenario could be possible in windows if we had the agent running on windows:

![image](https://user-images.githubusercontent.com/16720621/132645154-074befaf-508e-40c9-a526-428d161ecedb.png)

**Comment by amartinezfayo** [comment]
Thank you @ricardf for your detailed explanation.
I'm in the process of doing an in-depth research of all the different aspects involved for this, like if a change in SPIFFE specifications would be needed or can be avoided, etc.
I'm curious to know if you are already using SPIRE in environments that are supported today, or if running SPIRE on Windows would be your first experience with SPIRE.

**Comment by amartinezfayo** [comment]
Thank you @Falco20019 for sharing your use case!
What is being scoped at this moment is supporting running the agent on Windows only, not the server.
I'm also curious to know in this case if you are already using SPIRE in environments that are supported today, or if this would be your first experience.
It may be better to scope the server support in a separate issue, but in the meantime It would be great if you can share 1) more details about the SPIRE deployment topology that would be suitable for your use case, and 2) what Windows versions would be used. Thanks!

**Comment by Falco20019** [comment]
This would be our first productive SPIRE environment. I tried to get SPIFFE support for gRPC in C# for 2 years now (https://github.com/grpc/grpc/issues/20157), but the support was never implemented. Now we get another option through SDS with the xDS support in gRPC. Up until now, we only were able to develop our product with insecure credentials.

Our environment contains mostly up-to-date Windows versions including Server, but also Android devices. All endpoints would use xDS to get the certificates. Android will be looked into separately. For the start, Windows would be our main target.

We will have one agent per machine, and per machine multiple workloads. Most workloads are gRPC services that should use the SVID in X.509 form for peer AuthZ. We will also have other services like MQTT where we still want to check if we use Ghostunnel or long-living certificates.

There is a central xDS server used for service discovery with gRPC and we intend to extend that with the SDS from SPIRE. We also plan to use one SPIRE server for one trust domain with a X.509 upstream authority. For the first project, we can run the SPIRE server using Docker, so the Agent on Windows would be a bigger blocker. Long-term, we would also need a Windows version for the Server, since not all customers offer us a Linux or Docker environment.

We mostly run on-premise in the customer environment and not always have access to the infrastructure of the customer ourselves. So zero-trust would help us with maintenance.

**Comment by amartinezfayo** [comment]
I have some good news to share :)
With small modifications, I was able to build and run SPIRE on Windows, both the server and the agent.
I've implemented an initial tcp-based Workload API listener and a basic peertracker implementation for Windows that is able to obtain the PID from the connected peer.
To test workload attestation, I implemented also a basic Windows workload attestor, that's able to generate a selector with the username.
I'm optimistic that we can provide support for both the agent and the server. I'm dividing the work needed in tasks and I'll be creating a project to track this work. Here are some screenshots!

spire-server
![spire-server](https://user-images.githubusercontent.com/26970586/140586316-dbd4a6d0-5bf4-4564-b08a-225be3fd19d1.png)

spire-agent
![spire-agent](https://user-images.githubusercontent.com/26970586/140586327-0518bc0f-dc2d-4603-a681-74f5c8a97ebf.png)

fetch an SVID on Windows!
![api-fetch](https://user-images.githubusercontent.com/26970586/140586481-f6e19cf2-ddc8-493d-bbfb-329242661734.png)

**Comment by ricardf** [comment]
amazing :)

**Comment by amartinezfayo** [comment]
Windows support in SPIRE is being tracked in this project: https://github.com/spiffe/spire/projects/12.

**Comment by Falco20019** [comment]
I'm following along and saw, that https://github.com/spiffe/spire/pull/2695 will add the support for TCP peetracking on Windows. Just out of curiosity: TCP is mainly added because there is still the issue, that Go can't access the peer credentials on Windows when using UDS, right?

**Comment by amartinezfayo** [comment]
>I'm following along and saw, that #2695 will add the support for TCP peetracking on Windows. Just out of curiosity: TCP is mainly added because there is still the issue, that Go can't access the peer credentials on Windows when using UDS, right?

@Falco20019 Yes, that's correct. The current support that we have for peer credentials when using UDS in Windows is limited, being the main limitation that we don't have a way to obtain the PID of the peer. Since the [SPIFFE Workload Endpoint](https://github.com/spiffe/spiffe/blob/main/standards/SPIFFE_Workload_Endpoint.md) spec already supports exposing the Workload API as a TCP listen socket for implementations in which using UDS would impractical or impossible, we decided to follow this route.

**Comment by amartinezfayo** [comment]
@colek42 @ricardf @Falco20019 I'm working on a workload attestor that will generate Windows-based selectors (#2619). Assuming that this attestor would be useful for you, it would be great to know which selectors would be important for your use cases. User and group information are on my first thought, but maybe there are other selectors? Feel free to comment on this issue or in #2619, thanks!

**Comment by amartinezfayo** [comment]
Just wanted to provide an update here. We have found some limitations using the Workload API with TCP transport that makes it impractical to use in containerized environments at this moment. Additionally, any endpoint that requires both PID resolution and be protected by ACL (like the agent Admin API) would be very problematic to implement with a TCP transport. For this reason, we have [switched to named pipes](https://github.com/spiffe/spire/pull/2948) as the equivalent transport in Windows for the endpoints (both in the agent and the server) that are exposed over UDS in Unix platforms.

**Comment by amartinezfayo** [comment]
Since experimental Windows support is now supported in the main branch (for both the agent and the server), I'm closing this issue.
If you see an issue related with Windows support, or want a feature supported in Windows, don't hesitate to open an issue.
