### ISSUE TITLE
Restrictive key policy for  Server plugin: KeyManager "aws_kms"

### ISSUE THREAD

**Issue by vijaymateti** [spiffe/spire#2352]
Current aws_kms key pluggin create the kms key and apply's default key policy which allows are resources within current AWS account access the key.

It would be great if we can restrict the usage key policy to specific IAM role within the account.

You may want to include role arn as input field on the pluggin which can be applied as principle arn on kms key policy. 

E.g:

aws_key can have input role-name or role-arn as "spire-server-role" or "arn:aws:iam::111122223333:role/spire-server-role"

{
    "Version": "2012-10-17",
    "Id": "key-default-1",
    "Statement": [
        {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::111122223333:role/spire-server-role"
            },
            "Action": [
                "kms:CreateAlias",
                "kms:CreateKey",
                "kms:DescribeKey",
                "kms:GetPublicKey",
                "kms:ListKeys",
                "kms:ListAliases",
                "kms:ScheduleKeyDeletion",
                "kms:Sign",
                "kms:UpdateAlias",
                "kms:DeleteAlias"
            ],
            "Resource": "*"
        }
    ]
}

**Comment by marcosy** [comment]
Thanks for bringing this up @vijaymateti.

I am wondering if we should additionally include a new configurable to enable/disable this policy (something like `use_role_based_policy`). IMO there are two reasons for this:

 
- For plugin back compatibility.

- If we don’t include a policy statement that enables IAM policies to control access to the keys (like in the default case) there is a risk of the CMK becoming unmanageable (e.g. if the role is deleted).  So, some users may choose to use the default policy instead?  

From AWS [docs](https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html#key-policy-default):  "*the root user can access a CMK only when the key policy explicitly allows it. This is different from most other resources in AWS, which implicitly allow access to the root user*".

 Regarding the role name, instead of getting it from a configurable, we can get it from the assumed role in the instance using the AWS SDK.  
 
 Regarding key cleanup, keys created with the role based policy will be cleaned up only by servers that assumed the same role.

 
Thoughts around this approach @evan2645 / @azdagron / @amartinezfayo / @rturner3  ?

**Comment by evan2645** [comment]
@marcosy is it possible to define a default key policy that still allows root (in addition to "our" role) but with some restrictions added? For example, perhaps we can restrict signing operations, or we can add some kind of conditional that negates the iam-can-now-grant-unscoped-access problem?

**Comment by marcosy** [comment]
Yes that it is possible @evan2645 . We could include all the "management" permissions but not the "usage" permissions (`"kms:Sign"`, `"kms:Verify"`).

 Something like:
```json
{
	"Version": "2012-10-17",
	"Statement": [
	        {
                        "Sid": "Enable IAM User Permissions",
                        "Effect": "Allow",
                        "Principal": {
                            "AWS": "arn:aws:iam::111122223333:root"
                        },
                        "Action": [
                                        "kms:Create*",
                                        "kms:Describe*",
                                        "kms:Enable*",
                                        "kms:List*",
                                        "kms:Put*",
                                        "kms:Update*",
                                        "kms:Revoke*",
                                        "kms:Disable*",
                                        "kms:Get*",
                                        "kms:Delete*",
                                        "kms:TagResource",
                                        "kms:UntagResource",
                                        "kms:ScheduleKeyDeletion",
                                        "kms:CancelKeyDeletion"
                        ],
                        "Resource": "*"
                },
		{
			"Sid": "Allow full access to role",
			"Effect": "Allow",
			"Principal": {
				"AWS": "arn:aws:iam::111122223333:role/example-assumed-role-name"
			},
			"Action": "kms:*",
			"Resource": "*"
		}
	]
}
```

That reduces the risk of the key becoming unmanageable and provides a better user experience since the keys can be seen/managed in the KMS console.

**Comment by marcosy** [comment]
@evan2645  just to confirm I understood correctly: Do you suggest not adding a new configurable? 

In that case:

+ If the server is running under a particular role, we can create the keys using the above policy.
+ If the server has not assumed any role, we can create the keys with the default KMS policy.

I've been thinking about it and I don't see any problem with this approach and forward/backward compatibility as long as the server keeps the same role.

**Comment by evan2645** [comment]
I think that captures it all @marcosy thank you for the summary!

With regards to compat .. My vote will be to warn and require a role in the future. If we find that requiring a role is too heavy handed, we can always remove the restriction and take your second suggestion instead.

**Comment by marcosy** [comment]
Great! I updated the [PR](https://github.com/spiffe/spire/pull/2424) to reflect that behavior.
