### ISSUE TITLE
Agent restart crash without re attestation 

### ISSUE THREAD

**Issue by y2bishop2y** [spiffe/spire#242]
* **Version**: 
* **Platform**: 
* **Subsystem**: Spire Agent 

Have to figure out how the store the Base SVID key and cert on a Node so the Agent can restart on a crash without having to go through re attestation. 

Need to document and explain the different modes and affects of using in memory Base SVID (key).

Plugin to allow disk storage and retrieval of previously attested Base SVID

**Comment by evan2645** [comment]
Can fix re-attestation problem rather than skip attestation the second go around. To mitigate attestation methods which are vulnerable to replay (ex. AWS instance identity document), server can pass the agent a nonce which can be used in future attestations. This prevents unauthorized code from re-attesting using material which is available node-wide.

**Comment by evan2645** [comment]
Now that we have statically-linked plugins, it would be pretty trivial to introduce a keymanager named `disk`... either memory or disk must be configured. If you want to survive restart and your attestation mechanism only works once (like AWS), then you choose the disk keymanager. If you don't want to write the key to disk, then you deal with the consequences :)

This would be a lot less work than the nonce route, and would probably serve as a better MVP for this functionality.
