### ISSUE TITLE
How to attest program launched by interpreter process (java, bash, python, etc.)?

### ISSUE THREAD

**Issue by yangmarcyang** [spiffe/spire#2426]
We have deployed SPIRE in our company where each linux machine has one spire-agent running. Workloads on machine do attestation with spire-agent via unix workload attestor, by unix:uid and unix:path selectors. Recently when we were helping another team to attest their workloads, we found that their workloads are java programs and are launched via java binary. So, the unix:path is just the java binary path (e.g. /usr/jdk/jdk.1.8.0_131/bin/java), which cannot tell the real program info, which means any other programs launched by the same java binary with the same uid will also get the SVID.

Is there any way to handle this case so that only the program can get its SVID?

**Comment by azdagron** [comment]
The maintainers discussed this a bit today.

We need some way to distinguish the interpreted programs. One reasonable solution is  to run under their own user account, opening up the use of the unix:uid selector (@evan2645 made the observation that this is fairly common practice since running the processes under the same account in many ways groups them into the same security domain, allowing them some level of influence over each other).

Another thought is that there may be interpreter specific things we could do. For example, there may be metadata facilities that we could tie into for java or python that would allow us to introspect the running process from a trusted source. This would allow us to create an interpreter-specific workload attestor that queried those facilities and provide selectors for the trusted metadata. The caveat here is that the metadata would have to come from a trusted source and not something that the interpreted program had influence over. I don't know of any of these kinds of facilities off the top of my head though.

**Comment by elinesterov** [comment]
I think that could only be interpreter-specific attestor plugins, e.g., java, python, etc... As for java, one thing that comes to my mind is the `jps` utility from the java framework that can provide information specific to java packages. My one-minute google-fu allowed me to find https://github.com/tokuhirom/go-hsperfdata ( but I didn't test it). We can use something like this to create a java workload attestor for the environment where it is impossible to have different users for different processes.

**Comment by yangmarcyang** [comment]
@loveyana and I brainstormed about this and we are thinking whether we can utilize cmdline (https://github.com/shirou/gopsutil/blob/master/process/process.go#L355-L365) of the process as a unix selector. It contains all arguments of the interpreter process, which looks promising to distinguish the program with others. Any comments?

**Comment by azdagron** [comment]
Unfortunately producing selectors from `/proc/pid/cmdline` is not safe since it can be modified by the process itself with a little bit of hacking.
