### ISSUE TITLE
cgroup error on macOS while connecting the agent

### ISSUE THREAD

**Issue by tahirali-endurance** [spiffe/spire#2451]
I am following the starter doc at https://spiffe.io/docs/latest/try/getting-started-linux-macos-x/#retrieve-and-view-a-x509-svid. While starting agent on macOS, I am getting cgroup error:

```text
ERRO[0001] Failed to collect all selectors for PID       error="workload attestor \"docker\" failed: rpc error: code = Unknown desc = workloadattestor(docker): open /proc/59346/cgroup: no such file or directory" pid=59346 subsystem_name=workload_attesto
```

* **Version**: 
```bash
bin/spire-server --version
```
1.0.0-dev-unk

* **Platform**: 
```text
Darwin wal-miali-210423 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64
```
* **Subsystem**:

**Comment by sanderson042** [comment]
[This seemed like a doc issue at first and I help with spiffe.io docs, so I'm summarizing the planned fix for this issue. This issue started as this thread on the SPIFFE #help Slack channel on 9 August 2021: https://spiffe.slack.com/archives/CBNCC2V17/p1628562982031900]

Although it seems serious and is distracting, this error doesn't stop the tutorial from working because the tutorial uses the unix attestor rather than the Docker attestor. @evan2645 says this issue was discussed in the SPIRE maintainers meeting and, as a quick fix, a special version of the config file could be created for this tutorial to prevent this error message by only configuring unix selectors. If that occurs, the text of the tutorial will need to be changed to tell users where to get the special config file.
