### ISSUE TITLE
Provide official CSI driver for mounting the Workload API socket into containers

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#2459]
Up until now, examples and tutorials have relied on [hostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) mounts to mount the Workload API socket provided by the SPIRE agent DaemonSet into workload containers. `hostPath` requires elevated privileges, is generally avoided as part of Security Best Practices, and is outright disallowed in many environments for workload containers. 

A [prototype CSI driver](https://github.com/azdagron/spire/tree/wip-wlapi-csi-driver/support/k8s/wlapi-csi-driver) was developed some months back that allows the Workload API socket to be mounted into containers via an ephemeral, inline CSI mount. Allow `hostPath` mounts are required, they are limited to the communication between the CSI driver and the kubelet, by design. 

The prototype has been deployed and used in several environments (e.g., #2452) and has proven to be a viable solution.

We have decided to make the CSI driver available as an official component of the SPIFFE/SPIRE umbrella. This issue tracks the work to make that happen. Here is a checklist of things we need to decide before publishing:

- [x] component name
- [x] source code repository
- [x] release pipeline
- [x] CODEOWNERS

**Comment by azdagron** [comment]
My two cents:

> component name

Currently, it is named `wlapi-csi-driver` which is purpose-specific, but not functionality specific. The CSI driver implementation itself is very generic and applicable to mounting any single directory into N containers. I don't have a strong suggestion though.

> source code repository
> release pipeline

Due to the generic nature, the simplicity of purpose, and the unlikeliness of this component needing to undergo a lot of churn, particularly in breaking ways, I'm steering towards this thing living in it's own repo with an as-needed release schedule?

> CODEOWNERS

I'd be happy to volunteer as a maintainer. I don't see this component as a particularly heavy burden. Other volunteers welcome!

**Comment by erikgb** [comment]
@azdagron I/we will be happy to see this happen, and to help - where we can. But with limited knowledge of SPIRE internals and CSI, don't expect too much from me/us. 😉 Testing the CSI driver is something we could easily help with. Running multi-tenant Openshift clusters, we are looking forward to be able to provide SPIFFE IDs to our user workloads - without granting any standard user generic hostPath mount permissions. I could also help out in reviewing pull requests.

My two cents:

> component name

I would go for something like `spire-hostpath-csi-driver`, or even just `spire-csi-driver`. I am also ok with dropping the "driver" term from the name. I haven't looked too much on the code in your POC, but would we be able to use the [K8s csi-driver-host-path](https://github.com/kubernetes-csi/csi-driver-host-path) if https://github.com/kubernetes-csi/csi-driver-host-path/issues/239 was fixed?

> source code repository

I would also vote for an "own repo with an as-needed release schedule". This also the direction the cert-manager team has selected to go with https://github.com/jetstack/cert-manager-csi.

**Comment by evan2645** [comment]
> source code repository

+1 on dedicated repo. I think we can look to prior art for the naming, `spiffe/spiffe-csi` seems appropriate because I _think_ this should work with any SPIFFE implementation ... is there a chance that we end up having to add any SPIRE-specific bits here?

> component name

With a repository name of `spiffe/spiffe-csi`, I think that `spiffe-csi-driver` makes sense. It is likely that we'll want to ship an admission controller as well that can inject the workload api socket automatically. If we did, would it also ship from this repo? I would think so ...? And in that case ... `spiffe-csi-admission-controller`? Or would it be the same binary?

>  release pipeline

GitHub actions, container image publish only ... I assume we'll want the image names to align with "component name"

We'll probably want to run nightlies or weeklies just to make sure everything keeps building, but probably not necessary to post any artifacts from these

**Comment by azdagron** [comment]
:+1 on spiffe/spiffe-csi
:+1 on spiffe-csi-driver
:+1 on github actions image publishing

I also think we'll eventually want an admission-controller for this. I don't think there is any real benefit to throwing them in the same binary though. Would we publish both components under the same version number or would be do some approach to releases that didn't rely on tags?

**Comment by evan2645** [comment]
> I also think we'll eventually want an admission-controller for this. I don't think there is any real benefit to throwing them in the same binary though.

Less goo in the build pipeline? Perhaps a single container image with arg-based switch?

Is this to say that you agree that such a controller should live in the `spiffe/spiffe-csi` repo too (regardless whether it's a separate binary or not)? I think it should

> Would we publish both components under the same version number or would be do some approach to releases that didn't rely on tags?

I think these things will be tightly coupled. Tag-based release is my personal preference because that's what GH integrates well with. IMO version numbers should track each other if they're separate binaries. For example, if we add a new feature on the CSI driver that gets leveraged by setting some yaml in the workload pods, then the controller would need to learn how to do that too and be configurable for it.

**Comment by erikgb** [comment]
+1 for all in the latest comment from @evan2645! I started writing something, but you sum it all up.

**Comment by azdagron** [comment]
> Is this to say that you agree that such a controller should live in the spiffe/spiffe-csi repo too

Yes, I agree that a single repository is good

>  Perhaps a single container image with arg-based switch?

I think this is a minor usability loss. It's nice to have the image name be self explanatory as to the function. It's also nice to not have to mess with args. Folks very often copy-and-paste YAML blurbs and making it the same name with different args makes it a little too easy to copy and paste the wrong blurb and end up with a misconfiguration, IMO.  I'm personally willing to sacrifice (what I think to be) a small amount of script boilerplate to produce two images with clear purpose and intent.

> I think these things will be tightly coupled. 

I think you are right. Tag-based SGTM.

**Comment by azdagron** [comment]
This is available at https://github.com/spiffe/spiffe-csi.
