### ISSUE TITLE
Serial Numbers in CA certificates and conformity with  RFC5280

### ISSUE THREAD

**Issue by SilvaMatteus** [spiffe/spire#2484]
Hi all,

The SPIRE Server generates CA certificates with a serial number equals to zero (0x00). Following the RFC5280, it would be good to have these serial numbers be positive integers.

I would be happy to open a PR.

* **Version**: master
* **Platform**:  any
* **Subsystem**: server

**Comment by azdagron** [comment]
This is a historic behavior, so I'll defer to @evan2645 , but I think we should fix it?

**Comment by evan2645** [comment]
Way a long time ago we had some fairly significant serial number issues. That has since (long ago) been solved, but to my amazement it seems like we overlooked CA cert.

We now have[ helper util in x509util](https://github.com/spiffe/spire/blob/main/pkg/common/x509util/serialnumber.go) for generating these serials. We should use that, the space is large and the recommendation is a random number (which this helper method produces).

In terms of reasoning for why things are this way right now: there is no purpose. In terms of compat: I _think_ we are OK to introduce this at any time. I don't think serial number is in the validation path (unlike similar things such as AKID/SKID). My vote is to ship a fix with the next release.

Assuming everyone else agrees ... perhaps @SilvaMatteus would be willing to send a PR?

**Comment by azdagron** [comment]
Yep, big +1 to using the serial number generator. I agree that this doesn't seem to have a compat component to it and can go in as soon as ready.
