### ISSUE TITLE
Keep only single copy of SVID chains in Agent cache

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#2591]
The Agent cache currently contains the [chain](https://github.com/spiffe/spire/blob/f6327103c7ccf640d4ba6f5ec1b5effa9d09e069/pkg/agent/manager/cache/cache.go#L57) for each [SVID in the cache](https://github.com/spiffe/spire/blob/f6327103c7ccf640d4ba6f5ec1b5effa9d09e069/pkg/agent/manager/cache/cache.go#L698). The number of unique chains that a single agent should need to cache should generally be fewer than two times the number of server instances (considering rotation of each server CA SVID). Keeping the chain for each SVID stored in each cache entry results in a lot of duplicate certificate data held in the Agent memory.

X.509-SVIDs are roughly 1 KB in size. For a chain of length 2, this means each workload SVID will occupy 1 KB (workload cert) + 2 KB (chain certs) = 3 KB in the cache.

Taking an example of an HA deployment with four Server instances with a chain of length 2, we would expect at most eight unique chains in the cache. This is the approximate memory consumption that could be reduced from the cache if each unique chain was cached only once:

(100 SVIDs/agent * 2 KB) - (8 chains * 2 KB) = 184 KB
(1000 SVIDs/agent * 2 KB) - (8 chains * 2 KB) = 1.84 MB
(10,000 SVIDs/agent * 3 KB) - (8 chains * 2 KB) = 18.4 MB

Chains could potentially be uniquely identified in the cache by the lowest intermediate's serial number (i.e. SPIRE Server CA SVID).

**Comment by MarcosDY** [comment]
In current implementation we verify only if svid.Chain[0] is expired to rotates, [getStaleEntries](https://github.com/spiffe/spire/blob/f6327103c7ccf640d4ba6f5ec1b5effa9d09e069/pkg/agent/manager/cache/cache.go#L436) or [shouldRotate](https://github.com/spiffe/spire/blob/f6327103c7ccf640d4ba6f5ec1b5effa9d09e069/pkg/agent/manager/sync.go#L79)

It is possible because we saves a fetchSVID response in cacheRecord, so what happens if we move out chain part? 
we may have a way to keep an "old" and "new" chain, because we'll need to concat the correct chain to form an Identity, or just once we see there is an update in chain force update for all entries that uses it.

**Comment by rturner3** [comment]
Closing this for now since the impact of this optimization is small, but affects a more sensitive part of the codebase. Also with the recently added LRU cache in the agent, this is probably less of a problem. If this turns out to be a bigger issue for someone down the line, we are open to discussing again.
