### ISSUE TITLE
Windows support: Windows workload attestor

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#2619]
Implement an agent plugin that is able to generate Windows-based selectors for workloads calling the Workload API.

**Comment by Falco20019** [comment]
Thanks for the callout. In the beginning, we are fine with user and group selectors. Since we are pretty new in the SPIFFE environment, we had not struggled with finding more or missing selectors so far.

Our application runs multiple services with distinct SVIDs in one process, but the bootstrapper will be in charge of distributing them as there is no better selector I could think of right now how to distinguish them even more.

**Comment by amartinezfayo** [comment]
Thanks for the feedback, @Falco20019!
