### ISSUE TITLE
DigitalSignature bit SHOULD NOT be set on a SPIRE CA cert

### ISSUE THREAD

**Issue by georgi-lozev** [spiffe/spire#2811]
* **Version**: `main`
* **Platform**: `N/A`
* **Subsystem**: `server` 

Following up on our discussion in [slack](https://spiffe.slack.com/archives/CBNCC2V17/p1645682516086949?thread_ts=1645612693.364219&cid=CBNCC2V17), question 2., regarding DigitalSignature bit in the Key Usage extension being set on the SPIRE CA certs when running in a nested mode.

More context in https://datatracker.ietf.org/doc/html/rfc5280#page-31 section
```
If the subject public key is only to be used for verifying signatures on
   certificates and/or CRLs, then the digitalSignature and
   nonRepudiation bits SHOULD NOT be set.
```

**Comment by azdagron** [comment]
Hmm, yes, I agree with your assessment and frankly was surprised to see this (I didn't think we set this usage bit). Doing a little code archaeology, SPIRE CA has had `digitalSignature` set for a very long time, predating my time on the project. The default Upstream Authority (CA) plugin stopped adding `digitalSignature` back in 0.7.0, but self-signed CAs still have it. Downstream CAs have also had it since their inception.

My guess is this was an oversight, but maybe @evan2645 knows if there was some intentional reason for CA's having the `digitalSignature` key usage? Barring that, I think we're fine to change this behavior.

**Comment by evan2645** [comment]
If it wasn't clear in my last message, I think we need to fix it 🙃

**Comment by azdagron** [comment]
Heh, yeah, i agree. Like you said, I'd be surprised if somebody was leaning on this. I'm also for fixing it and taking on the small risk here. We can call this out very clearly in the release notes.
