### ISSUE TITLE
Develop a method for consistent logging

### ISSUE THREAD

**Issue by noxora** [spiffe/spire#2865]
Not specific to any platform or version, but as a user of Spire, I have noticed that while troubleshooting some issues I've run into, logs have been inconsistent. Logs sometimes showing information that there is an error, without further explanation as to what the error is. For example, this is a healthcheck log I've seen on my Spire server

`time="2022-03-17T18:18:15Z" level=error msg="healthcheck has failed" check=server.ca.manager err="subsystem is not live or ready" fatal=true subsystem_name=health`

Which is an important log, but as a user, I am unsure how to proceed with debugging this. 

Other times, events that I would generally expect to be logged at debug don't exist. An example of this was when trying to understand why an SVID was not being given to a specific workload, it would have been helpful to get some context on why, other than saying no identity was issued. 

I've found the support in the slack to be amazing and everyone has been incredibly helpful, but I'd like to be able to debug more issues for which I lack the context in the future

**Comment by evan2645** [comment]
Thank you so much for opening this @noxora 

As I mentioned during our SIG-SPIRE call today, this problem is (as you've pointed out) pervasive. The outcome is a poor diagnostics experience, but I think there are a few contributing factors. I further think that a real solution to this problem starts with a project policy about how we treat log lines. We already have a section of our contributing guidelines that [covers logging](https://github.com/spiffe/spire/blob/main/CONTRIBUTING.md#logs-and-errors), however as you can see it is far from sufficient.

What exactly do we need to document here?

I can think of at least two things ... First, we probably want to document the different log levels, and have a clear policy allowing contributors to easily understand both when a message should be logged, and at what level. For example:
```
### Log-able events and log levels
...
#### Error
* Any unexpected condition that prevents SPIRE from continuing the current line of processing

#### Warning
*  Any unexpected condition that is recoverable
* Any time we observe a deprecated behavior

#### Info
* Any time internal SPIRE state changes
* Any time SPIRE API handles a call
```

The second thing is that we also probably need to capture _what makes a good log message_. Perhaps this goes in the top-level section in the snippet above. Things like "log messages should always indicate a path to resolution" would be great to see there.

I feel if we can solidify these guidelines in the contributor docs, we can 1) "stop the bleeding", and 2) position ourselves to circle back around and fix all the spots where we don't meet the new guidelines.

What do you think? Would this be something you'd be interested in helping with?
