### ISSUE TITLE
Loose sanitization rules for label value in telemetry

### ISSUE THREAD

**Issue by deanyxu** [spiffe/spire#2895]
Regarding the sanitizeLabel function, currently spire performs sanitize() for both label name and value. 
https://github.com/spiffe/spire/blob/bcfbaf9d8294fcb999b024ee986c3011f5b3e4ad/pkg/common/telemetry/sanitize.go#L36-L43

From the comment in the same file, it mentioned that Prometheus only allowed certain characters.
https://github.com/spiffe/spire/blob/bcfbaf9d8294fcb999b024ee986c3011f5b3e4ad/pkg/common/telemetry/sanitize.go#L13-L27
This is true for the name field, but usually more characters are allowed for the value field. For example, Prometheus allows any unicode character (https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)

Wonder is it ok to loose the sanitization rules a bit to allow more diverse types of label value?

**Comment by rturner3** [comment]
Hi @deanyxu , I can see that this is an unfortunate limitation in the telemetry today. Out of curiosity, are there any specific metric label values that you'd like to contain Unicode characters?

This seems like something that would be good to support, but it's a breaking change since dashboards/metrics aggregation may return different results once we start allowing Unicode characters in the label values. Knowing which metrics labels may contain Unicode characters would help us understand the scope and impact.

**Comment by deanyxu** [comment]
Hi @rturner3, thanks for replying. For our use case, we are trying to see if we could add a new `spiffe_id` tag to metrics like `server_ca.sign.x509_svid`. It would help to collect the usage of different customers. In our case, the value of `spiffe_id` would contain other characters like "."

**Comment by rturner3** [comment]
Thanks for sharing, @deanyxu . A consideration we have to make whenever we add any metric label is the cardinality of the possible value set. When the cardinality of a metric label value set can be very high, it can overwhelm metrics aggregation systems because the cost to index the metrics becomes too high.

Unfortunately, a SPIFFE ID is one example of a metric label that has potentially high cardinality. We have historically seen some metrics aggregation issues reported by higher scale users in cases where SPIFFE IDs were applied as metrics labels. For this reason, we have intentionally removed all instances of SPIFFE ID metric labels to avoid such problems.

That being said, did you have any other metrics labels in mind that would have values using Unicode characters?

**Comment by deanyxu** [comment]
SPIFFE ID is the only one we had in mind. You had a good point that attaching it to metric label was too much. Even though it seems that our metrics system is able to handle it, we are thinking to expose a variant of that to reduce loads to metrics system but could still tell us where the requests belong to

**Comment by rturner3** [comment]
@deanyxu For the other metrics labels you are considering, would you require Unicode characters? Just checking to see if this specific issue is still relevant for you given that we wouldn't want to introduce a SPIFFE ID metrics label.

**Comment by deanyxu** [comment]
Not for now. Thanks for the reply.

**Comment by azdagron** [comment]
Thanks for letting us know. Closing this issue for now.
