### ISSUE TITLE
HTTP Workload APIs

### ISSUE THREAD

**Issue by deanyxu** [spiffe/spire#3108]
Hi, we implemented a HTTP (non-gRPC) version of workload APIs and corresponding SDKs internally, in order to support internal services that did not want to have gRPC dependency. It is very similar to the gRPC approach, except both workload (i.e SDK) and agent communicate via REST instead of gRPC.
 
The changes are currently sitting in an internal fork of spire. We would like to check if the community is willing to consider accepting these changes? Appreciate any feedback/comment.

**Comment by azdagron** [comment]
Hi @deanyxu! Thanks for reaching out. We discussed this today and had the following thoughts:

- It is unlikely that even if SPIRE took this change that the SPIFFE specification would adopt an HTTP-based API alongside the gRPC-based API.
- gRPC seems to mostly be a barrier for adoption for existing (legacy) software that has a high cost to change, and considering that, there are already solutions for these kinds of software, for example using something to broker between the legacy software and the Workload API (e.g. the [SPIFFE Helper](github.com/spiffe/spiffe-helper))
- Having two Workload API implementations in SPIRE feels not ideal due to divergences of behavior, decision analysis (i.e. which one do I choose?), larger attack surface, etc. We already feel some of this with our support of the Envoy SDS API and hesitate to introduce additional complexity without a similar high strategic payoff that came with first class support of Envoy.
- Does your implementation implement server side streaming (e.g. via chunked encoding)? This is a fairly critical behavior of the Workload API for timely updates/revocation of identity related materials.
- While there is currently no client streaming or bidirectional streaming RPCs, if the Workload API were to gain such an RPC in the future, this would not be implementable via HTTP/1.1.

Having said all that, it's probably clear that we are hesitant to build this kind of support into SPIRE.

Have you considered implementing an HTTP<--->gRPC broker that can be deployed alongside these internal services? Depending on the workload attestors in use, this may be a viable path.

Alternatively, many languages support calling out to C. Would a C shared library that wrapped the Workload API be more consumable for these services?

**Comment by azdagron** [comment]
I'll close this out for now. Please let us know if you have further thoughts. Thanks!
