### ISSUE TITLE
Registration API should require Authentication

### ISSUE THREAD

**Issue by walmav** [spiffe/spire#311]
Look into  https://github.com/ory/hydra as a possible Oauth and OpenId integration.

**Comment by mcpherrinm** [comment]
I would prefer SPIFFE authentication to the Registration API....

**Comment by evan2645** [comment]
@mcpherrinm agreed. We have since moved the registration API to UDS only. I think that the ideal solution is to grant SPIFFE IDs administrative privilege, which will allow them to reach the Registration API via mTLS-based SPIFFE auth.

We have this issue open, which is tangentially related... perhaps we can accomplish both of these things at once: https://github.com/spiffe/spire/issues/635

**Comment by mcpherrinm** [comment]
Fixed via https://github.com/spiffe/spire/pull/656 ?

**Comment by evan2645** [comment]
Yes thank you
