### ISSUE TITLE
Automatic recovery from JWK key missing in trust bundle

### ISSUE THREAD

**Issue by yueqiao1** [spiffe/spire#3161]
We observed several JWT public key missing incidents because of split-brain in the database. To be more specific, because of the co-existence of two primary trust bundle database instances, Spire Agents get different trust bundles from Spire Servers and some trust bundles are incomplete. Therefore, some legal tokens cannot be validated because their public keys are not included in certain trust bundles.

Our current process to handle this type of incident involves the following steps:
1. Resolve inconsistency at the database side.
2. Identify which key is reported missing and which Spire Server instance is using the key for token signing.
3. Restart the Spire Server instance to stop it from signing more tokens that cannot be validated.
4. Identify which clients are using tokens signed by the missing key and then restart their Spire Agents accordingly.

The process is pretty manual and very fragile. There are multiple factors that can prevent us from a smooth recovery. For example:
1. It takes time to identify which clients/machines are affected by the missing key. 
2. Restarting Spire Agents on customers' machines sometimes requires special approval/permissions.
3. We observed once that the whole database was purged when SRE tried to fix the split-brain issue. We were lucky that it happened in a testing environment otherwise we need to restart all Spire Agents on the client sides.

Definitely, we need to work on improving the consistency at the storage side. But we feel like this type of missing key incident might be triggered by various reasons so it would be challenging to preclude them all. Therefore, we'd like to understand when such an incident happens, whether we can have a more automatic/quicker way to recover from it.  Below is a modified JWK key trust bundle lifecycle we thought might help resolve the issue:

1. When a Spire Server (re)starts, it first tries to reuse the latest valid JWK key from journal.pem (no matter whether it is in the database or not). If it doesn't exist, it generates a new JWK key and writes it into the trust bundle database and journal.pem.
2. The Spire Server instance periodically reads from journal.pem to get valid JWK keys and writes them into the trust bundle database.

Please let me know your thoughts about this solution and if you have better suggestions. Thanks in advance!

**Comment by rturner3** [comment]
Hi @yueqiao1 , the maintainers discussed this today and want to acknowledge the pain points you've described here with previous versions of SPIRE that had improper interactions with some SQL databases when updating the bundle. However, we feel that if there are data consistency issues like you described, they should be directly addressed with appropriate fixes in SPIRE Server datastore code and database replication configuration that ensures that primary database replicas do not drift out of sync, if using a multi-master configuration. As an example, #3039 addressed an improper transaction implementation in SPIRE when using PostgreSQL as the backing datastore by introducing read-modify-write semantics.

If I understood it properly, this proposal sounds like a defense mechanism built into SPIRE Server in case there were other data consistency bugs in the code. We are reluctant to add logic into SPIRE that works around data consistency issues, since it would potentially mask serious, underlying issues with SPIRE.

I'm curious to hear if you are still experiencing the issues you described with JWT key rotation using SPIRE 1.3.1+ (containing fix for #3039). If this is still a problem for you with SPIRE 1.3.1+, it would be great to open a new issue that is focused on solving the core consistency issues in the database.

**Comment by yueqiao1** [comment]
Thanks for your quick response, @rturner3 !

We had another round of internal discussion and felt like a defense mechanism is highly desired for better reliability. So we decided to work on adding it in our own fork if you still have concerns about adding it in the public version. And below is our rationale:

1. First I want to clarify that such kind of issues is not necessarily caused by code bugs. For example, the split-brain scenario typically happens because of a network partition. When it happens, we cannot assure both consistency and availability. We may prioritize consistency over availability, but there will still be a risk that a key owned by a newly booted Spire Server instance cannot be propagated to end clients as expected. In addition, SRE's misoperation may also lead to disastrous damage to the database. For example, we observed once that the whole database was wiped in a sandbox environment. SREs might be more cautious about such operations in production environments but they are humans.
2. Secondly, we cannot afford the price of such an incident, no matter how low the chance is. We are in the progress of installing Spire Agent on hundreds of thousands of machines in the next 1~2 months and turning on authentication for the majority of services in our company. We would like to avoid the risk of breaking running services as much as possible.
4. I understood your concern that our proposal might cover the root cause in certain scenarios, but I feel like we may still be able to capture unexpected behaviors via a monitoring and alarm system. We ourselves are curious about whether there are any bugs in the code. We would try to watch it closely and report to the SPIFFE community when we identify something.
5. And yes, our version contains fix [3039](https://github.com/spiffe/spire/issues/3039), which was actually proposed by my colleague. In fact, this fix [2770](https://github.com/spiffe/spire/issues/2770) is somehow also related and proposed by another colleague :)

**Comment by rturner3** [comment]
@yueqiao1 I think it would be helpful if we could identify some specific scenario(s) where a network partition somewhere in the deployment would result in a split-brain that results in workloads failing to verify SPIRE-issued JWT-SVIDs and how the proposed mechanism for handling JWT signing keys would mitigate those scenarios. I'm not quite sure I understand in what cases network partitions might result in a prolonged issue with distribution of a Server JWT signing key.

With the recent fixes you mentioned, the behavior should be that when SPIRE Server fails to add a newly generated signing key to the database bundle it will not sign any JWT-SVIDs with that key. Are you referring to issues with network partitions between replicas in the database cluster?

**Comment by rturner3** [comment]
If there are network partitions between database replicas that are causing data inconsistencies, there are many things that may go wrong - e.g. missing X.509 CAs in trust bundle, inconsistent entry sets, etc.

I don't think there is anything we can do to reliably address this class of failure modes within SPIRE itself. Reattempting a write operation when there is a network partition between a replica and the primary database instance doesn't provide us any guarantee that the data will be replicated to all replicas in the cluster. For signing keys, it is possible to do this attempt of re-writing, but I don't think it's reasonable to ask clients of SPIRE Server API to do the same when they create/update/delete data because they will have no way of knowing whether the data has been properly replicated. Retrying create/update/delete operations of only some SPIRE data persisted in the database also feels kind of arbitrary.

I think the more resilient solution is to make sure that the database cluster has appropriate monitoring that can detect abnormal replication delay or network partitions between instances and handle replacement of faulty replicas.

By misoperations, are you referring to manually deleting bundle keys in the database? There is no API to remove signing keys from the trust domain bundle of the SPIRE Server. We discourage any manual manipulation of data in the SPIRE Server database because it may cause unintended data corruption.

**Comment by yueqiao1** [comment]
> I think the more resilient solution is to make sure that the database cluster has appropriate monitoring that can detect abnormal replication delay or network partitions between instances and handle the replacement of faulty replicas.

Yes, we are going to add monitoring to detect this type of problem. But what makes us struggle is how to ensure the restored trust bundle contains all previously valid pub keys. We observed that some public keys are missing after our SRE fixed the database issue. But in the meanwhile, our clients are using tokens signed by the corresponding private keys, and they are supposed to be refreshed after 1/2 TTL. Unless we restart Spire Agents on the affected client machines, their tokens will be viewed as invalid for that duration. We thought that rewriting after the storage issue is resolved should help restore the trust bundle, but are you saying that's not the case? Do you have any better idea of how we can recover quickly from such an incident then?

**Comment by yueqiao1** [comment]
@rturner3 forced key rotation seems to be promising. About saving the signing keys in the database, I am not sure whether it can help here as the key problem is that the database itself may not be trustworthy. And yes, this type of incident did happen several times in the past 2 months.

We've added the requested feature support in our own fork. We may consider removing it to keep consistent with the OSS version when forced key rotation is available. Thanks for all your thoughts anyway.

**Comment by azdagron** [comment]
I'll go ahead and close this for now. Hopefully we get some cycles to move the forced revocation and rotation feature forward soon.
