### ISSUE TITLE
Performance Issue with excessive Get Bundle Requests

### ISSUE THREAD

**Issue by patricka3125** [spiffe/spire#3179]
* **Version**:  N/A
* **Platform**:  N/A
* **Subsystem**:  server

Hello, 

We observed some performance issues during failover testing when spire server received a large number of GetBundle requests. The performance hit comes from an excessive amount of pulls from the underlying datastore to fetch the trust bundle. I was wondering what the community's opinion is, or whether this discussion has been had on adding an additional caching layer over the datastore for retrieving trust bundles. 

Additionally, I've noticed in https://github.com/spiffe/spire/blob/main/pkg/server/cache/dscache/cache.go that there is some logic already implemented for a datastore caching mechanism for fetching/updating trust bundles. I am curious as to how that is utilized in a deployment setting. 

Would love to hear your thoughts and opinions, thanks!

**Comment by amartinezfayo** [comment]
> Additionally, I've noticed in https://github.com/spiffe/spire/blob/main/pkg/server/cache/dscache/cache.go that there is some logic already implemented for a datastore caching mechanism for fetching/updating trust bundles. I am curious as to how that is utilized in a deployment setting.

This caching functionality is only leveraged by the agent authorization checks, calls to the GetBundle RPC do not use the cache.

Since we haven't seen this kind of problem even in large deployments, there is a possibility that you are seeing this because of the way that the database deployment is configured.

It would be great if you can share some more details that would help to figure out what is happening here:
- What's the configuration of the datastore plugin? Are you leveraging the support of read-only replicas?
- What's the latency that you are seeing? What's your expectation?
- Could you share the RPS to this endpoint when you see the performance issue?

**Comment by azdagron** [comment]
Hi @patricka3125! Can you share additional insight into the questions @amartinezfayo posed above? Thanks!

**Comment by azdagron** [comment]
Closing for now due to inactivity.
