### ISSUE TITLE
k8s WorkloadAttestor plugin does not support anonymous authentication to secure kubelet port

### ISSUE THREAD

**Issue by rturner3** [spiffe/spire#3193]
When configuring SPIRE Agent to reach the kubelet over the secure port by setting `kubelet_secure_port`, the k8s WorkloadAttestor plugin requires usage of either an X.509 client certificate or a service account token in order to authenticate with the kubelet.

However, the kubelet also supports anonymous authentication over the secure port. Ideally the plugin should be able to support deployments of kubelet that use anonymous authentication.

**Comment by azdagron** [comment]
The agent needs get access to the nodes/pods via the kubelet as proxy. Typically this role is granted to the service account the agent is running under (and then granted to the agent when it presents the SA token).

How does the requisite RBAC work in this kind of deployment? Does the kubelet allow unauthenticated users access to the pod list?

**Comment by rturner3** [comment]
I'll try to offer some context behind this request, while acknowledging that it is in some ways a non-traditional use case.

Consider a Day 0 migration of a large set of services running on a private cloud that were previously managed by another orchestration platform to being managed by a self-hosted Kubernetes deployment. In this scenario, SPIRE Agent is not deployed by Kubernetes, but through an out-of-band deployment mechanism. Migrating SPIRE to be managed by Kubernetes itself is infeasible at the beginning, mostly due to implementation details of the infrastructure.

In this case, service account token authentication to the kubelet is not really feasible for SPIRE Agent, since it is brought up before Kubernetes itself and is not managed by Kubernetes (no corresponding service account).

Client certificate authentication to the kubelet is ideal for this use case, but also really challenging to implement at scale on Day 0 without a sophisticated traditional PKI system already in place.

During this period of time where SPIRE cannot be managed by Kubernetes and the kubelet client cert PKI is being bootstrapped, anonymous authentication is a low-friction way to get started with Kubernetes in the initial phase of migration.  I don't want to go into too much detail of how the RBAC works for security reasons, but you can imagine something like https://github.com/kubernetes/kubernetes/issues/83465 being present in the version of the kubelet being used, such that more fine-grained permissions can be granted to anonymous users of the kubelet secure port. Ultimately, using the secure port in this way rather than the read-only port is preferable since it still prevents man-in-the-middle attacks by using TLS.

Stepping back from the use case though, I can totally understand why it makes sense to second guess this kind of deployment, but I guess the question I would ask is whether it's the role of SPIRE to dictate how Kubernetes is configured? There are already some existing options in the k8s WorkloadAttestor plugin for disabling kubelet server certificate hostname verification and using the read-only port, both of which also have security drawbacks. Perhaps a good way to accommodate this mode would be to document that this configuration is not a recommended way to run the kubelet in most cases, or prefix the configurable name with `insecure` or `experimental`?

**Comment by azdagron** [comment]
Thanks for providing that use case, @rturner3. I agree that providing this feature doesn't weaken the security SPIRE provides, since turning on this feature should typically result in _less_ privileges with the kubelet, not more.

My first thought was, "if this is a temporary fix to bootstrap deployment, maybe they could just fork the k8s plugin and use that fork in the short term until everything was stable", but I can also see why going through the machinations and friction of deploying that plugin might be more hassle than it's worth.

In lieu of that, I'm personally OK adding configuration that can support this.

I don't necessarily think we need the `insecure` or `experimental` labels on the configurable. Maybe something like `use_anonymous_authentication`?

In any case, we should make that configurable mutually exclusive with the other credential related configurables (cert/key or token path). We should also provide some pretty good documentation on when somebody would choose this configurable.

Happy to hear from other maintainers if there is a different perspective.

**Comment by amartinezfayo** [comment]
Thank you @rturner3 and @azdagron for the thoughts on this.
I think that having a `use_anonymous_authentication` configurable would be OK if it is accompanied with clear documentation about when this setting is suitable to use. My main concern is around somebody using this as a shortcut when they could chose other authentication options.
