### ISSUE TITLE
Spire agent crash (restart) during upgrade

### ISSUE THREAD

**Issue by alitta-german** [spiffe/spire#3365]
Sometimes during our product's upgrade, the spire-agent restarts with this error: 
`time="2022-08-15T20:21:45Z" level=error msg="Agent crashed" error="create attestation client: failed to dial dns:///my-nsm-spire-server:8081: connection error: desc = \"transport: error while dialing: dial tcp 10.103.204.7:8081: connect: connection refused\""
`
Right after this happens, the restarted agent can start successfully:
```
time="2022-08-15T20:21:46Z" level=info msg="Starting agent with data directory: \"/run/spire\""
time="2022-08-15T20:21:46Z" level=info msg="Node attestation was successful" spiffe_id="spiffe://my.nsm/spire/agent/k8s_psat/nsm-cluster/10c216cc-3c05-48a8-91a8-9a13dc412d5b" subsystem_name=attestor trust_domain_id="spiffe://my.nsm"
```

Context:
Our product is delivered in a helm chart, that deploys NetworkServiceMesh and Spire together. During the upgrade of our product, on docker level the images have tags based on the version of the helm chart, even in case for example the Spire version is not changed. Due to this everytime we upgrade, the Spire pods perform a rolling upgrade (restarts with the new image tags).
In this case the Spire version was 1.3.3 (before and after the upgrade).
System: Linux my-nsm-test 5.4.0-1039-kvm #40-Ubuntu SMP Mon Apr 19 13:09:06 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
There are 2 spire-servers and a Service for them:
```
kind: Service
metadata:
  name: my-nsm-spire-server
  labels:
    app: "my-nsm-spire-server"
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: my-nsm-spire-server
```

Before upgrade there is only one spire-server:
`pod/my-nsm-spire-server-0                  2/2     Running   0          38s   192.168.34.148    worker-pool1-gjv7pf8x-n16-vpod1-senp02-ipv4-2585   <none>           <none>
`
After it there are two of them and you can see there was a spire-agent restart:
```
pod/my-nsm-spire-agent-4hlmc              1/1     Running   0             57s   10.0.10.15        worker-pool1-3t82e5a8-n16-vpod1-senp02-ipv4-2585   <none>           <none>
pod/my-nsm-spire-agent-c4vch              1/1     Running   0             45s   10.0.10.2         worker-pool1-s61lcqk5-n16-vpod1-senp02-ipv4-2585   <none>           <none>
pod/my-nsm-spire-agent-dxshb              1/1     Running   1 (61s ago)   65s   10.0.10.24        worker-pool1-qttl1k6r-n16-vpod1-senp02-ipv4-2585   <none>           <none>
pod/my-nsm-spire-agent-vxpg6              1/1     Running   0             51s   10.0.10.3         worker-pool1-gjv7pf8x-n16-vpod1-senp02-ipv4-2585   <none>           <none>
pod/my-nsm-spire-server-0                 2/2     Running   0             59s   192.168.34.152    worker-pool1-gjv7pf8x-n16-vpod1-senp02-ipv4-2585   <none>           <none>
pod/my-nsm-spire-server-1                 2/2     Running   0             65s   192.168.113.43    worker-pool1-qttl1k6r-n16-vpod1-senp02-ipv4-2585   <none>           <none>
```

The order pods(containers) were started:
```
2022-08-15T20:21:42Z my-nsm-spire-server-1_spire-server
2022-08-15T20:21:45Z my-nsm-spire-agent-dxshb_spire-agent_prev
2022-08-15T20:21:46Z my-nsm-spire-agent-dxshb_spire-agent
2022-08-15T20:21:48Z my-nsm-spire-server-0_spire-server
2022-08-15T20:21:53Z my-nsm-spire-agent-4hlmc_spire-agent
2022-08-15T20:21:59Z my-nsm-spire-agent-vxpg6_spire-agent
2022-08-15T20:22:05Z my-nsm-spire-agent-c4vch_spire-agent
```

So, only the first upgraded spire-agent had the problem, around the time when the spire-server was also upgraded.

Would it be possible to prevent restart in such case?
For example by implementing a retry mechanism.

**Comment by rturner3** [comment]
Hi @alitta-german, a few thoughts come to mind here:

It sounds like both your SPIRE Server and Agent pods are restarted around the same time (in this case an "upgrade" which is really the same version but using a different image tag)? Our [upgrade docs](https://github.com/spiffe/spire/blob/main/doc/upgrading.md#supported-upgrade-paths) mention that the Server upgrade needs to be completely finished before the Agent upgrade to avoid compatibility or availability issues. In this specific case, it sounds like Server <-> Agent compatibility is not a major concern since the images themselves are the same across the Helm chart upgrade, but upgrading the Server and Agent in parallel will still result in the availability issues you're noticing.

Is it feasible for you to split the SPIRE deployment across multiple Helm charts, one for SPIRE Server and one for SPIRE Agent? That would prevent some of the Agent crashes you are noticing.

Alternatively, if you are also looking for a way to prevent SPIRE upgrades in this scenario when the container image itself has not changed, you may consider not changing the SPIRE image tags for every release of your product. I understand that may be less feasible or desirable though depending on your use case and if you have automation that is driving the creation of those tags.

**Comment by rturner3** [comment]
Hey @alitta-german 👋 , just checking in to see if you were able to try any of the suggestions and if they work for you.

**Comment by alitta-german** [comment]
Hi @rturner3 , we discussed it in our team that non of these option are suitable for our product. But we've changed the upgrade base, so now it has also 2 SPIRE Servers and with this we have not seen spire-agent restarts since that during the upgrades.

**Comment by evan2645** [comment]
Hey @alitta-german - sounds like you were able to resolve the issue. Apologies about the upgrade policy .. we're considering some improvements there as a result, but it will likely be some time before there's any movement there.

Going to go ahead and close this out since it sounds like you're ok for now. Please ping back if you continue to have trouble. Thanks for opening the issue!
