### ISSUE TITLE
Add a resource tag(optional) when SPIRE server creates a KMS key

### ISSUE THREAD

**Issue by radnair** [spiffe/spire#3484]
Would be good to add an optional field (based on config) to add a resource tag to the keys that generated by the SPIRE server when using KMS.

The main reasoning for this ask is for being able to reduce the scope of permissions that SPIRE server needs specifically the `ScheduleKeyDeletion`; Once a resource tag is added the iam policy for the SPIRE server could be reduced in scope with conditions such as `aws:ResourceTag/tag-key`.

* **Version**: 1.4.0
* **Subsystem**: Server

**Comment by evan2645** [comment]
Hi @radnair - thanks for opening this. We've briefly discussed it today and have a couple questions/comments
* If IAM policy is being used to control which keys SPIRE Server can delete based on a tag value, but SPIRE has the ability to set an arbitrary tag value, it seems like the security control is circumvented? Perhaps you are wanting to do this purely for safety purposes rather than security?
* The [GCP plugin](https://github.com/spiffe/spire/pull/3410) does set a static tag onto the key for safety purposes, and we could do the same here as well (i.e. non-configurable)

**Comment by radnair** [comment]
Hi @evan2645 yes, wanted this for safety purpose (so that later on i can configure spire to only schedule key deletion for keys which has a specific tag like "spire_key": true etc. 
+1 to the GCP plugin - something like this would work

**Comment by amartinezfayo** [comment]
@radnair Aliases managed by the plugin have the following form: `alias/SPIRE_SERVER/{TRUST_DOMAIN}/{SERVER_ID}/{KEY_ID}`. Wouldn't be enough to add a condition to the Policy to filter only the keys that are managed by the plugin? Like:
`"Resource": "arn:aws:kms:region:account-id:alias/SPIRE_SERVER*"`

**Comment by amartinezfayo** [comment]
We discussed this some more in today's sync and the consensus was that it would be good that the plugin adds a (static) tag to identify the keys managed by the `aws_kms` plugin. Thank you for bringing this up, @radnair!

**Comment by radnair** [comment]
> We discussed this some more in today's sync and the consensus was that it would be good that the plugin adds a (static) tag to identify the keys managed by the `aws_kms` plugin. Thank you for bringing this up, @radnair!

Excellent sounds good!

**Comment by amartinezfayo** [comment]
Closing this, as there is no clear way to implement this in the plugin at this time. @radnair Please feel free to reopen if you have further considerations.
