### ISSUE TITLE
[RFC] Introduce SyncAuthorizedEntries RPC

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#3496]
There exist several problems with the agent sync for deployments that deliver a large amount of registrations to each agent (see #2675 and #2845).

To alleviate these problems and severely reduce the amount of network traffic required to do the agent sync in these situations, we propose the introduction of a new RPC with the following semantics:

- If the list of authorized entries is smaller than a given threshold, the entire list is sent back, mimicking today's GetAuthorizedEntries behavior, otherwise:
- The server streams back "sparse" entries, paged by a predetermined page size. The "sparse" entries just contain the entry ID and revision number.
- The agent receives the "sparse" entries and determines which entries need to be added, updated, or deleted.
- The agent streams up a list of entry IDs for the entries it needs to add or update.
- The server streams back the complete entry for each ID requested.
- The agent updates the complete entries in its cache. Deleted entries are removed.

This means that in the average case, there is no change in behavior. For these large deployments, there will be an initial sync of all entries when an agent starts up, but afterwards, the agent will only need to fetch full entries for what has changed. This should result in a large reduction in network traffic since nominally only the ID and revision number per entry need to be transmitted, omitting the relatively bulkier items such as Parent/SPIFFE IDs and selectors.

There is the potential for some increased latency, since the exchange requires multiple messages back and forth.

While we evaluate the behavior of this new sync exchange, we can reduce risk by putting it behind a feature flag until we're ready to ship it officially.

Thank you @amoore877 for designing the bulk of this proposal in #2875!

**Comment by azdagron** [comment]
A proof-of-concept for this work has been implemented [here](https://github.com/azdagron/spire/tree/syncauthorizedentries).

**Comment by amoore877** [comment]
> If the list of authorized entries is smaller than a given threshold, the entire list is sent back, mimicking today's GetAuthorizedEntries behavior, otherwise:

I have a non-major concern just about this one bit, where rather than consistently performing the same operations we introduce branching logic. Any decision point is inherently going to add a cost to maintenance and be a potential failure mechanism.
I can understand what is the counterpoint here though, that this reduces the practical complexity/overhead of cases not needing the multi-step syncing.

**Comment by azdagron** [comment]
This has not been merged. I've had other priorities. The last stretch is to finish implementing some basic tests and then get it merged under a developer feature flag for selective evaluation by interested parties.

Are you folks ready to give it a go? If so I can try and wrap it up sooner than later.

**Comment by stevend-uber** [comment]
@azdagron Are you still needing assistance in load-testing on this? We've had other priorities as well but coming up on being able to prioritize this soon. Unfortunately, I've lost our message history for the scenarios we want to test.

**Comment by azdagron** [comment]
@stevend-uber and I talked offline and testing should be starting soon.

**Comment by stevend-uber** [comment]
We ran a performance test using this feature against SPIRE 1.6.1. A conclusion of the results which is a subset of the numbers sent to @azdagron 

Summary

- We experienced an overall reduced amount of CPU utilization throughout the test simulations.
- We realized post-scenarios that latency of GetAuthorizedEntries was probably not an apt metric to gauge on since this is a
- completely separate feature and stream so that data is probably useless; it was included nonetheless.
- Net network traffic after SyncAuthorizedEntries was applied saw a drastic improvement for the network so that’s a big win.
- We were unable to get memory utilization differences for these simulations due to limitations in Uber infrastructure.

**Comment by evan2645** [comment]
Discussed this today in contributor sync, sounds like the best path forward is to enable this by default on the server side starting in 1.8, and have an experimental flag on the agent side. In 1.9, we can flip the agent to enable the pattern by default as well
