### ISSUE TITLE
Support Annotations selectors in Kubernetes workload attestor

### ISSUE THREAD

**Issue by lodthe** [spiffe/spire#3502]
At the moment, K8S WorkloadAttestor doesn't add pod annotations to workload selector list (but adds pod labels). I want to understand if this was done intentionally. If so, I'd be glad to understand the reasons of this decision. It may be useful for some users to match entries not only based on labels and other existing selector types, but on annotations too.

Annotations can be taken from the pod structure, like it's [done with labels](https://github.com/spiffe/spire/blob/598e28e1593be7e0ed8c6ef8582f8fd02e5766f3/pkg/agent/plugin/workloadattestor/k8s/k8s.go#L666).

The only potential problem I see is the unlimited size of annotation value. To avoid situations of too large workload selectors, a user can specify required annotation names in the plugin config. 

I'm not familiar with the limitations of selectors and can miss some other issues with the proposed solution. Would be glad to see your thoughts on this topic.

**Comment by evan2645** [comment]
If I had to guess, the unbounded length thing was probably seen as an issue when evaluating what should be surfaced as selectors and what shouldn't. Maybe one option is to hardcode a max, and log an error and fail to emit selectors for annotation values above that size.

Another observation is that when googling for annotations vs labels, the very first thing surfaced is:
```
Labels can be used to select objects and to find collections of objects that satisfy certain conditions. In contrast, annotations are not used to identify and select objects.
```

**Comment by lodthe** [comment]
I guess having large annotations is a common case, so error logging is unnecessary. In my mind, hardcoding a reasonable max length is OK. Also, it should be checked if all characters used in an annotation value could be presented in a SPIFFE selector.

If that's appropriate, I can try to implement this.

```Labels can be used to select objects and to find collections of objects that satisfy certain conditions. In contrast, annotations are not used to identify and select objects.```
I have seen that recommendation, but labels have their own limitations. For example, label value must be 63 characters or less.

**Comment by evan2645** [comment]
Hey @lodthe, thanks for the additional information. We discussed this a bit, and are having a hard time coming up with a good experience

> error logging is unnecessary

If we silently drop/ignore annotations that are too long, I think folks will get confused... workloads won't pass attestation if these dropped selectors are referenced, and there won't be any good indication as to why. I don't think we tightly manage maximum selector length (which would be done on server APIs instead of inside the agent), which increases the opportunity for confusing mismatches

> I guess having large annotations is a common case

This makes things more difficult, because I think we will definitely need to log somehow if we are dropping selectors, and if this is a common case, we can flood the logs. It will be especially annoying if the selector being dropped isn't being used/referenced by any registration entry

One possible compromise is to ask operators to set an allow list of annotation names/prefixes/etc ... but this is also not a great option, because an operator that is setting these selectors at the SPIRE Server API needs to know that they also must go to all agents and explicitly configure them to emit these selectors ... we don't really have any other selectors that behave like this at the workload level

> I have seen that recommendation, but labels have their own limitations. For example, label value must be 63 characters or less.

Perhaps the constraints placed on labels is also the same that make it good for a selector 😂 may I ask what kind of information you are packing into an annotation >63 bytes? Maybe it can be broken out into multiple labels?

**Comment by lodthe** [comment]
> may I ask what kind of information you are packing into an annotation >63 bytes? Maybe it can be broken out into multiple labels?

In most cases it's metadata like detailed information about release and even some parts of configuration.

> Perhaps the constraints placed on labels is also the same that make it good for a selector 

I had the same minds. Annotations that I want to use as workload selectors are < 64 bytes. The only reason why I prefer to put them in annotations (instead of labels), is that I never ask Kubernetes to filter k8s resources by them and I want to avoid extra overhead because of storing labels in etcd indices (or other types of indices/caches inside k8s).

**Comment by evan2645** [comment]
Hey @lodthe .. thanks for the reply

> Annotations that I want to use as workload selectors are < 64 bytes. 
> ...
> I want to avoid extra overhead because of storing labels in etcd indices

Oh, I see ... that makes sense

I'm still having a hard time coming up with a good way to support this. It seems like we either silently drop a subset of selectors, log noisily even in cases where the selectors aren't used, or truncate (which comes with security concerns). I don't think any of them are very good options...

I'm going to go ahead and close this issue out for now ... please do let us know though if you're able to come up with a solution that doesn't have one of the above drawbacks. In the grand scheme of things, we'd of course like to support annotations as selectors, but not at the expense of a confused/annoyed/vulnerable user experience. Thanks very much for opening this, sorry I don't have a better option for you right now.
