### ISSUE TITLE
Spire agent scratch image "Failed to lookup user name by uid"

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/spire#3702]
Scratch images are unable to get the uid.

* **Version**: 1.5.1
* **Platform**: k8s
* **Subsystem**: agent

```shell
time="2022-12-15T12:57:44Z" level=warning msg="Failed to lookup user name by uid" error="user: lookup userid 0: no such file or directory" external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog uid=0
time="2022-12-15T12:57:44Z" level=warning msg="Failed to lookup group name by gid" error="user: lookup groupid 0: no such file or directory" external=false gid=0 plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
time="2022-12-15T12:57:44Z" level=warning msg="Failed to lookup group name by gid" error="user: lookup groupid 10: no such file or directory" external=false gid=10 plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
time="2022-12-15T12:57:45Z" level=warning msg="Failed to lookup user name by uid" error="user: lookup userid 0: no such file or directory" external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog uid=0
time="2022-12-15T12:57:45Z" level=warning msg="Failed to lookup group name by gid" error="user: lookup groupid 0: no such file or directory" external=false gid=0 plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
time="2022-12-15T12:57:55Z" level=warning msg="Failed to lookup user name by uid" error="user: lookup userid 0: no such file or directory" external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog uid=0
time="2022-12-15T12:57:55Z" level=warning msg="Failed to lookup group name by gid" error="user: lookup groupid 0: no such file or directory" external=false gid=0 plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
time="2022-12-15T12:58:05Z" level=warning msg="Failed to lookup user name by uid" error="user: lookup userid 0: no such file or directory" external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog uid=0
time="2022-12-15T12:58:05Z" level=warning msg="Failed to lookup group name by gid" error="user: lookup groupid 0: no such file or directory" external=false gid=0 plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog
time="2022-12-15T12:58:15Z" level=warning msg="Failed to lookup user name by uid" error="user: lookup userid 0: no such file or directory" external=false plugin_name=unix plugin_type=WorkloadAttestor subsystem_name=catalog uid=0
```

Probably it would be good to create a user with a certain ID e.g. `1000`.
Create some expected folders and authorize this user.

Then copy this user to the scratch image. Inclusing the folders with those permissions.

This also allows us to run the image in kubernetes with the following securityContext.

```yaml
securityContext:
  runAsUser: 1000
```

As well we can do volumeMounts using this user.

**Comment by rturner3** [comment]
@marcofranssen Thanks for raising this! There is also some discussion of using a non-root user in scratch images in https://github.com/spiffe/spire/issues/3545#issuecomment-1331541391.

There are some potential pitfalls to using a non-root user by default because scratch images do not have the typical [FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html) provided by Linux distributions, which can cause some problems for users because SPIRE expects to be able to create its data directories and Unix socket at runtime. Since the data directory and socket paths are configurable in the server and agent, users who want to run as a non-root user will be forced to either run their containers as a designated uid defined in our images and accept some default paths created in the images (or mount those paths with correct permissions into the container), or create their own image builds that reference the scratch images and manage the container user + directories themselves.

As part of #3545, we intend to provide a guide that documents these choices for users so they understand the limitations and can choose the one that makes the most sense for them.

Regarding using the `unix` workload attestor plugin in a container, the behavior you are describing is also true for our alpine release images. If you want to attest workloads using the `unix:user` or `unix:group` selectors while running the agent in a container, you will either need to populate `/etc/passwd` and `/etc/group` with the users/groups for your environment as a volume mount from the host or statically at image build time.

**Comment by rturner3** [comment]
Closing this issue since the work is already tracked in #3545.
