### ISSUE TITLE
Feature request: Plugin can get the peer IpAddress

### ISSUE THREAD

**Issue by loveyana** [spiffe/spire#3708]
In our service, we hope to verify the consistency between the clientIP and the Principle Name in the Kerberos during the Node Attest process or set the IP list that allows connections to enhance the security of Node Attest. I thought I could find the corresponding interface in the hostservice but it seems that there is no way to get it.

I would like to see what the community thinks about this requirement and whether we can add this function so that plugins can get the information in the RPCContext including CallerAddr, CallerID, etc

**Comment by loveyana** [comment]
@evan2645 friendly reminder

**Comment by evan2645** [comment]
Hi @loveyana - I think we had someone ask for this on a previous occasion, but it wasn't clear how much it helped or if it was a "good" idea. One concern is that source IP address is rarely reliable from a security standpoint.

> so that plugins can get the information in the RPCContext including CallerAddr, CallerID, etc

CallerID won't be available since callers accessing node attestor logic are unauthenticated.

> or set the IP list that allows connections to enhance the security of Node Attest.

You may be able to accomplish this via iptables? Not sure if you want to apply this specifically to node attestation calls or SPIRE Server clients in general ...

I think the only way we can get what you're asking is to amend the NodeAttestor plugin interface such that it additionally passes caller IP... and probably some big long warnings on the field about SPIRE not being able to guarantee the reliability or integrity of the information passed in that field (which is part of why it doesn't feel great to include). If we added such a field, I don't think we'd ever want to support such functionality in any of the built-in plugins, but it could be consumed by a custom plugin.

**Comment by evan2645** [comment]
Going to go ahead and close this out due to inactivity, please ping back if we need to re-open it!
