### ISSUE TITLE
Mechanism for safe backups/restore of on-disk SQLite data

### ISSUE THREAD

**Issue by drrt** [spiffe/spire#394]
Copying the SQLite files should be safe for off-line storage and disaster recovery. Check-pointed files are also useful for testing complex configurations.

**Comment by evan2645** [comment]
@martincapello has done _some_ of this, if someone other than him picks this up ping him about progress

**Comment by martincapello** [comment]
To address this I'm working on the following proposal:
# Introduce new “data” command to spire-server:
Usage:
```
spire-server data <subcommand> [-path]
Subcommands:
    dump   
    replay 
```
### data dump: 
Makes a logical backup of the currently configured (and enabled) datastore’s data.  It saves all the data as JSON in spire-data.json file. By default it saves the file to current directory. 
### data replay: 
Takes a data dump in a spire-data.json file and replays the data into the currently configured (and enabled) datastore. By default it tries to read the file from the current directory.
### -path 
Is the directory (and optionally the filename) where the JSON data will be stored/read. If path doesn’t include a filename with .json extension, then spire-data.json will be used, and -path would be considered to point to a directory.

## Wish list:
- Datastore hot-swap: add to spire-server the ability to swap datastores without having to restart it.

**Comment by martincapello** [comment]
@evan2645 @amartinezfayo @walmav @MarcosDY feel free to take a look at the proposal, any comment will be appreciated!

**Comment by evan2645** [comment]
@martincapello sounds good to me! I have a couple small comments but those can be done during code review. The wish list definitely sounds out-of-scope for this work

**Comment by amartinezfayo** [comment]
It looks great! Just some thoughts to be considered in the implementation
@martincapello @evan2645 

- I think that we should consider adding some kind of schema version to the data dumped. That will help to handle data migration when restoring from an older version or decide what to do with an unknown version.
- My understanding is that the **restore** operation appends all the data to the current datastore. We need to make sure that the same validations when inserting the data are applied as if they would be manually added. e.g.: well-formed SPIFFE IDs, duplication of entities, etc.
- It seems that we don't have foreign keys in the SQLite database and we don't have unique constraints in certain tables where we have a composite key (e.g. for registration entries). Maybe it's time to consider this? I think that we should try to enforce the consistency of the data stored in the database as much as possible. I guess that this should be addressed separately.

**Comment by MarcosDY** [comment]
so, we want a backup, how about restoring it, it'll just clean actual db and put the content of our backup?
as Agustin I'm worry about DB integrity, I'm ok with versioning, but dont know if we have version concept in our current db, if we dont have it maybe we can consider it in the future, 
and provide code to merge an old db schema  supporting `n` versions before current db schema version.
it's no a problem for v1, but in possible patchs or upgrades, it will be necessary.
now a question, you said db will be saved as a json, must we compress it? dont know how  big that file will be.
another point is, will we lock db while dumping? if no we must prevent possible edge cases.

**Comment by martincapello** [comment]
I wasn't thinking in cleaning the current DB before making a data replay because it seems to me quite dangerous...I can imagine someone running a data replay by mistake over the incorrect DB  and loosing its data. Although, I had been considering ensuring that the database is empty before beginning the data replay, but this doesn't convince me yet.

About compression...it seems like a good idea, but I'm concerned about the ability of reading/writing a file as a sequence of chunks without having to load the entire file in memory for decompressing/compressing it, which for a large file, it would be overkill. I want to be able to read/write sets of DumpChunk messages (which size could be negotiated or configured) from/to a stream, I thought it this way because I wanted to read a potentially big file one chunk at a time. However, as currently each DumpChunk is a byte array, we could compress each chunk independently when transferring them (I will have to checkout if grpc provides compression already, in which case we would get this for free).

I would like to avoid locking the DB while dumping, and that's what I gonna do for the first version of this feature, later on we'll see.

**Comment by MarcosDY** [comment]
agree remove is dangerous, but as part of replay, we can create a copy and apply changes to it, and then use that db instead, that will prevent corruption in case of failures too, 
that can be solved with a transaction with rollback in case of failures, 
of course we need to prevent those kind of errors, where a user run replay in wrong/invalid DB

**Comment by evan2645** [comment]
> I think that we should consider adding some kind of schema version to the data dumped.

This is not a bad idea, but I will point out that the "schema" is unrelated to the database in use and is instead related to the database protobuf definition. I think ideally these will change infrequently... something to think about (will we keep old protobuf versions around? maintain protobuf compat instead? etc).

> It seems that we don't have foreign keys in the SQLite database and we don't have unique constraints in certain tables where we have a composite key (e.g. for registration entries)

I have been slowly adding these constraints, agreed we need to beef them up significantly. The reason that registration entries aren't (yet) protected with unique constraints is because the composite key is `parent + id + [selectors]`, where selectors are stored in a different table and reference the id of the record they belong to... I wasn't able to figure out how to build a unique key out of this.

> validations are made at the registration API handler (for example CreateEntry on registration/handler.go), and I was suggesting to create a new API handler (based on a new protobuf definition). (a) So, what should we do? Should we call the registration API from the data API? or should we avoid a new handler and add the Dump and Replay functions into the registration API?

I have also been slowly adding better data validation into datastore logic directly (in addition to the validation which exists in api handler). I think keeping data and registration api separate is a good idea. The restore method in datastore plugin can internally call the `Create*` methods that the datastore plugin exposes and can gain some validation that way.

> Another concern is about entities that are created as a side effect of some API call, that is the case for NodeResolverMapEntry and AttestedNodeEntry (which are created on the node/handler.go when FetchBaseSVID function is called). Should these entities be dumped?

These should all be dumped. If we lose AttestedNodeEntry between restore, existing agents won't be able to rotate their SVIDs. Similar problems for NodeResolverMapEntry

> The idea I was thinking of (not only for these entities, but all) is to dump them by adding some additional functions to the datastore plugin which enables the user to retrieve "pages" of entities (to avoid get all the entities at once)

I think we will definitely need this at some point, but not sure if we want to spend time doing this optimization just yet... As long as data format stays consistent, we can implement this later without disrupting much. Streaming interface can be useful here and should probably be used regardless of whether we page the data or not.

> What about JoinToken? Should we dump them all, none, or only the unused ones?

Should probably just dump all of them. I think we are missing a cleanup routine on these, but that's a different issue that we can address later.

> About compression...it seems like a good idea, but I'm concerned about the ability of reading/writing a file as a sequence of chunks without having to load the entire file in memory for decompressing/compressing it, which for a large file, it would be overkill

I think gzip might have the ability to stream compression/decompression. This is also something though that might be better left for later (for how many users will this be a problem today?).

> I would like to avoid locking the DB while dumping, and that's what I gonna do for the first version of this feature, later on we'll see.

One option as @MarcosDY points out is to open a transaction and do the dump from there.

**Comment by martincapello** [comment]
Thank you all for the comments and responses! Now I have a much clearer scope.

**Comment by martincapello** [comment]
> One option as @MarcosDY points out is to open a transaction and do the dump from there.

As far as I can tell, gorm doesn't support nested db transactions, so if I have to use the datastore's Create* functions, which uses transactions already, how should I control the restore transaction (which would be the outer transaction)?

**Comment by martincapello** [comment]
Current state can be viewed on https://github.com/martincapello/spire/tree/data-command

**Comment by evan2645** [comment]
This has not proven to be a problem in the time since we looked at it - at least, not one large enough to warrant the changes and work. Going to go ahead and close this out.
