### ISSUE TITLE
gRPC FetchX509SVID does not work as expected

### ISSUE THREAD

**Issue by amartinezfayo** [spiffe/spire#401]
Only one message is streamed when calling the `FetchX509SVID` API.
After the first successful response, the stream fails with the `PERMISSION_DENIED` error code, and the error message `"no identity issued"`. 

The following C++ code shows how this problem can be reproduced:

```cpp
#include <fstream>

#include <grpc/grpc.h>
#include <grpc++/channel.h>
#include <grpc++/client_context.h>
#include <grpc++/create_channel.h>
#include <grpc++/security/credentials.h>

#include "workload.grpc.pb.h"

using grpc::Channel;
using grpc::ClientContext;
using grpc::ClientReader;
using grpc::ClientReaderWriter;
using grpc::ClientWriter;
using grpc::Status;

static void fetch_svids() {
    std::unique_ptr<SpiffeWorkloadAPI::Stub> stub;
    std::shared_ptr<grpc::Channel> channel = grpc::CreateChannel("unix:/tmp/agent.sock", grpc::InsecureChannelCredentials());
    stub = SpiffeWorkloadAPI::NewStub(channel);
    
    X509SVIDRequest x509SVIDRequest;
    X509SVIDResponse x509SVIDResponse;
    ClientContext context;
    context.AddMetadata("workload.spiffe.io", "true");

    std::unique_ptr<ClientReader<X509SVIDResponse> > reader(
        stub->FetchX509SVID(&context, x509SVIDRequest));
  
    while (reader->Read(&x509SVIDResponse)) {
        std::cout << "fetched X509SVID with SPIFFE ID: " << x509SVIDResponse.svids(0).spiffe_id() << std::endl;
    }

    Status status = reader->Finish();
    if (status.ok()) {
        std::cout << "FetchX509SVID rpc succeeded." << std::endl;
    } else {
        std::cout << "FetchX509SVID rpc failed. Error code: " << status.error_code() << ". Error message: " << status.error_message() << std::endl;
    }
}

int main(int argc, char** argv) {
    fetch_svids();
    return 0;
}

```

Output:
```bash
fetched X509SVID with SPIFFE ID: spiffe://example.org/host/front-end
FetchX509SVID rpc failed. Error code: 7. Error message: no identity issued
```

**Comment by evan2645** [comment]
Update: workload api handler is functioning as expected. It turns out that there is in fact a brief period during which no cache entry exists for a given workload...

Cache manager calls a method named `checkExpiredCacheEntries()` which returns entries which need to be refreshed. Before returning them, however, it deletes the the entry(ies) in question. Subscriber notifications come from the underlying cache, so when the delete occurs, an update is (correctly) sent. Trying again shortly after results in success, as by that time the SVID has bee refreshed and a new cache entry created.

#416 works around this problem by implementing retries, but this is not a solution. Will need to spend a bit thinking about the right fix for this. It might lead to a refactor. Also see #418
