### ISSUE TITLE
Add BLAKE support to unix WorkloadAttestor

### ISSUE THREAD

**Issue by udf2457** [spiffe/spire#4035]
At present, the `unix` WorkloadAttestor only supports `sha256` hashing.

BLAKE2 (or BLAKE3) are much more efficient algorithms, see comparison at https://www.blake2.net/

BLAKE2 is available in Go stdlib under [golang.org/x/crypto](https://pkg.go.dev/golang.org/x/crypto)

**Comment by amartinezfayo** [comment]
Thank you @udf2457 for opening this issue.
I personally don't see a problem introducing a new selector based on BLAKE.
I'm curious to know if you have already been using `sha256` and experienced problems? Is performance the main problem for you?

**Comment by udf2457** [comment]
@amartinezfayo Tricky question to ask because on most modern desktop/sever hardware `sha` is reasonably performant, or at least "good enough".

I think the question comes more when we look at more CPU constrained environments (e.g. IoT, edge, virtualisation and containers).  That is likely where blake woud shine most.

**Comment by amartinezfayo** [comment]
Thank you for your response, @udf2457. My question was actually more about trying to figure out if using `sha256` has been problematic for your specific use case and knowing about your requirement to use BLAKE and less about the hypothetical benefits of BLAKE.
While introducing BLAKE support shouldn't be a problem, I would like to understand first why it's needed. Introducing this new selector would mean that we will need to figure out how we accommodate current configuration settings (that assume that only `sha256` could be enabled). We may end up needing to change the current behavior (through a deprecation path), introduce new settings, etc. That's why it would be important to know if there is a current justified demand or is something that we may need in the future but not at this point in time.

**Comment by amartinezfayo** [comment]
I'm closing this for now. We will be happy to take a look at this again if there is a concrete scenario where `sha256` is causing problems and introducing BLAKE would solve that.
