### ISSUE TITLE
Proposal: Configurable SVID rotation threshold on Agents

### ISSUE THREAD

**Issue by hiyosi** [spiffe/spire#4115]
This is the issue that previously discussed (https://github.com/spiffe/spire/issues/1754) .
Previous issue was closed, however I still need the feature.

### Proposal
The SVID rotation period is configurable.

### Motivation
In my production, There are different implementations of SPIFFE are running.  
(e.g. SPIRE and Athenz)

It is desirable that SVIDs issued by any implementation have the same availability level.
(e.g. SVID TTL=7days, Rotation=everyday)

### Details

A parameter is similar to the cert-manager.

```hcl
agent {
    experimental {
      rotation_config {
        x509_rotate_before = "144h"
      }
    }
}
```

Above example means that the Agent will rotate the SVID 6 days before expiration.

Limitations:
- The lower limit is considered to be a value such as `1m`.
- There is no upper limit, If the `x509_rotate_before` is grater than the SVID TTL, the Agent will fallback to default behavior (rotation at 1/2 of TTL).

I have a PoC code, so please refer to check more details.
https://github.com/spiffe/spire/pull/4116

**Comment by evan2645** [comment]
Hi @hiyosi , thank you for opening this.

I feel that trying to align rotation semantics across different SPIFFE implementations is a bit of a moving target and probably not practically achievable in the long run ... however, I also understand that having control over these rotation semantics allows you to more tightly control you availability/security trade-offs

We discussed this issue in a maintainer call last week, and the biggest concern is around usability of this feature, as well as the impact. We agreed that we should probably not subject signing keys to configuration in this way ... the logic there is more nuanced. We also agreed that this agent configurable should apply equally to agent SVIDs, workload SVIDs, and X509 and JWT. What do you think?

In terms of usability, having another duration-based configurable feels unwieldy. Questions around the min/max come up (as you have pointed out), and it impacts SVIDs with different TTLs differently. What happens when an SVID lifetime just barely exceeds the `x509_rotate_before` value? etc ... Two alternative ideas were discussed:
* **Rotation levels or modes:** we could have something like "lazy", "default", and "aggressive" to describe how quickly SVIDs will be rotated, as a function of their relative lifetime. The advantage of this approach is that it's easy to understand and think about, and we can easily change the internal details of what they mean in the future.
* **Rotation configurable as a fraction of TTL:** we could configure a value between 0-1, indicating at what point the agent should begin to attempt rotation, expressed as a fraction of the TTL of the SVID in question. The default can be 0.5 which is the current behavior. The advantage of this approach is that it gives more control, but at the cost introducing the potential for a bad experience (e.g. if a user configures 0.99 and normally has large TTL values, but then sets agent_svid_ttl to a low number).

**Comment by hiyosi** [comment]
@evan2645  
I appreciate the discussion.

> I feel that trying to align rotation semantics across different SPIFFE implementations is a bit of a moving target and probably not practically achievable in the long run .

My motivation is to provide users with the same availability level of SVIDs. 
So, the objective may be different than in the past.

> probably not practically achievable in the long run

I'm no sure why?
(sorry, maybe I didn't understand correctly)

> We also agreed that this agent configurable should apply equally to agent SVIDs, workload SVIDs, and X509 and JWT. What do you think?

Should the rotation configurable be the same even though the ttl configurable are different?
X.509 and JWT have different use-cases and different TTL sizes, so I think one value would not work well even if the configurable is like ratio.

e.g. The impact of 5% for 24h is different from 5% for 5m.

So, It would be better to be able to configure JWT and X.509 for different purposes.

> Rotation levels or modes:

I think it is difficult to understand when the SVID will be rotated.

> Rotation configurable as a fraction of TTL: 

Actually, I considered this approach before making this proposal.
In my opinion, there are concerns about it need for calculations and indivisible values for specific value. (e.g. 0.3333....).
However, we can achieve something close to my purpose by this idea as well.

Honestly, I think it is a matter of preference which is easier to understand.

**Comment by hiyosi** [comment]
What should I do next?

**Comment by evan2645** [comment]
>> probably not practically achievable in the long run
> I'm no sure why?
> (sorry, maybe I didn't understand correctly)

Just because we have no control over what rotation semantics other SPIFFE implementations choose to implement, and it's hard to see how SPIRE can support all the different possibilities as the number of SPIFFE implementations grows.

> Should the rotation configurable be the same even though the ttl configurable are different?
> X.509 and JWT have different use-cases and different TTL sizes, so I think one value would not work well even if the configurable is like ratio.

Hmm.. yes, maybe worth some more thought. Ultimately just trying to figure out how we can support your request without creating an overly complicated solution that is difficult to configure or easy to do the wrong thing. Perhaps two configurables isn't bad, and I think there is precedent for it. On the other hand, it might not be clear that something like `x509_rotate_before` also affects agent availability

>> Rotation levels or modes:
> I think it is difficult to understand when the SVID will be rotated.

It could be easier to understand if they are implemented as a fraction, and we can document it. I agree though that it is less clear than a straight number.

> Actually, I considered this approach before making this proposal.
> In my opinion, there are concerns about it need for calculations and indivisible values for specific value. (e.g. 0.3333....).

Yes that is one down side to the approach ... but IMO the downside with a static duration (e.g. not rotating until minutes/seconds prior to expiry) is more severe

> What should I do next?

We discussed this issue again on Tuesday, and neither of the solutions proposed thus far are feeling like a great fit. During our discussion, we talked about what it is that users are really trying to achieve with this configurable, and the conclusion was that we're trying to achieve some kind of manageable floor for availability purposes. There is an additional aspect which is security related, but that can be controlled by existing TTL configurables.

The outcome of the discussion was that being able to simply configure SPIRE with your desired level of availability is probably a good idea, and makes the functionality clear. I think that ends up being close to what you originally proposed, but with some added semantics and a different name.
```
agent {
     availability_target = 7d
}
```
When set:
* SVIDs will never rotate prior to ~20% of their lifetime (to prevent tight renewal loops where SVID TTL is just slightly higher than the availability target)
* SVIDs older than ~20% of their lifetime, but with less than the availability target remaining, will be rotated
* SVIDs older than ~50% of their lifetime will be rotated regardless of the availability target (to prevent low availability target from triggering last minute renewal on longer TTLs)
* If the agent caches a new entry that has a TTL set wherein it is not possible to reach the availability target, a warning is logged

I just took a guess at the percentages, we can tweak them however we feel is appropriate .. I think the more important bit is how we react in the various situations. What do you think?

**Comment by hiyosi** [comment]
> Just because we have no control over what rotation semantics other SPIFFE implementations choose to implement, and it's hard to see how SPIRE can support all the different possibilities as the number of SPIFFE implementations grows.

	- I understood. Sorry, I made a bad proposal.

- I just took a guess at the percentages, we can tweak them however we feel is appropriate .. I think the more important bit is how we react in the various situations. What do you think?
	- It looks fine!
	- Ideally, I would be happy if there is a way to relax the restrictions with an understanding of the risks.
	  e.g. parameter with prefix `subtle_*`, `unsafe_*`.  
	- Some our environments run with large TTLs and short rotation period.
	  e.g. `ttl=10d, availability_target=1d`, `ttl=30d, availability_target=1d`

**Comment by hiyosi** [comment]
@evan2645 

>  Is it that you want to a 10 day TTL and you want to rotate every day?

That’s correct.
So is the above configuration like this ?
`ttl=10d, availability_target=9d`

**Comment by hiyosi** [comment]
any updates?

**Comment by hiyosi** [comment]
What is the status of this issue?
If we can proceed, I would like to proceed this.
If this was rejected, I will close this.

**Comment by evan2645** [comment]
Hi @hiyosi , sorry for the delay here, I lost track of this issue and it recently bubbled back up.

I think you are right, the limits I proposed won't fit your use case very well. Thank you for sharing some examples from your environment. I spent some time thinking about it, here is an alternate proposal:
* The minimum configurable `availability_target` is 24hrs
* For any given SVID, `grace_period` = `ttl - availability_target`
* If `grace_period` is less than 12hrs, we log a warning and fall back to default rotation strategy
  * Could be that the SVID TTL isn't long enough to guarantee `availability_target`
  * Could be that SVID TTL is just slightly longer than `availability_target` and doesn't leave us much time to renew
* When `grace_period` is greater than 12hrs, and the remaining SVID lifetime reaches `availability_target`, the agent will begin renewal attempts

I think it's also easier to explain and reason about than the last one ... does it work better for you?

**Comment by evan2645** [comment]
@hiyosi yes I think that is accurate.

12hr grace period is just a guess from me, maybe we want to fine tune that ... but this general direction feels like a good one.

Is it something you'd like to work on? I will flip this issue to backlog/help wanted

**Comment by hiyosi** [comment]
@evan2645 

Thank you.

> Is it something you'd like to work on? I will flip this issue to backlog/help wanted

Yes I'd like to work on.

**Comment by mnp** [comment]
I wanted to express support here. We're investigating Spire for an IOT edge usecase.  Our adoption challenge is our edges may join successfully, store and update their SVIDs, and then -- unlike the datacenter usecases -- go offline for a month. Ideally, they can wake up, rejoin, and resume SVID rotation.  The current CA and x509 TTL server configs do not permit such a thing.
