### ISSUE TITLE
Feature request: emit trust domain in metrics

### ISSUE THREAD

**Issue by StupidScience** [spiffe/spire#4120]
In certain situations and setups metrics from multiple spire installations can appear in same metrics storage and then sometimes it is pretty difficult to understand which installation metrics belong to without additional configuration outside of spire’s one. My suggestion is to add `trust_domain` label to metrics, as for me add it to `started` metric only along with version would be sufficient. Wdyt?

**Comment by rturner3** [comment]
Hi @StupidScience, this generally sounds reasonable. I had a few questions that might help in scoping this request.

- Is there a particular monitoring scenario you're trying to enable that led you to want to add the trust domain label to only the `started` and `version` metrics?
- Did you have any other use cases in mind for the trust domain being a label in other metrics? I'm curious as to whether you already have some other way to differentiate other metrics, since I imagine it could be otherwise be confusing to correlate telemetry with a particular deployment.

**Comment by StupidScience** [comment]
Hi @rturner3.
I mostly use prometheus+grafana so my experience with other tooling and metrics engines are pretty limited. Anyway I assume it should be achievable there as well.

So with prometheus only we can add trust domain label to other metrics using prometheus alternative to join functions and joining on instance.  [Some random example](https://www.robustperception.io/exposing-the-software-version-to-prometheus/).
With grafana you can make filtering with variable that you'd get from `started` metric.
Not sure if it is defined anywhere but just noticed pattern with one metric like `up`/`started`/`info` that hold all or some metadata about target, so it won't bloat all other metrics.

**Comment by StupidScience** [comment]
@rturner3 I've sent https://github.com/spiffe/spire/pull/4131 to address this so PTAL if that looks good.
