### ISSUE TITLE
Update all examples that use SPIRE Agent K8s workload attestor to use node env to reach the kubelet

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#4147]
The agent defaults to localhost for reaching the kubelet but in some environments the kubelet is not available on localhost but rather the node IP.

We should update all examples to use the node IP (via the envvar available on the downward API).

See #2351 for an example of where this failed.

**Comment by krishnakv** [comment]
Hi @azdagron , could you please assign me this issue? Happy to follow the pattern in #2351 to clean up the examples.

**Comment by rturner3** [comment]
@krishnakv We'd love to get your help here. We'll do an initial assessment of all the examples that might be affected, and enumerate them as a comment in this issue.

**Comment by krishnakv** [comment]
I was able to identify the following examples where there are deployments to k8s in the SPIFFE github org.

In all these cases, I have listed the config files below. In every case, the deployment file is close and will also be modified.  Do advise if anything I have missed - happy to work with you. I will start with the changes, there will be multiple PR's since multiple repos are being changed.

https://github.com/spiffe/spire-examples/blob/main/examples/k8s/simple_sat/spire-agent.yaml#L38

https://github.com/spiffe/spire-examples/blob/main/examples/k8s/simple_psat/spire-agent.yaml#L66

https://github.com/spiffe/spire-examples/blob/main/examples/k8s/postgres/spire-agent.yaml#L38

https://github.com/spiffe/spire-examples/blob/main/examples/k8s/k7e/base_minikube_sat/config/spire-agent.conf#L23

https://github.com/spiffe/spire-examples/blob/main/examples/k8s/eks_sat/spire-agent.yaml#LL66C20-L66C20

https://github.com/spiffe/spire-examples/blob/main/examples/k8s/advanced/spire-chart/templates/agent-configmap.tpl#L28

https://github.com/spiffe/spire-tutorials/blob/main/k8s/quickstart/agent-configmap.yaml#L31

https://github.com/spiffe/spire-controller-manager/blob/main/demo/config/cluster1/spire/spire-agent.yaml#L71

https://github.com/spiffe/spire-controller-manager/blob/main/demo/config/cluster2/spire/spire-agent.yaml#L71

https://github.com/spiffe/helm-charts/blob/main/charts/spire/charts/spire-agent/templates/configmap.yaml#L26

The remaining, unresolved use case is where we are just creating a config file with the default 'WorkloadAttestor "k8s"' entry without the 'node_name_env = "MY_NODE_NAME"' entry e.g. https://github.com/spiffe/spiffe-helper/blob/main/examples/postgresql/spire-agent.conf#L21 . Not sure in this case if just adding the entry is  a good idea, as we cant be sure where the image will be deployed. Maybe we can tackle this under a separate issue?

**Comment by krishnakv** [comment]
Hi @rturner3 , pull request created for spire-tutorials. Will create similar PR's for spire-examples and spire-controller-manager over the weekend.

https://github.com/spiffe/spire-tutorials/pull/117

**Comment by krishnakv** [comment]
2 additional PR's created for `spire-examples` and `spire-controller-manager`. For spire-examples, testing uncovered additional issues (might be with my setup), have pinged offline about these. Do advise if any changes required to the `spire-examples` PR below of these potential changes  can be taken up in a separate issue?

https://github.com/spiffe/spire-controller-manager/pull/160

https://github.com/spiffe/spire-examples/pull/62
