### ISSUE TITLE
BatchNewX509SVID Response types.X509SVID Should Contain EntryID 

### ISSUE THREAD

**Issue by onesafe** [spiffe/spire#4261]
hello

BatchNewX509SVID returns a batch of certificates. The Agent finds which private key corresponds to which certificate based on the index, but matching by index is not a good way. 

It is better to add EntryID to the return value, and matching by EntryID will be more elegant. 
If some requests fail in the batch request, the number of returned data will not match the request, which may result in the private key matching the wrong certificate.

**Comment by evan2645** [comment]
> If some requests fail in the batch request, the number of returned data will not match the request, which may result in the private key matching the wrong certificate.

Did you experience this behavior @onesafe?

**Comment by onesafe** [comment]
yes. I requested the issuance of a certificate by connecting to the upstream PKI system. When there was a problem with the PKI request, I skipped the current request, which resulted in a lower number of returns. I admit that there is a problem with the code I wrote

**Comment by azdagron** [comment]
@edwbuck do you want to follow up here?

**Comment by edwbuck** [comment]
Further investigation indicates that this would require updating github.com/spiffe/spire-api-sdk/proto/spire/api/server/agent/v1/entry.proto(GetAuthorizedEntriesResponse and others) and / or github.com/spiffe/spire-api-sdk/proto/spire/api/types/entry.proto(Entry and others) to key off EntryIDs instead of the dominate pattern of keying off SPIFFE IDs.  

While the change will provide the finer grained access that would permit one to more easily which items are returned (independent of indexing or any other confounding issues) it seems against the current design in the spire-api-sdk and other documentation that prefers using the SPIFFE ID as the identifying element within an Entry (even when multiple entries contain the same SPIFFE ID due to differing selector sets).  

The "multiple entries for a SPIFFE ID" might mean that we should consider improvements to the protocol to focus more on EntryIDs, but, for your purposes, it would seem that you could already match on the SPIFFE ID of the returned items, avoiding any kind of non-matching indexing issues.  I'm going to ask Evan and others in the maintainers group about possibly changing the matching on the clients within the SPIRE offering to match based on SPIFFE IDs or possibly on EntryIDs, should the group decide to embed and distribute EntryIDs.

**Comment by edwbuck** [comment]
@onesafe 

A quick look into the GRPC prototypes indicate that the EntryID is already part of each replied Entry, and that the unpacking of Entries (done within package client under `spire/pkg/agent/client`) already slices the entry entities from the GRPC protocol packets, into Entries that are indexed by the EntryID

Lines 112 through 129 of `spire/pkg/agent/client/client.go` are responsible for requesting and unpacking the Entries, and the storage of them occurs on line 128, with the code

```
   regEntries[entry.EntryId] = entry
```

Which might mean that in your custom client, you would need to implement similar functionality to avoid any partial / out-of-order returns in the data replied to the client from the server.

Under normal circumstances, if the investigation showed that we were using indexing instead of embedded identities, I would call for an immediate code repair; however, it seems that in this case, there is nothing to fix as the desired repair is already in the code base.

If you can identify a different location where logic like this is missing, please let me know and we will open a Bug and fix the issue quickly.  If you can't find such an problem, please close this issue.

If you wish to address any other aspects of internal SPIRE functionality, or see an issue that is closely related; but slightly different, than this one, please open a new Issue as to not complicate it's handling with history that doesn't directly speak to the new problem.

Cheers, Edwin

**Comment by azdagron** [comment]
The semantics of the Batch APIs are such that:
1. There is one `result` in the response per `param` in the request (no holes).
2. The order of the `result`s are the same as the `params` in the request (order is maintained).

See https://github.com/spiffe/spire-api-sdk/blob/main/proto/spire/api/server/svid/v1/svid.proto#L95.

The entry ID for a given result in the response is derivable by inspecting the `params` in the request for the same index.

If there was a response observed that didn't follow these semantics, that would be a bug and we should investigate but I see no evidence of that in this issue.

**Comment by azdagron** [comment]
@onesafe, considering the description of the semantics that I posted above, do you still feel like there needs to be a change to the API?

**Comment by evan2645** [comment]
Hey @onesafe, we're going to go ahead and close this since we haven't heard from you in a few weeks. Please ping back or open a new issue if you'd like to continue the conversation. You can also reach us in Slack https://slack.spiffe.io

Thanks for opening this ❤️
