### ISSUE TITLE
spire-oidc does not start if federatesWith contains a down federated endpoint 

### ISSUE THREAD

**Issue by drewwells** [spiffe/spire#4445]
Spire oidc logs

### Example spiffeid
```
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spire-system-federates
spec:
  federatesWith:
  - non-existent.example.com
  spiffeIDTemplate: spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{
    .PodSpec.ServiceAccountName }}
```

### Repo Steps:
- Configure clusterspiffeids.spire.spiffe.io with a federatesWith to a down spire federation endpoint
- Attempt to start oidc
- See the above logs and oidc container terminates

### Results
```
Defaulted container "spiffe-oidc-discovery-provider" out of: spiffe-oidc-discovery-provider, nginx
time="2023-08-17T19:03:49Z" level=info msg="Serving HTTP" address=/run/spire/oidc-sockets/spire-oidc-server.sock network=unix
time="2023-08-17T19:03:49Z" level=debug msg="Polling started" interval=10s
time="2023-08-17T19:03:51Z" level=warning msg="Failed to fetch JWKS from the Workload API" error="rpc error: code = PermissionDenied desc = no identity issued"
time="2023-08-17T19:04:01Z" level=warning msg="Failed to fetch JWKS from the Workload API" error="rpc error: code = PermissionDenied desc = no identity issued"
```

### Expected
oidc gives some error that federated endpoint is down, or starts despite missing one federatesWith endpoint.

spire/helm-charts#454

**Comment by evan2645** [comment]
Thanks for opening this @drewwells!

Can you please check logs from spire-controller-manager to see whether or not it was able to create the registration entry for the oidc discovery provider? Can you also verify that SPIRE Server logged errors as well? Just want to make sure we  have a full picture of the situation before recommending a fix

**Comment by drewwells** [comment]
That's exactly what happens, and a helpful error message. Maybe we can push that through the workloadapi so error shows up closer to the client?

```
[spire-server-0 spire-controller-manager] 2023-08-24T17:37:42Z  ERROR   entry-reconciler        Failed to create entry  {"id": "", "parentID": "spiffe://box-4.infoblox.com/spire/agent/k8s_psat/box-4/39a03296-1cb9-402d-9f85-98c35f0f36a1", "spiffeID": "spiffe://box-4.infoblox.com/ns/spire-server/sa/spire-oidc-spiffe-oidc-discovery-provider", "selectors": "[k8s:pod-uid:f74811fc-6f1b-46a6-9540-04b39d175027]", "federatesWith": "[noop.infoblox.com,box-3.infoblox.com,env-2a.infoblox.com]", "dnsNames": "[]", "admin": false, "downstream": false, "error": "rpc error: code = Internal desc = failed to create entry: unable to find federated bundle \"spiffe://noop.infoblox.com\""}
```

**Comment by evan2645** [comment]
> Maybe we can push that through the workloadapi so error shows up closer to the client?

We don't have a clear path to propagating this kind of thing towards the workload unfortunately ... since the entry can't be created, we don't even know which agents should log, etc. I think the real problem here is that when an identity doesn't get issued to a workload, people's natural tendency is to start troubleshooting from the workload, but in SPIRE, you usually need to do the reverse.

I'm not sure how best to improve the situation. One thing we could do is try to fix the issue preventing an entry from being created when a bundle for a referenced federated trust domain doesn't exist. Unfortunately, it's pretty tough to fix and will probably take a few releases to get it done. Is it something you'd be willing to help work on?

**Comment by evan2645** [comment]
Hey @drewwells , since we don't have a clear path forward on improving this, I'm going to go ahead and close it. If you come up with a way to improve, even if it's just a docs change, please do open another issue or send a PR. If you'd open to working on fixing the requirement that federated bundle is present when creating an entry that references it, then let me know and I'm happy to spend some time writing up an issue for it. Thanks for reporting ❤️

**Comment by drewwells** [comment]
Can you close it as "won't do", I wouldn't want people to think this was completed.
