### ISSUE TITLE
Using k8s_psat attestation in sidecar model

### ISSUE THREAD

**Issue by netiperher** [spiffe/spire#4459]
We would like to start using Spire in a highly restricted multi-tenant Kubernetes cluster. In this environment it is not desirable to run the Spire agent as a DaemonSet due to it requiring elevated permissions (run as root, access to kubelet and so on).

Instead we would like to run the spire agent as a sidecar container together with the normal workload. In this model the attestation between server and agent uses the `k8s_psat` plugin, where a Spire node entry is created for each type of workload/service account. Attestation between agent and workload can use either the `k8s` or `unix` (requires `shareProcessNamespace` in pod) plugins.

A problem with the `k8s_psat` plugin in this configuration is that server creates an "agent id" with the node uuid in the path. https://github.com/spiffe/spire/blob/main/pkg/server/plugin/nodeattestor/k8spsat/psat.go#L209. So sidecar model only works when a single agent runs on the node. Would it be possible to make the "agent id" configurable, e.g. with a template approach that the `x509pop` plugin uses? For sidecar model using something like the pod uuid or pod name would work better than the node uuid.

* **Version**: All versions
* **Platform**: All platforms
* **Subsystem**: server, agent

**Comment by edwbuck** [comment]
The design of SPIRE has a SPIRE Agent that manages the Workload Attestation and Certificate issuances for all Workloads within a Node.  While it might seem like the Agent could be deployed multiple times within the same node, there are issues that arise when attempting to do so.  Some of those issues are due to the architectural choices made by SPIRE in the past, and could be altered; however, some of the issues intertwine with the distribution of SPIRE Entries which control if a SPIRE Agent should respond to a request for a Workload.  

Currently, SPIRE believes an Agent is the sole distribution point of a Node.  This means that the Agent will report aspects of the Node's identity in the Node/Agent Attestation to the pool of servers.  When two Agent instances of the same Agent Attester report to the same set of SPIRE Servers, the competition of the two instances can invalidate the other Agent's identity.  

Additionally, the Agent UNIX domain socket is intended to have a single location per node, which is important for the workload to communicate with the Agent as the Workload must be configured to use the correct UNIX domain socket.  While a Kubernetes Pod provides a private filesystem space such that two Agents would not conflict, SPIRE must also support non-Kubernetes deployments where the single operating system namespace would prevent all but the first Agent from launching.

Finally, the idea of removing the UNIX domain sockets is not one that is desired at this time, as it permits UNIX domain socket extensions to find the UNIX process table entry for the requesting workload, required for SPIRE's current solution of the bottom turtle problem.  Without a third party (the Operating System in this case) to validate the request is not a forged request, severe security issues could arise as it would remove a critical security check that the contents of the Workload ID request are consistent with the Workload making the request.

If you have further questions, or suggestions on how we might otherwise handle the functionality, please feel free to reach out to me in slack chat.

**Comment by evan2645** [comment]
Thanks very much for the explanation @edwbuck 🙏 

IMO the biggest issue at hand here is if and how we should deploy SPIRE Agent in the sidecar pattern, as Edwin alludes to. The problem is much broader than k8s node attestor support. I think we'd benefit from having an issue that is focused on that topic , rather than how do we fix k8s attestor to support it (e.g. "How and why SPIRE can support sidecar deployment pattern"). In that issue, it would be very useful to know the details of why we want to support this, and very importantly, what the threat model of that environment should be.

@netiperher are you up for creating an issue about the above? I'm happy to help make sure the right information is included, I see you're in the SPIFFE slack and you can contact me there under the same handle

**Comment by evan2645** [comment]
Hey @netiperher just checking back in here ... want to make sure you're on the right path, please let me know if the previous comment(s) made sense. Also welcome to join one of our community calls if the timing works for you: https://github.com/spiffe/spiffe/blob/main/community/sig-spire/README.md#spire-contributor-sync

**Comment by netiperher** [comment]
Hi @evan2645 sure I understand this is a large and complex issue that would need some more voices from the community to build support around the idea. I'm fine with closing this issue and then see if I can formulate my use cases more concretely in a separate ticket.

**Comment by evan2645** [comment]
Ok great, thank you @netiperher! I might recommend something like "Run SPIRE Agent on top of k8s as a workload sidecar" ... and it would be awesome if you can include some information about the motivations and use cases that cause you to lean in this direction 🙏 

I'm excited to explore this further as we've heard it several times but don't understand the implications very well yet. Thanks again for all of your input and feedback here, it is much appreciated! 🚀
