### ISSUE TITLE
Custom ServerCA

### ISSUE THREAD

**Issue by itomsawyer** [spiffe/spire#4482]
All of UpstreamCA plugin  for spire server provider a interface for signing a intermediate CA that can sign end-entity SVIDs.
I wonder if it is possible to implements a custom pkg/server/ca.ServerCA plugin for sign end-entity SVIDs.
Or why it is a must for spire server to be a intermediate CA instead of using upstreamCA to sign end-entity SVIDs

* **Version**: any
* **Platform**: any
* **Subsystem**:  server

**Comment by MarcosDY** [comment]
SPIRE Server signs SVIDs using intermediate certificates to be able to rotate bundles with a specified TTL (ca_ttl), and automatically handle the rotation of SVIDs to include the new local authorities. Due to this, users don't have to worry about rotating intermediates, and those intermediates are signed by the configured UpstreamCA.

What use case do you want to accomplish with the proposed new interface?

**Comment by evan2645** [comment]
Hi @itomsawyer , thanks for opening this

> What use case do you want to accomplish with the proposed new interface?

Are you able to provide some more information on your use case(s)? What about JWT-SVID signing?

**Comment by azdagron** [comment]
We'll go ahead and close this out for now. If you need more information or have a feature request, please feel free to open a new one.

**Comment by itomsawyer** [comment]
Hi @evan2645  @MarcosDY,  Thanks for reply.

I found I misunderstand the propose of the design of ServerCA interface. 

I though SPIRE server can only generate master key by itself. But the fact is SPIRE server key manager plugin can leverage the master key generation and signing operation to KMS like AWS. 

My original requirement is to extend SPIRE server to use another service to  signing CSR with signature algorithm instead of SHA256. So a new server key management plugin should be fine to me.
