### ISSUE TITLE
ListEntries times out for ~700k+ registrations.

### ISSUE THREAD

**Issue by stevend-uber** [spiffe/spire#4488]
There is currently an upper limit to how many entries can be in the spire-db before ListEntries times out. We recently ran performance tests on a few scenarios, list-entries and cache-sync times out at 120s.

Some scenarios:

1. List Entries, 10 RPS and 700k Registrations

There is an [existing PR up](https://github.com/spiffe/spire/pull/4411) to solve this for the runtime of the cache-reload but we should look at solutions for the startup of a new spire-server. Multiple spire-servers starting up at the same time will incur too much latency and fail startup when trying to sync to the DB. This would also occur as #registrations increases and spire-server startup-cache sync times out.

Specs:
DB: MySQL 8.x
Server: 40gb Memory, 2 CPUs

**Comment by azdagron** [comment]
Can you give more context on where the timeout was experienced? Was it just server startup (i.e. rehydrating the cache)?

I thought we were doing pagination there, but it [looks like we aren't](https://github.com/spiffe/spire/blob/fd79f5074757e56a068d2946a8a141deb0f1fed1/pkg/server/cache/entrycache/fullcache_ds.go#L42). We should be paginating cache hydration at a minumum.

**Comment by stevend-uber** [comment]
Unfortunately, I'm unable to find the exact data to tell us where the timeout was being experienced. But I agree that we should look at pagination for cache hydration on startup in addition to runtime for change-events.

**Comment by stevend-uber** [comment]
I'll be putting up a diff to add pagination soon :)

**Comment by stevend-uber** [comment]
Hah. Very interesting. I was tackling this and found this PR a few years ago. 

https://github.com/spiffe/spire/commit/83c01b83896db303ffe575ac8acd114aad97c540. 

Looks like we removed it for performance reasons. I think reliability here is more pertinent than performance in this case with the event-based cache hydration coming in, yes? 

cc: @rturner3 since you made the removal would like to query your thoughts as well.

**Comment by rturner3** [comment]
@stevend-uber If memory serves correct, it is much faster to query all the registrations at once when the total number of registrations in the database is something like < 100,000 registrations (number from my head that probably needs validation). That was the original motivation behind https://github.com/spiffe/spire/commit/83c01b83896db303ffe575ac8acd114aad97c540. There were some pretty different assumptions made about the overall scale of registrations managed by SPIRE deployments in the wild at the time that that commit was authored (>3 years ago). I think it's fair to reevaluate those assumptions now given the project has matured significantly since then and users may be pushing the bounds of SPIRE's scalability.

Once the database `registered_entries` table gets very large, it can be expensive to query all the entries at once, since it can involve locking multiple tables in the database. It makes sense to me to explore pagination in the server entry cache sync as a way to optimize the server entry cache sync for higher scale deployments.

It would be good to do some benchmarking of how long the entry cache routine takes with different page sizes. That data will help to derive a sane default page value. The previous page size value of 500 is definitely not going to be large enough for moderate-high scale cases. For the example mentioned in this issue, 700k entries with previous page size of 500 would result in 1400 sequential DB queries.
