### ISSUE TITLE
Refactor & enhance SQLite datastore implementation to support all gorm dialects

### ISSUE THREAD

**Issue by martincapello** [spiffe/spire#453]
At the time of writing, spire-server has only one datastore implementation that uses sqlite as the underlying database. But actually this implementation is using https://github.com/jinzhu/gorm, which supports additional DB dialects. So this issue is to propose a refactor & enhancement to spire-server's datastore plugin to support all the dialects supported by gorm.

**Comment by martincapello** [comment]
Maybe I would rename it to gorm instead of sqldatabases. IMO sqldatabases is like too generic. Let's see if @evan2645 has any thoughts on this. The other changes proposed seems to be fine to me.

**Comment by evan2645** [comment]
Huge thanks for looking into this @eicnix!

> rename the plugin from sqlite to sql_database

perhaps just `sql` since the plugin type is already datastore... config would then be like `DataStore "sql" ...`. I don't know if exposing `gorm` is a good idea because we may have to play some tricks with the ORM layer in the future if it doesn't meet our needs as we grow/change... my two cents anyways.

> enable configuration for database_type and connection_string

👍 default to sqlite would be good too, folks will want to be able to play around without too much effort setting up database

Everything here sounds great! thanks again :)
