### ISSUE TITLE
Spire agent should error if -insecureBootstrap and -trustBundleUrl are given

### ISSUE THREAD

**Issue by mnp** [spiffe/spire#4530]
* **Version**: 
 1.7.2
* **Platform**: 
 Linux da497fc50492 5.10.124-linuxkit #1 SMP Thu Jun 30 08:19:10 UTC 2022 x86_64 GNU/Linux
* **Subsystem**: 
agent

[Docs say](https://spiffe.io/docs/latest/deploying/spire_agent/#initial-trust-bundle-configuration) only one of the three options can be set at once, but the agent will not error out with that message if you try.

Eg `spire-agent run -config /hacked.conf -joinToken ... -insecureBootstrap -trustBundleUrl https://abc.xy:8081` will carry on trying to call the URL instead of bailing early.

This noob user was confused for a while before more RTFM and realized it's an invalid usage.

**Comment by mnp** [comment]
Yeah, if I get a minute.  Anyone else, feel free though.

**Comment by SilvaMatteus** [comment]
Hi guys,

I was looking at the issues to contribute again after some time not being able to do so.

There is a test in https://github.com/spiffe/spire/blob/main/cmd/spire-agent/cli/run/run_test.go#L744. However this test does not catch the right error. I forced the test case to fail by setting `expectError: false`:

```
--- FAIL: TestNewAgentConfig (0.00s)
    --- FAIL: TestNewAgentConfig/insecure_bootstrap_and_trust_bundle_url_cannot_both_be_set (0.00s)
        run_test.go:935:
            	Error Trace:	/home/matteus/spire/cmd/spire-agent/cli/run/run_test.go:935
            	Error:      	Received unexpected error:
            	            	only one of trust_bundle_url or trust_bundle_path can be specified, not both
            	Test:       	TestNewAgentConfig/insecure_bootstrap_and_trust_bundle_url_cannot_both_be_set
FAIL
```

It is actually failing because of "only one of trust_bundle_url or trust_bundle_path can be specified, not both". 

I would use a function `expectErrorContains` to catch the right error, if you guys do not mind me tackling this issue.

**Comment by SilvaMatteus** [comment]
@evan2645, should we close this now that #4532 is merged?
