### ISSUE TITLE
Trust Domain as a const.

### ISSUE THREAD

**Issue by raissonsouto** [spiffe/spire#4620]
Hello, I'm currently developing a plugin for SPIRE, and I'm interested in optimizing its performance.

In SPIRE, not only the Trust Domains but also various other entities are stored throughout the codebase along multiple objects and employed in multiple sections of the application. Furthermore, these entities maintain a constant value during the entire execution (for instance, you don't go from `myecommerce.com` to `ilovebrazil.net` on a daily basis).

Given these characteristics, have you considered the potential benefits of treating them as global constants?

**Comment by azdagron** [comment]
Hey, @raissonsouto, thanks for opening this issue. I'm not quite sure I follow what you are suggesting when you suggest a "global constant" for the trust domain name. Can you give a more concrete example of what you mean?

**Comment by raissonsouto** [comment]
Certainly,

After dedicating about 15 minutes to navigate in the SPIRE files, I listed each of the structs that have a `spiffeid.TrustDomain` as an atribute that showed up in my face (except the ones which refers to the federated bundles td's). The result:

https://github.com/spiffe/spire/blob/main/pkg/server/api/agent/v1/service.go#L43
https://github.com/spiffe/spire/blob/main/pkg/server/api/agent/v1/service.go#L54
https://github.com/spiffe/spire/blob/main/pkg/server/api/bundle/v1/service.go#L38
https://github.com/spiffe/spire/blob/main/pkg/server/api/bundle/v1/service.go#L47
https://github.com/spiffe/spire/blob/main/pkg/server/api/debug/v1/service.go#L38
https://github.com/spiffe/spire/blob/main/pkg/server/api/entry/v1/service.go#L24
https://github.com/spiffe/spire/blob/main/pkg/server/api/entry/v1/service.go#L33
https://github.com/spiffe/spire/blob/main/pkg/server/api/health/v1/service.go#L23
https://github.com/spiffe/spire/blob/main/pkg/server/api/health/v1/service.go#L40
https://github.com/spiffe/spire/blob/main/pkg/server/api/localauthority/v1/service.go#L39
https://github.com/spiffe/spire/blob/main/pkg/server/api/localauthority/v1/service.go#L47
https://github.com/spiffe/spire/blob/main/pkg/server/api/localauthority/v1/service.go#L57
https://github.com/spiffe/spire/blob/main/pkg/server/catalog/catalog.go#L60
https://github.com/spiffe/spire/blob/main/pkg/server/credtemplate/builder.go#L103
https://github.com/spiffe/spire/blob/main/pkg/server/bundle/pubmanager/pubmanager.go#L36
https://github.com/spiffe/spire/blob/main/pkg/server/bundle/pubmanager/pubmanager.go#L47

 From my perspective, I don't see any advantage in creating redundant instances of this object in the codebase. This is particularly true because the trust domain is a configuration defined in server.conf and remains constant during execution (write once, read many). Therefore, there's no need to worry about different threads altering its value.

> In this issue, I'm focusing on trust domain, but the idea can be used for more entities in SPIRE code

Listing some of the drawbacks:

- **Memory Consumption:** Every time you pass an object as a parameter in Go functions, a copy of it is created. While using pointers can mitigate this issue, it adds complexity to the code.
- **Code Maintainability Challenges:**
    - Accessing a specific value often requires navigating through a hierarchy of objects, making the code less straightforward.
    - It also necessitates passing a higher number of parameters, often requiring auxiliary objects
    - This can result in tightly coupled code

My suggestion is to implement a singleton object for this purpose, creating a global instance:

something like:

``` go
// Singleton implementation
package example

import (
    // Import required libraries...
)

var TrustDomain = trustDomain.New(...)

// rest of the code
```

``` go
// a code calling the singleton
// Code calling the singleton
package new-plugin

import (
    // Import required libraries, including example packge
)

func parseTrustDomain2PluginFormat() (PluginFormat, error) {
    tdName := example.TrustDomain.getName()
    // the rest of function code
}

```

**Comment by azdagron** [comment]
Thanks for the explanation and suggestion, @raissonsouto.

> Memory Consumption

I don't think this concern is valid in this particular instance. The spiffeid.TrustDomain type is backed by a `string`. Go `string`'s are immutable types. When passed or "copied" by value, the only values being duplicated are the pointer to the backing array and length. Even if this wasn't the case, we're talking about a few dozens vars at most. This represents a negligible amount of memory at the scale of use that SPIRE operates at. There are much more impactful places to focus attention if we want to improve memory usage.

> Code Maintainability Challenges

I fully agree that threading through the trust domain value into the various subsystems (and subsystems of subsystems) is tedius. However, the SPIRE project generally considers singletons an anti-pattern and rarely uses them, preferring instead that each unit be self-contained and individually configurable.

Further, in the case of plugin development, a singleton would not be of any utility since external plugins are loaded as separate processes. Plugins (both external and built-in) learn about the trust domain during the [Configure](https://github.com/spiffe/spire-plugin-sdk/blob/a2e5ba68e76045c0ca332264af935ea8c3a59f99/proto/spire/service/common/config/v1/config.proto#L14) call ( see [CoreConfiguration](https://github.com/spiffe/spire-plugin-sdk/blob/a2e5ba68e76045c0ca332264af935ea8c3a59f99/proto/spire/service/common/config/v1/config.proto#L28)).
