### ISSUE TITLE
Spire SDS extension protocol supports obtaining delegated identity

### ISSUE THREAD

**Issue by LCAIZJ** [spiffe/spire#4710]
Spire has implemented both SDS and Delegated Identity API, satisfying various requirements. I would like to make a proposal on expanding the current SDS to utilize key-value in metadata to allow users to obtain delegated identity via SDS. The detailed process is shown in the following figure and the authorization part of this extension will follow up with the original implementation ([#3620](https://github.com/spiffe/spire/issues/3620)).
<img src="https://github.com/spiffe/spire/assets/22522105/2f201c29-f6f3-4caf-ab1f-a00e2fe2afe9"  height="900" width="500"/>

The specific content of the SDS extension protocol is shown as follows.
| Extension Key | Value Example | Illustrate |
|:----------:|:----------:|:----------|
| spiffe-selectors | ["app: foo", "env: prod" ] | Delegated SVID selectors are used to filter the SVIDs that the client wants to obtain. An SVID is selected, only if all selectors of this SVID are included in the spiffe-selector. |
| spiffe-dns-names | [1.com,2.com] | Used to further filter out SVIDs with specific dnsNames based on the spiffe-selectors filtering logic. An SVID is selected, only if this SVID matches any one of the domains in spiffe-dns-names. |
| spiffe-max-entries | 1 | The maximum number of selected SVIDs. |

For example, the following configuration could be added to Envoy:
`initial_metadata:`
`- key: spiffe-selectors`
`  value: ["app: foo", "env: prod" ]`
Envoy then writes the spiffe-selectors into gRPC's metadata, thus Spire SDS may read the vaule of key 'spiffe-selectors' in the metadata as the delegated SVID selectors and filter out the SVIDs based on them, and finally returns the corresponding Delegated Identity.

The SDS extension protocol will bring the following Pros:
1. Some projects have already implemented SDS but no delegated identity API. This proposal provides a way of obtaining delegated identity by only making changes in the SDS configuration file instead of integration with the delegated identity API. For example: https://github.com/envoyproxy/envoy/issues/19756 .
2. In addition to the Delegated Identity API, SDS extension support is provided to obtain the option of Delegated Identity, providing developers with many choices to meet the needs of real-world projects.
3. It can provide good support for scene like ambient mesh (https://istio.io/v1.15/blog/2022/introducing-ambient-mesh/). 

If the community is interested in this proposal, then I'd like have a try to implement it.

* **Version**: 
* **Platform**: 
* **Subsystem**:

**Comment by rturner3** [comment]
Hi @LCAIZJ just as a heads up, this is on our plate to review, but with end of year, we'll likely get back to this in January 2024.

**Comment by itomsawyer** [comment]
Maybe also related to https://github.com/istio/istio/issues/42339

**Comment by rturner3** [comment]
Hey @LCAIZJ, thanks for your patience. I have a few questions on the use case and expected consumption pattern:

1.  xDS is an Envoy-centric protocol, and I have not personally seen it widely adopted in other open source projects. Are there any other projects you had in mind where having an xDS implementation of Delegated Identity would prove useful?
1. Were you thinking to use this API only to provide certificates to be used for TLS?
1. As xDS is primarily oriented around Envoy as the API consumer, I think we need to identify how this could be securely used in practice with Envoy. Part of the core design of SPIRE Delegated Identity is to require the caller to pass a superset of the selector set for a given workload registration entry so as to prevent trivial exfiltration of all identities authorized to an agent. In order for Envoy to use this API in a way that doesn't require users to register workloads with identical selector sets, Envoy needs some way to determine for a given connection what the caller's selectors should be. This selector data would ideally be discovered dynamically so that we're not replicating registration data in static Envoy config, which may drift from SPIRE over time. I have some firsthand experience building a solution like this and am not really aware of a straightforward way to do it with the available features in open source Envoy. Do you have any ideas of how Envoy might uniquely identify callers to a Listener endpoint and translate that into Envoy Cluster TLS config that uses certificates from the SPIRE Delegated Identity API?

**Comment by rturner3** [comment]
>Maybe also related to https://github.com/istio/istio/issues/42339

It looks like a different path was taken in that issue to use the SPIRE Delegated Identity API directly. In that case, the API caller is Istio ztunnel, which I believe doesn't need to use xDS?

**Comment by itomsawyer** [comment]
> > Maybe also related to [istio/istio#42339](https://github.com/istio/istio/issues/42339)
> 
> It looks like a different path was taken in that issue to use the SPIRE Delegated Identity API directly. In that case, the API caller is Istio ztunnel, which I believe doesn't need to use xDS?

Yes，it‘s a two-sides choice. ztunnel integrate Spire with Delegated Identity API, or, Spire integrate istio/envoy/ztunnel( ztunnel is also a xDS client) with xDS API extension.

**Comment by rturner3** [comment]
Closing this out for now due to inactivity.

**Comment by evgeniy-khatko** [comment]
Hi there, are there any updates around this feature. We have use-case for it.
Maybe there's an existing implementation I missed?
