### ISSUE TITLE
Subject x500UniqueIdentifier control

### ISSUE THREAD

**Issue by kfox1111** [spiffe/spire#4755]
Trying to hook up spire-server with mysql. Subjects for the client are being generated like:
```
Subject: C = US, O = SPIRE, CN = mysqlclient.default.svc.cluster.local, x500UniqueIdentifier = a753b06724b81d4a2f14f615d40550ed
```
But mysql can not pattern match the Subject for authentication so has to be tweaked for every instance rather then being able to set more generically.

Could there please be an option added to the spiffe entry to let the end user modify the subject behavior for that entry to drop the x509UniqueIdentifier?

**Comment by evan2645** [comment]
Hi @kfox1111 - thank you very much for bringing this to our attention. The unique identifier was added in response to #3110. At the time, conformance appeared to be the right thing to do. This issue, along with other feedbacks, have shown the change to present significant UX challenges, and after several discussions we've decided to roll it back.

For users that require this to be set, to satisfy policy or otherwise, we will be shipping a new built-in credential composer plugin (currently named "uniqueid") and there is an open PR to both roll back the change and introduce the new plugin here: https://github.com/spiffe/spire/pull/4862
