### ISSUE TITLE
Do we have workload API support for Windows. ?

### ISSUE THREAD

**Issue by prasanthAllu** [spiffe/spire#4762]
I have successfully executed the SPIRE server and SPIRE agent on Windows. However, I'm encountering an issue when attempting to run a workload, and I'm not receiving any response. I used the example from the go-spiffe repository (https://github.com/spiffe/go-spiffe) under the 'examples' directory.

I have configured the SPIRE server and agent with the settings provided in the [conf.zip](https://github.com/spiffe/spire/files/13784112/conf.zip) file. Specifically, I set the socketPath to "npipe:\\\\.\\pipe\\spire-agent\\public\\api".

Here are the steps I followed to run the SPIRE server, agent, and workloads:

1. Build the SPIRE server executable:
           go build -o C:\spire\bin\spire-server.exe
2. Build the SPIRE agent executable:
          go build -o C:\spire\bin\spire-agent.exe
3. Start the SPIRE server with the provided configuration:
         spire-server run -config conf/server/server.conf
4. Generate a join token and apply it to the SPIRE agent:
        spire-server token generate -spiffeID spiffe://example.org/host

       spire-agent run -config conf/agent/agent.conf -joinToken <token>

5. Create two new users: server-workload and client-workload.

6. Define SPIRE server entries for the users:
       spire-server entry create -spiffeID spiffe://example.org/server -parentID spiffe://example.org/host -selector 
        windows_account:username:server-workload
        
       spire-server entry create -spiffeID spiffe://example.org/server -parentID spiffe://example.org/host -selector 
       windows_account:username:client-workload

7. Run the server workload:
      runas /user:server-workload ".\server.exe" or go run main.go -username=server-workload

8. Run the client workload:
     runas /user:client-workload ".\client.exe" or go run main.go -username=client-workload

Have I missed any essential commands in the process?

And If workload is working on windows, can you provide the demo video for it or steps with description.

**Comment by edwbuck** [comment]
There is a major error in step 6.

You are configuring a workload identity system as if it were a user identity system.  That is outside of the functionality of this product.  This product provides secure, cryptographic identities for each workload (and has little to do with user identity).

This means that your selector is a selector against the process, and needs to be created with the following format

> <plugin_that_detected_the_worload>:<label_of_the_selector>:<value_for_the_label>

As, for windows we only have a 'windows' workload plugin, there's no way that your selector could ever match a workload.  You would need to reconfigure your selector with the following pattern

> windows:user_name:client-workload

instead of

> windows_account:username:client-workload

You probably want to also include more than one selector, as this would provide one "workload id" for every process running under this user, which might not be your goal.  With the addtional configuration option "discover_workload_path = true"  A combination of

> windows:user_name:client-workload
> windows:path:C:\Program Files\appname\application.exe

or possibly

> windows:user_name:client-workload
> windows:path:C:\Program Files\appname\application.exe
> windows:sha256:<sha256hash of the exe>

would provide a better resolution to the process.

The windows agent documentation is a bit out-of-place, as it is experimental.  [here's a link for your convenience](https://github.com/spiffe/spire/blob/main/doc/plugin_agent_workloadattestor_windows.md)

**Comment by edwbuck** [comment]
Please consider asking this issue to be closed, unless you find a bug with the new direction.  For additional details, consider using our support slack channel. [spire help](https://app.slack.com/huddle/T2EU67LTV/CBNCC2V17)

**Comment by evan2645** [comment]
Hi @prasanthAllu - I think what Edwin was trying to say is that the selector you used in step 6 has a typo. It should instead be `windows:user_name:client-workload` and `windows:user_name:server-workload`. Does changing it fix your problem? For what it's worth, your use case/usage seems valid to me

**Comment by prasanthAllu** [comment]
Hi @edwbuck, @evan2645, I have tried with  windows:user_name:client-workload and windows:user_name:server-workload bu still not getting any response, and also tried with the path windows:path:path/server.exe. wit this one also no response

**Comment by amartinezfayo** [comment]
@prasanthAllu Please note that the "windows" workload attestor discovers the complete path of the user name, including the computer or domain. So it's discovered as `windows:user_name:computer-or-domain\myuser`.
Could you check that you are including the computer name or domain in the selector?

**Comment by amartinezfayo** [comment]
You can turn on DEBUG log level in the agent and see 1) if the workload is reaching the Workload API and 2) if selectors are discovered. You should see a log line like `PID attested to have selectors`. That way you can see what are the selectors that are actually discovered.

**Comment by amartinezfayo** [comment]
@prasanthAllu did the suggestion to include the computer/domain in the selector solve the problem?

**Comment by amartinezfayo** [comment]
I'll go ahead and close this issue. @prasanthAllu Please reopen if needed.
