### ISSUE TITLE
Prep work to make reconfiguration possible

### ISSUE THREAD

**Issue by edwbuck** [spiffe/spire#5105]
Add support for listening to new configurations.

Initially, the SPIRE system indicated that some support for reconfiguration should be permissible; however, most code is initialized in such a manner that it cannot even detect reconfiguration of the system, should the system somehow load a new configuration file.

I propose that the Config struct in cmd/spire-server/cli/run/run.go have two receiver methods added to it:

addListener(...)
removeListener(...)

where a listener, adhering to the interface

type ConfigListener interface {
  CheckConfig(config *Config) error
  ConfigChanged(config *Config) error
}

The first method, CheckConfig, would present a potential new configuration, with no expectation that the configuration should be live.  This will permit some systems from replying back that the proposed new configuration is not suitable, by returning an error.

The second method, ConfigChanged, would indicate that a new configuration is live, and the listening modules should take whatever appropriate actions to apply the new configuration, returning an error if the configuration change is not possible.

From our current practice of passing configuration data around, this effects an inversion of the dependency.  The top-level initial Config struct would have to be passed into spire's server object, and all configurable objects below it.  This means that we would have to take a new pattern in initializing the objects, one that looks like

- Ensure a NewXXX func that takes the Config and builds the internal object config from the data, but within the package of the object.
- Add the module as a listener of the main config.
- Clean up the code to remove any older "create the object config outside of the package"

**Comment by amartinezfayo** [comment]
SPIRE maintainers have discussed the pros and cons of different approaches to allow plugin reconfiguration. We found that developing a solution to reconfigure all plugins by propagating new configurations to each plugin raises many questions regarding potential failure modes and sharp edges that can occur.

To minimize potential problems and frictions, we decided to start with reconfiguration support on a per-plugin basis. For the specific case of adding or removing Kubernetes clusters (#3549, #4390), one option could be to support configuring a directory where kubeconfig files are placed. The plugin would then scan this directory for changes without requiring a restart.

We could provide a pattern and helper functions to scan and pick up changes in a specified location, which other plugins could also use. This approach leverages the fact that each plugin is best positioned to validate and decide how to apply configuration changes, rather than involving the SPIRE core in plugin configuration changes. Additionally, it avoids the complications associated with mixed states of server or agent config files that contain both valid and invalid plugin configurations.

**Comment by sorindumitru** [comment]
It's possible that this was already discussed, but it's not just the new kubecfg files that need to be picked up, but all the configuration for a cluster (defines in https://github.com/spiffe/spire/blob/main/doc/plugin_server_nodeattestor_k8s_psat.md). Instead of kubecfg files the directory could contain files with the configuration for a cluster. The name of the file would map to the name of the cluster.

I'm wondering if, in the interesting of making this generic enough to be easily used by other plugins, we could handle this at the plugin configuration layer. Instead of having `plugin_data`, we could have:
* `plugin_data_file` containing the location of the configuration file for the plugin
* `watch_plugin_data_file` (or refresh interval) to reload the data file when changed/periodically and call `Configure` again.

I imagine that might not be a lot of extra work/complexity and allows using the interface with any plugin.

**Comment by amartinezfayo** [comment]
Thank you @sorindumitru for the feedback.
Having a `plugin_data_file` setting is one of the approaches that we discussed, and if the need is to be able to change other configuration settings, then this is the right approach for the use case. We can go with this approach.

**Comment by azdagron** [comment]
I prototyped this a while back. I can probably dust off this branch and put up a PR. In terms of reloading, have we decided whether we should do signal based or on some internal? I think we probably want to avoid inotify and the like.

**Comment by azdagron** [comment]
Closed in favor of #5165. We can sort out the last few details there.
