### ISSUE TITLE
Error starting spire-server from a different working directory than /opt/spire

### ISSUE THREAD

**Issue by ajessup** [spiffe/spire#518]
When following the tutorial to start the  starting server `spire-server run \  -config /opt/spire/conf/server/server.conf`

When run from any directory other than `/opt/spire/` we see `Error encountered while configuring plugin sql: unable to open database file`

This is because the spire server looks for a relative `.data` directory to be exist where it will create the sqlite DB file, `./.data/datastore.sqlite3`.

The workaround to this is to ensure `/opt/spire/.data` exists, and run the `spire-server` command from the `/opt/spire` directory, but we should safely assume that there is only one `spire-server` installation per host, and thus the `spire-server` command should run consistently from any working directory.

**Comment by grittershub** [comment]
Looks accurate to me. .data now gets created via of the tarball which then gets located in the right place with the install instructions, so it seems like the only missing part of the fix is to use absolute path.
I guess the bigger question is whether tarball is the longer term plan for install and whether you can parameterise the install process to work in any target location.
