### ISSUE TITLE
Issue with JWT Key Type Change not Being Reflected on SPIRE Server Restarts

### ISSUE THREAD

**Issue by spring-zhao** [spiffe/spire#5256]
If the SPIRE server key is persisted in storage and the SPIRE server is successfully started within a cluster, modifying the **jwt_key_type** parameter in the SPIRE server configuration will not update the JWT key type as expected when the SPIRE server restarts.

The reason is that when loading the key, only two checks are currently performed, and **there is no check to determine if the key type has changed**:

**findCAJournal**: This checks whether the SHA-1 hash of the public key in the key manager exists in the ca_journal table in the database.
![image](https://github.com/spiffe/spire/assets/45536703/81a46bec-cc1d-40fe-8604-999acaead609)

**filterInvalidEntries**: This verifies whether the entries signed by the keys in the key manager can be validated against the bundle in the database.
![image](https://github.com/spiffe/spire/assets/45536703/0431f120-2e38-46e9-ba59-ac6e9d09fdd1)

**Comment by azdagron** [comment]
This is by design. The new key type will be used at the next rotation. However, @MarcosDY has been slowly working on controls that allow operators greater influence over the rotation cadence (e.g. "forced rotation") that would help you rotate into the new key type more quickly.

**Comment by evan2645** [comment]
Hi @spring-zhao - if SPIRE Server generates and steps into the new key type immediately, the deployment would likely incur some rolling outages as the new key will be used for signing immediately, before there's been enough time to distribute the updated bundle that includes the new pubkey. So as @azdagron , it is by design that we step into the key carefully.

The work he mentioned around forced rotation will enable an operator to take manual action to speed the adoption of the new key. It offloads safety to the operator, who must ensure that all machines have the updated bundle before activating the new key.

If you have some other ideas on how to do this safely, please do open a  new issue so we can discuss that mechanism and figure out how to incorporate it. Thanks for your time here 🙏 I hope we can find some other ways to improve this safely!
