### ISSUE TITLE
Upstream CA plugin in support of spire server hierarchy. 

### ISSUE THREAD

**Issue by trilokgm** [spiffe/spire#636]
To use spire server as an upstream CA, a new upstream plugin needs to be implemented in order to retrieve intermediate certificates, chain and rootCA bundle from the upstream server. 
This requires a new node api to be implemented for attestation of downstream spire servers. 
Rotation of intermediate certificates, chain and new bundle should be handled based on TTL configured. 

See details shared by Evan in this [document](https://docs.google.com/document/d/1Mbsbo2xuWajU1h_XxNx2ChmNv4RIfZlb7VIaS2qM5K4/edit?usp=sharing). 

For previous discussions by @APTy @evan2645 @deepak-vij , please refer to #533 .
Detail design document to be published soon.

**Comment by evan2645** [comment]
The scope of this issue is to create a new plugin `UpstreamCA "spire"` which 1) receives CSR as input from SPIRE core, 2) uses locally available workload API (exposed by co-located agent) to get a client certificate, and 3) use the client certificate to connect to upstream SPIRE server node API and submit the CSR for signing

**Comment by evan2645** [comment]
this has been done for some time now, closing it out
