### ISSUE TITLE
Generate workload certificates based on intermediate CA. 

### ISSUE THREAD

**Issue by trilokgm** [spiffe/spire#638]
When workload calls the workload API, the certificate bundle should have 
a. SVID + Intermediate (the chain) 
b. Root CAs belonging to the Upstream SPIRE server (the bundle) 

Detail design document to be published soon.

**Comment by evan2645** [comment]
Is this a duplicate of #637 or is it different?

**Comment by deepak-vij** [comment]
I think so too, as Evan mentioned that Workload API has been refactored now for delivering the correct intermediate trust chain. Earlier, all the certificates (upstream root + all intermediates) were lumped into a single bundle instead of serving up intermediate certificates appropriately as part of a chain.

@trlokgm, please verify and close this issue if it is duplicate. Thanks.
