### ISSUE TITLE
Enhancement request for the x509pop attestor

### ISSUE THREAD

**Issue by mmerrill3** [spiffe/spire#665]
* **Version**: feature request
* **Platform**: feature request
* **Subsystem**: x509pop plugin

It would be helpful to incorporate fields from the subject section of the certificate that is being attested with the x509pop into the SPIFFE ID of the generated SPIFFE certificate.  For instance, if a certificate has an OrganizationalUnit of billing, and the trusted domain is acme.org, the SPIFFE ID would be spiffe://acme.org/billing/spire/agent/x509pop/<fingerprint>.  Ideally, any field of the subject could be used as a "sub" trusted domain, this is just an example.

This would help to distinguish certificates outside of the spire realm.  For instance, say I wanted to write a service to handle checking spiffe certificates, and to give out secrets based on that spiffe certificates.  Now, I can validate the certificate, and know which organization or application is making the request.  This will allow me to filter out secrets based on the identity of the caller.

**Comment by evan2645** [comment]
@mmerrill3 thank you for the feedback!

Generally speaking, the trust domain portion (`acme.org`) in your example is tied to a signing authority rather than a host, OU equivalent, or otherwise. That is to say, a single SPIRE server deployment manages and signs SVIDs for a single trust domain.

Further, the SPIFFE IDs generated through node attestation are typically reserved for internal SPIRE communication (e.g. from the agent to the server). The agent's identity and key aren't exposed to workloads. Are you suggesting that you'd like your application to talk directly to SPIRE server, bypassing the agent?

I will note that the x509pop node attestor currently provides supplementary selectors for agents/nodes that have been attested with it. Namely, it provides a selector `x509pop:subject:cn:YOUR_CN_HERE` that can be used to reference agents that have attested with a particular common name. You can use this selector to build up more complicated relationships by chaining registration entries together. Of course, we can make additional subject-based selectors available if you need them.

Overall, I think there are a few misconceptions here - can you share a little more about your use case? It sounds like you have existing PKI... what are you trying to further accomplish by using SPIRE? Do you know the subject values/possibilities in advance? SPIFFE IDs must be [registered in SPIRE server](https://github.com/spiffe/spire#workload-registration).

**Comment by evan2645** [comment]
Hello @mmerrill3 - just checking in to see if this addressed your issue/question? Happy to chat further if not, please just let us know.

**Comment by azdagron** [comment]
Closing this for now. Please re-open if you feel still feel there is something to do here.
