### ISSUE TITLE
Inconsistent AWS configuration in aws_iid NodeAttestor and NodeResolver

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#683]
The configuration of AWS access controls is different in the aws_iid NodeAttestor and NodeResolver.

The Node Attestor doesn't require static credentials, but the Node Resolver does.
I would like the Resolver's behavior to match the Attestor, as we don't want to use static credentials.
The code is duplicated between the two plugins.  We're additionally working on new AWS integration features (UpstreamCA stored in AWS Secrets Manager), and it would be good if the code could be shared somewhere.

Code snippets:
https://github.com/spiffe/spire/blob/573b6d7ceeff605d8babcf05cca8abaf5c0de0eb/pkg/server/plugin/noderesolver/aws/iid.go#L84-L100

https://github.com/spiffe/spire/blob/573b6d7ceeff605d8babcf05cca8abaf5c0de0eb/pkg/server/plugin/nodeattestor/aws/iid.go#L204-L210
https://github.com/spiffe/spire/blob/573b6d7ceeff605d8babcf05cca8abaf5c0de0eb/pkg/server/plugin/nodeattestor/aws/iid.go#L112-L117

**Comment by evan2645** [comment]
Thank you for filing this @mcpherrinm.

These two plugins were developed separately, and were pulled into core after having been initially written as external plugins... this is why you are seeing divergence. In terms of "would this be a welcomed change" the answer is yes, definitely.

On a related note, the node attestor interface has received an extension that allows it to optionally return selectors that are discovered as a result of the attestation process. It is possible (likely?) that the current functionality delivered by the AWS node resolver could be completely subsumed by the AWS node attestor alone, since the latter already does DescribeInstances and is in a position to return a rich set of selectors.

**Comment by mcpherrinm** [comment]
In particular:  Where should shared AWS library code live?

**Comment by azdagron** [comment]
We've typically used `pkg/common/plugin` as a place for shared code between plugins. `pkg/common/plugin/aws/` might be a decent spot.

**Comment by azdagron** [comment]
This should be solved in a way to ensure compatibility with the old configuration.

**Comment by ZymoticB** [comment]
@amoore877 you may be able to cover this in #747

**Comment by amoore877** [comment]
> @amoore877 you may be able to cover this in #747

Agreed. Should be relatively quick

**Comment by amoore877** [comment]
The mentioned commit addresses the inconsistency problem and pulls out some common functionality, since that's in line with what I was already doing in #747; I have not taken on the additional suggestion of having attestor subsume resolver
