### ISSUE TITLE
Determine what constitutes a healthy server/agent

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#730]
For the purposes of process supervision, determine what state constitutes a healthy (or unhealthy) server and agent. We will eventually use this to expose a healthcheck endpoint. When the endpoint reflects an unhealthy state, the server/agent will be restarted by the supervision system.

Care should be taken here. For instance, if the agent's health check was simply "am I connected to the server", then a server restart or failure might cause all agents to restart, which is disruptive and unnecessary given the situation. Consider the failure modes, and choose a conservative method that doesn't lend itself to false positives.

**Comment by mcpherrinm** [comment]
I think it is worthwhile to make each plugin able to participate in health checking.  For example, an UpstreamCA plugin that can't contact its UpstreamCA should return not ready.

One key point is that in Kubernetes, there are two notions of healthchecks:  Liveness and Readyness checks.  If a liveness check fails, the server/agent can be restarted.  However, for a readyness check, it'll simply be omitted from load balancing (and may stop a rollout from continuing).  I think it's important to think about that distinction.

**Comment by evan2645** [comment]
> I think it is worthwhile to make each plugin able to participate in health checking. For example, an UpstreamCA plugin that can't contact its UpstreamCA should return not ready.

That's an interesting idea... I had similar thoughts around datastore connectivity check etc but allowing plugin to advertise health is a better solution. Once we have a basic healthcheck facility in place, we should definitely explore this.

> two notions of healthchecks: Liveness and Readyness checks

Excellent point, thank you for bringing this up.

**Comment by azdagron** [comment]
I also think it important to distinguish between the two types of checks. For server liveness/readiness, I do think database connectivity is going to be really important. I really like the idea of plugins contributing to the health status, in particular on the server.

For agent readiness checks, I can imagine the following being important:
- Workload API is being served
- Agent has attested

These checks would allow kubernetes to schedule the POD as soon as the Agent was in a reasonable position to handle Workload API requests (but says nothing about whether or not a workload will have an SVID available).

For agent liveness checks, I can imagine:
- Workload API is being served over the unix domain socket
- Agent cache, if it contains SVIDS, has valid SVIDs (an indication that they are being rotated)
- Agent SVID itself is valid (an indication it is being rotated)
- Last connection attempt to the server didn't fail because the agent SVID was rejected.

**Comment by azdagron** [comment]
@evan2645 and I discussed this offline a bit and he can correct me if I misrepresent anything. For the purposes of SPIRE agent, we think it makes sense for liveliness and readiness to mean the same thing, for now. We also think the agent check should start very simple and be embellished as needed on a case-by-case basis in the future. We'd hate to have too aggressive of a health check and accidentally interrupt workloads.

In that light, we propose the following liveness and readyness check for SPIRE agent:
- Workload API is being served and is not returning Unavailable

This is a simple assertion that the Agent has performed initial attestation (otherwise it will never serve the Workload API). We can improve the agent workload handler to return Unavailable in the appropriate circumstances, as is deemed necessary in the future.

In addition, we propose that both SPIRE server and agent get a `healthcheck` command that implements these health checks. For liveliness purposes, `healthcheck` can take a `--shallow` option that performs less stringent checks. This way, k8s config can use `healthcheck` for readiness and `healthcheck --shallow` for liveliness, and as we expand the definition of what this means for server and agent, they can reap the benefits without having to adjust config.

**Comment by azdagron** [comment]
For now, the SPIRE server health check can be as simple as verifying datastore reachability (via the registration API). Similar to the agent health check, I'd hate to do more than that until we can identify targeted scenarios to check for.

After we get the catalog refactor (#725) we can define an auxiliary interface for plugins that want to participate in the health checks.

**Comment by azdagron** [comment]
The basic health checks have been implemented. Closing this issue for now.
