### ISSUE TITLE
Enumerate options for removing UpstreamCA dependency in kubernetes

### ISSUE THREAD

**Issue by evan2645** [spiffe/spire#736]
SPIRE agents must be started with a trust bundle they can use to validate the server when they reach it for the first time. In kubernetes, we work around this requirement through the use of a dummy_upstream certificate which does not change, allowing us to provide it via a static config map.

Instead of using long-lived certificates to bootstrap agent trust in the server, we should ensure that agents are provided with the latest bundle when they start. Explore and enumerate the options for ensuring that agents are always started with an up-to-date bundle. I suspect that we will want to run some code inside SPIRE server pod, which can update the bundle periodically in k8s API server (perhaps as a config map?).

**Comment by azdagron** [comment]
We've explored this space a little. Updating a ConfigMap with the x509 roots from the bundle seems to work well. Restricting the parties who participate in updating the ConfigMap to a single party seems intractable, since even K8s CronJob's don't absolutely guarantee only one pod is executing the job at a time. Therefore care has to be taken to employ a read-modify-write approach so that Kubernetes can enforce conflict resolution. (Cron)/Jobs are also subject to scheduling latency. Any latency introduced here is time a new server will be untrusted by bootstrapping agents.

A few potential solutions:

- A simple script (or outside process) that periodically polls for the latest bundle from the registration API (via the `spire-server` CLI)

PRO: Simple. Can work right now without adding code to SPIRE.
CON: Introduces artificial latency between when a SPIRE server starts and when the ConfigMap is updated, dictated by the polling interval. This could contribute to a higher than necessary cold-start period for servers.
CON: Increased datastore traffic, subject to the polling interval. This may not really present an issue.
CON: Unnecessary churn and traffic to the API server (this can be mitigated by the script maintaining a hash of the last bundle it pushed and taking no action if the bundle didn't change).

- A new plugin type that can be triggered when SPIRE Server updates the bundle to know when to push an update.

PRO: Negligible latency between a bundle update and the resulting ConfigMap update.
CON: Harder to implement resilience. If the ConfigMap update fails for transient reasons, we have to figure out how to retry gracefully.
CON: Additional complication in the SPIRE codebase around bundle management, depending on how/where the integration with this plugin is implemented.

**Comment by azdagron** [comment]
After some prototyping and consideration, we've settled on a specific Bootstrapper plugin since the plugin needs some very specific support from SPIRE core (i.e. a specific read-modify-update flow to facilitate conflict resolution) that does not really fit well with a generic fire-and-forget event handler interface.

#789 implements the solution.
