### ISSUE TITLE
CA_TTL and SVID_TTL are not applied to workloads

### ISSUE THREAD

**Issue by dnkolegov** [spiffe/spire#862]
* **Version**: 0.7.3
* **Platform**: `Linux kali 4.14.0-kali1-amd64 #1 SMP Debian 4.14.2-1kali1 (2017-12-04) x86_64 GNU/Linux
`
* **Subsystem**: Server

## Steps to reproduce

1. Configure a server with `svid_ttl = 3m` and `ca_ttl=15h`.

```
Server {
    bind_address = "127.0.0.1"
    bind_port = "8081"
    registration_uds_path = "/tmp/spire-registration.sock"
    trust_domain = "example.org"
    data_dir = "/opt/spire/server/.data"
    plugin_dir = "/opt/spire/conf/server/plugin"
    log_level = "DEBUG"
    upstream_bundle = true
    svid_ttl = "3m"
    ca_ttl = "15h"
    ca_subject = {
        Country = ["US"],
        Organization = ["SPIRE-CA"],
        CommonName = "",
    }
}

```

2. Run the server and create an agent and an entity.

3. Run the agent. 
Inspect the retrieved agent_svid.

```
openssl x509 -inform der -in agent/.data/agent_svid.der -out agent/.data/agent_svid.pem
openssl x509 -in agent/.data/agent_svid.pem -text
```

You will see the following:

```
...
Issuer: C = US, O = SPIRE-CA
Validity
            Not Before: Apr 18 04:58:56 2019 GMT
            Not After : Apr 18 05:02:06 2019 GMT

```
The agent's SVID ttl is about 3m. Correct.

Then retrieve and inspect an SVID for the workload.
 
```
spire-agent api fetch x509 -write ./
```
```
 openssl x509 -in svid.0.pem -text

...
Issuer: C = US, O = SPIRE-CA
Validity
            Not Before: Apr 18 04:59:56 2019 GMT
            Not After : Apr 18 05:59:04 2019 GMT
```
Workload's SVID_TTL is about 1h.

```
openssl x509 -in bundle.0.pem -text

...
Issuer: C = US, O = SPIFFE
        Validity
            Not Before: Apr 18 04:58:54 2019 GMT
            Not After : Apr 18 05:59:04 2019 GMT
        Subject: C = US, O = SPIRE-CA

```
CA_TTL is about 1h.

**Comment by azdagron** [comment]
Hi @dnkolegov. The `svid_ttl` configurable controls the default SVID TTL that is 1) applied to agent SVIDs, 2) applied to SVIDs for registration entries where the TTL has been set to zero. I assume you didn't set a TTL explicitly when you created your workload registration entry? The CLI defaults to 3600 seconds (1 hour) when you create registration entries so unless you explicitly pass `-ttl=0`, an hour is what you will get. You can confirm your TTL by running `spire-server entry show`.

The `ca_ttl` configurable determines how long the server CA is signed for but only when self-signed. Otherwise the TTL of the server CA is determined by the Upstream CA that signs it.
