### ISSUE TITLE
In-progress Agent Sync cancelled when SVID rotated

### ISSUE THREAD

**Issue by azdagron** [spiffe/spire#891]
The agent sync and SVID rotator code operate somewhat independently. When the SVID is rotated by the rotator, it immediately closes the client connection (so that the connection can be re-dialed with new credentials). However, when a sync operation is in-progress, the FetchX509SVID call will be interrupted. At a minimum, this causes unnecessary logging of error conditions, at most, it could impact how quickly an agent responds to registration changes.

The agent code should be changed so that the rotator does not close the client connection while there is an in-progress sync operation. There are probably a few ways to tackle this. One solution would be to integrate the rotation code into the agent sync code.

**Comment by APTy** [comment]
What if: `client.FetchUpdates()` increments a waitgroup counter and decrements it on completion, and `client.Release()` waits for that waitgroup to be done (i.e. any in-progress requests will be completed), subject to a timeout, before returning. The client could also enter a "draining" state, so that no more requests could be started while the resources are attempting to be released.
