### ISSUE TITLE
Overly large bundle can stop SPIRE server from working

### ISSUE THREAD

**Issue by mcpherrinm** [spiffe/spire#921]
If the `bundle` ever exceeds the size a gRPC message can handle, SPIRE server stops working.

We had deployed it with some other problems, so SPIRE was being restarted a lot on a bunch of nodes, then we hit this situation:

```
2019-05-17_17:28:37.95060 time="2019-05-17T17:28:37Z" level=info msg="plugins started"
2019-05-17_17:28:38.05665 time="2019-05-17T17:28:38Z" level=error msg="fatal: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5343103 vs. 4194304)"
2019-05-17_17:28:38.05670 time="2019-05-17T17:28:38Z" level=error msg="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5343103 vs. 4194304)"
```

```
2019-05-17_17:28:37.95060 time="2019-05-17T17:28:37Z" level=info msg="plugins started"
2019-05-17_17:28:38.05665 time="2019-05-17T17:28:38Z" level=error msg="fatal: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5343103 vs. 4194304)"
2019-05-17_17:28:38.05670 time="2019-05-17T17:28:38Z" level=error msg="rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5343103 vs. 4194304)"
```

The configuration we were using looked like:

```
plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "mysql"
            connection_string = "..."
            root_ca_path = "..."
            client_key_path = "..."
            client_cert_path = "..."
        }
    }

   NodeAttestor "join_token" {}

   NodeResolver "noop" {
       plugin_data {}
   }

    KeyManager "memory" {
        plugin_data = {}
    }

    UpstreamCA "disk" {
        plugin_data {
            ttl = "1h"
            key_file_path = "dummy_upstream_ca.key"
            cert_file_path = "dummy_upstream_ca.pem"
        }
    }
}
```

**Comment by APTy** [comment]
I dug into this some more.

If you are using KeyManager "memory", the size of the trust bundle increases by ~100 bytes each time a SPIRE Server in your cluster boots (because a new ECC JWT signing pubkey is added). Now, if some bug causes your Server to crash loop, the size of the trust bundle will quickly hit the 4MB gRPC message limit.

One solution is to use the KeyManager "disk" plugin, which ensures that subsequent boots of the Server will re-use keys that were already generated and added to the trust bundle.

Still, it seems weird that a single bad server can DoS the entire cluster.

Long term, if we expect that a trust bundle could conceivably exceed 4MB, we should maybe turn this into a streaming API. Perhaps also increasing the gRPC [message size limits](https://godoc.org/google.golang.org/grpc#MaxCallRecvMsgSize) could help.

Short term, should we add application logic to prevent the trust bundle from exceeding 4MB? Or emit metrics/log warnings that the trust bundle size is reaching dangerous levels?

**Comment by amoore877** [comment]
Perhaps the keypair of a SPIRE Server using KeyManager `memory` should also be shorter-lived; I'm assuming that expired keys are eventually removed from the trust bundle?

However, this suggestion along with increasing message size limits, streaming API, and metrics monitoring (what do we do on such an alert?) are all just mitigations. Agree that it would be best to find an actual solution, not mitigation, to `single bad server can DoS the entire cluster` while still allowing the `memory` config instead of `disk`.

**Comment by evan2645** [comment]
Just pinging here to note that this issue is still outstanding, however it is not as urgent as it once was because most practical configurations won't trigger this condition anymore (this was not the case in past SPIRE versions).

Specifically, SPIRE Server is either using an Upstream or it is not. In the latter, a persisting KeyManager is probably in use, which will prevent a spinning server from continually generating and injecting new CAs. In the former, SPIRE Server keys don't need to be regenerated on boot and thus shouldn't cause the bundle to grow if it's spinning.

As for how to address the actual problem, I'm not quite sure on the best route...

>Short term, should we add application logic to prevent the trust bundle from exceeding 4MB? Or emit metrics/log warnings that the trust bundle size is reaching dangerous levels?

A warning makes good sense I think... it's hard for me to see how we could further heal though without intervention. We probably don't want to stop rotating and let things expire?

>Long term, if we expect that a trust bundle could conceivably exceed 4MB, we should maybe turn this into a streaming API. Perhaps also increasing the gRPC message size limits could help.

If we could safely increase the message size to a value large enough that we probably won't ever see this again, then that sounds pretty good... In general, it sounds like large bundles are likely to break other things too (e.g. https://github.com/spiffe/spire/issues/1004#issuecomment-510541064)

**Comment by narg95** [comment]
Hi, I run into a similar issue. My setup is not realistic but it shows how things can grow or go wrong. I am rotating CA certs every 3mins and SVID certs every minute. I am running agent and server in different kubernetes clusters with in-memory storage. 
Currently the `spire-server` crashed and can not recover because the `bundle` is bigger than `1MB`:
```
ConfigMap \"spire-bundle\" is invalid: []: Too long: must have at most 1048576 bytes"
```
 and `ConfigMaps` can not have more than 1MB due to a apparently [etcd limitation](https://github.com/kubernetes/kubernetes/issues/19781#issuecomment-172553264).

From this tread I still do not understand how to fix this issue hopefully without downtime. Streaming the bundle or placing an alert won't make the ConfigMap smaller. Am I overlooking something? How a disk storage could help? Is there a way to delete/ extract old CAs?

Although my setup is unrealistic as I mentioned, it still shows a problem that will arise over time.

Thanks for your comments!

**Comment by evan2645** [comment]
@narg95 thank you for this... I wasn't aware of the config map limitation, and it will be important to keep in mind as we find a better solution.

> From this tread I still do not understand how to fix this issue hopefully without downtime. Streaming the bundle or placing an alert won't make the ConfigMap smaller.

There is a related problem in which the bundle size exceeds the gRPC message size limit, and gRPC is (was) used between SPIRE Server core and the datastore... so this issue was initially opened after hitting a problem there and not in k8s config map.

> Is there a way to delete/ extract old CAs?

There is not currently an API to do this, however one is planned as part of the work described in https://github.com/spiffe/spire/issues/1934

> Although my setup is unrealistic as I mentioned, it still shows a problem that will arise over time.

SPIRE will automatically delete expired CA certificates from the bundle to prevent it from growing too large over time. In this issue, we can see that it can still grow large in certain edge cases.

SPIRE waits until a CA certificate has been expired for 24 hours before removing it from the bundle. This is a safety mechanism intended to protect against outages induced by clock-related problems. Perhaps the hard 24hr limit can be adjusted to account for smaller CA TTLs... 🤔

**Comment by azdagron** [comment]
While this is still possible, it's much less likely given the way SPIRE currently operates. I'm going to close this issue for now.
