### ISSUE TITLE
Reduce extra calls to datastore plugin for workload entries

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#980]
## Background

The [`regentryutil/fetch`](https://github.com/spiffe/spire/blob/8f92fef7c8d5d0c0842ab1ba7b7b4b8e024b3658/pkg/server/util/regentryutil/fetch.go) module answers the question: "Which workloads is node X authorized to fetch identities for?"

It accomplishes this by traversing the graph of registration entries, ultimately returning a list of all registration entries associated with a node's SPIFFE ID.

The base case for this recursive search is when a registered entry has no child entries and no node selectors. This determination requires two calls to the `datastore` plugin.

## Problem

Consider the case of an agent `spiffe://agent123` with 100 registered workloads. Let's enumerate the queries that occur in `regentryutil`:

1. Fetch all entries with a parent id of `spiffe://agent123`, receive a list of 100 entries.
2. Fetch node selectors associated with spiffe id `spiffe://agent123`, receive 0, return.

For each entry received in (1), repeat steps (1) and (2). Nothing will be returned from either query, indicating that we can "step out" of this depth and return.

This results in 202 calls to the `datastore` plugin, which is excessive given that we can probably figure out that these are "child" entries by some other means.

## Proposed Solution

Annotate registration entries with some type information: `node` or `workload`. When the regentryutil logic encounters a registration of type `workload`, it can terminate early. Since these type annotations will not be available on older registrations, the behavior would be to fall back to the current logic if the annotations don't exist.

This has a benefit of clearing up the distinction between the registration types, which has been the source of confusion for some users (speaking for myself). This annotation could become required in the next major release.

## Alternatives

We _could_ determine if a registration is a node entry by checking whether the parentID is "spiffe://.../spire/server", however, due to the recursive nature of the search, this actually wouldn't cover cases that are currently allowed, such as when there are aliases of aliases.

**Comment by APTy** [comment]
I'll wait until we discuss more to open a PR, but https://github.com/spiffe/spire/compare/master...APTy:registration-type-2 shows an example of what the data model for this could look like under the proposed solution.

**Comment by rturner3** [comment]
Carrying over some conversation from [#1435](https://github.com/spiffe/spire/pull/1435#issuecomment-601482228):

I think #1439 will definitely help minimize this query crawl problem to a certain degree, but I'm concerned it won't be enough for larger registration entry sets. When the number of registrations managed by an Agent is greater than 100, we're still looking at 100+ unnecessary database queries for registration entry set cache misses. For HA deployments of the Server with N instances, that could result in N * 100 unnecessary queries every few seconds (assuming a 5 second Agent sync interval and short-lived cache entries).

I think the root of these performance problems is this dynamic registration entry graph discovery/traversal performed during each Agent sync. If we could persist all the child + selector subset relationships between registration entries into a single table on create/update/delete of registrations, we might be able to simplify the FetchX509SVID registration entry lookup to only a couple of queries. Doing this would make create/update/delete operations more expensive and complex and would require a little extra storage, but it would heavily optimize the read case, which is generally expected to be the more frequently executed path. My idea here is basically to move the logic of [regentryutil/fetch](https://github.com/spiffe/spire/blob/master/pkg/server/util/regentryutil/fetch.go) into the create/update/delete registration entry code path, then persist the graph of relationships into the database.

We could model the registration entry relationships as a many-to-many relation through a secondary relation table. Here's some DDL showing an example of how the relationship data could be persisted (tested on MySQL 5.6+):
```sql
CREATE TABLE registered_entries (
  id INT NOT NULL AUTO_INCREMENT,
  spiffe_id VARCHAR(2048),
  parent_id VARCHAR(2048),
  PRIMARY KEY (id)
  /* Omitting other DDL of registered_entries here for brevity */
);

CREATE TABLE registered_entry_relation (
  registered_entry1_id INT NOT NULL,
  registered_entry2_id INT NOT NULL,
  PRIMARY KEY (registered_entry1_id, registered_entry2_id),
  FOREIGN KEY (registered_entry1_id) REFERENCES registered_entries(id),
  FOREIGN KEY (registered_entry2_id) REFERENCES registered_entries(id)
);

DROP TRIGGER IF EXISTS registered_entry_relation_order;

/*
    Create a trigger that enforces that registered_entry1_id < registered_entry2_id.
    This prevents possible duplicate relations from being persisted.
*/
DELIMITER //
CREATE TRIGGER registered_entry_relation_order
BEFORE INSERT ON registered_entry_relation 
FOR EACH ROW
BEGIN 
  DECLARE x int; 
  IF (NEW.registered_entry1_id>NEW.registered_entry2_id)
  THEN 
    SET x:=NEW.registered_entry1_id; 
    SET NEW.registered_entry1_id:=NEW.registered_entry2_id; 
    SET NEW.registered_entry2_id:=x; 
  END IF; 
END;//
DELIMITER ;

INSERT INTO registered_entries (parent_id, spiffe_id) VALUES
('spiffe://example.org/spire-server', 'spiffe://example.org/node1'),
('spiffe://example.org/node1', 'spiffe://example.org/workload1'),
('spiffe://example.org/node1', 'spiffe://example.org/workload2');

INSERT INTO registered_entry_relation (registered_entry1_id, registered_entry2_id)
VALUES (2, 1), (3, 1);
Then regentryutil/fetch could effectively be replaced with the following SQL for the registration entry lookup in FetchX509SVID:

SELECT * FROM registered_entry_relation
WHERE registered_entry1_id=<AGENT_ID>
OR    registered_entry2_id=<AGENT_ID>;
The business logic could process the results of the query and filter them to a distinct set of IDs, then basically do:

SELECT * FROM registered_entries r
WHERE r.id IN (...)
...
```
Not sure if there's a more sophisticated way with SQL to simplify this further into one query, but still, two queries is much more performant than the current approach.

Just to clarify a bit further, `registered_entry_relation` would contain all reachable registered entries from a SPIFFE ID, not just direct parent-child relationships. Take the following scenario for example:

- There is an Agent `A` with selectors `S1` mapping to a node registration `N1`.
- There is a selector set `S2`, which is a subset of `S1`.
- There is a node registration `N2` with selectors `S2`.
- There is a workload registration `W1` with parent ID `N1`.
- There is a workload registration `W2` with parent ID `N2`.
- Based on these registrations, `A` should receive the registration entry set `{N2, W1, W2}` when it calls FetchX509SVIDs.

In this scenario, the contents of `registered_entry_relation` would be:
```
{(N1, N2), (N1, W1), (N1, W2), (N2, W2)}
```

Long term, I think using a graph database may be a good option if the performance characteristics are reasonable. It makes sense to evaluate it since the registration entry data is inherently modeled as a graph.

**Comment by rturner3** [comment]
Another option to consider on top of the proposal for a entry graph lookup table could be to adopt more of an eventual consistency model for propagation of registration entry data to Agents. When create/update/delete operations occur on the `registration_entries` table, we could record these events into a journal or history table as part of the same database transaction.

The advantage of recording the events is that the whole process of generating the `registered_entry_relation` graph view could then be done on some periodic basis. That way you're not paying the cost of regenerating the full registration entry graph on every registration entry write/delete as a synchronous operation. That will keep the registration entry APIs performant, at the compromise of some propagation delay to the Agents.

**Comment by rturner3** [comment]
A detail that I missed in my proposal is that agent SPIFFE IDs are stored in the `attested_node_entries` table, not in the `registered_entries` table. So the SQL is actually a bit simpler, and the trigger is not required since there is no ambiguity between agent IDs and registration entry IDs in the mapping table:

```sql
CREATE TABLE registered_entries (
  id INT NOT NULL AUTO_INCREMENT,
  spiffe_id VARCHAR(2048),
  parent_id VARCHAR(2048),
  PRIMARY KEY (id)
  /* Omitting other DDL of registered_entries here for brevity */
);

CREATE TABLE attested_node_entries (
  id INT NOT NULL AUTO_INCREMENT,
  spiffe_id VARCHAR(2048),
  PRIMARY KEY (id)
  /* Omitting other DDL of attested_node_entries here for brevity */
);

CREATE TABLE registered_entry_relation (
  attested_node_entry_id INT NOT NULL,
  registered_entry_id    INT NOT NULL,
  PRIMARY KEY (attested_node_entry_id, registered_entry_id),
  FOREIGN KEY (attested_node_entry_id) REFERENCES attested_node_entries(id),
  FOREIGN KEY (registered_entry_id)    REFERENCES registered_entries(id)
);
```

**Comment by rturner3** [comment]
Formalizing the ideas I described in previous comments in the issue into a more succinct proposal with pros/cons and more details:

# Proposal
Maintain a new table called `registered_entry_relation` that associates attested nodes to the registration entries for which they are authorized to distribute identities.

Example MySQL DDL for the new table:
```sql
CREATE TABLE registered_entry_relation (
  attested_node_entry_id INT UNSIGNED NOT NULL,
  registered_entry_id    INT UNSIGNED NOT NULL,
  PRIMARY KEY (attested_node_entry_id, registered_entry_id),
  FOREIGN KEY (attested_node_entry_id) REFERENCES attested_node_entries(id) ON DELETE CASCADE,
  FOREIGN KEY (registered_entry_id)    REFERENCES registered_entries(id)    ON DELETE CASCADE,
  INDEX (attested_node_entry_id),
  INDEX (registered_entry_id)
);
```

Keeping this table up-to-date potentially introduces significant overhead for write operations in SPIRE Server. This new relation table can maintained in one of two ways:

### Synchronous updates on related write events
The relation table is synchronously kept up-to-date when relevant create/update/delete events to registration entries and/or attested nodes occur.

**Pros**:
- Minimizes propagation delay of authorized registrations to Agents.
- More in line with strong consistency patterns used in SPIRE today.

**Cons**:
- Will significantly increase latency of write/delete operations. It’s not yet clear whether maintenance of the new relation table will cause write API latencies to be > 5 seconds (max timeout value today).
- Adds significant complexity to write/delete operations.

### Asynchronous updates
The relation table is asynchronously updated in a separate goroutine on a periodic basis. Create/update/delete events to registration entries and/or attested nodes are tracked in a journal table, and the periodic task repopulates the contents of the relation table if there are new events in the journal since the last time the task executed.

**Pros**:
- Write APIs will remain as responsive as they are today.

**Cons**:
- May break some consumption patterns of SPIRE that depend on strong consistency semantics of registration APIs/identity propagation.
- Introduces complexity around how to handle this process in HA SPIRE Server deployments. Instances of SPIRE Server would want to coordinate which instance is managing the `registered_entry_relation` table to avoid conflicts with each other.
- May become harder to correlate datastore load metrics trends with API requests.

Due to the complexity and possibility of backward incompatibility that may result by using asynchronous updates and eventual consistency, I propose the option to maintain the relation table synchronously on write events.

## Events requiring updates to the relation table

### One-time creation of the table on SPIRE Server startup
If SPIRE Server starts up and does not find the `registered_entry_relation` table, it will create the table with a database migration and populate the contents of it by iterating through all attested nodes and discovering all registration entries authorized to those nodes.

### On creation of a registration entry

1. Discover the set of attested nodes that are authorized to distribute the identity for the new registration. Call this procedure `affectedAttNodeSpiffeIDs()`. Pseudocode is provided below.
1. For each such attested node discovered in the previous step, perform the crawl in [regentryutil/fetch](https://github.com/spiffe/spire/blob/master/pkg/server/util/regentryutil/fetch.go) and discover each registration for which the given attested node can serve identities.
1. Persist all such relationships of attested node ID -> authorized registration ID in `registered_entry_relation` table.

Pseudocode:

```go
// This procedure is intended to be a reverse crawl of the procedure
// in regentryutil/fetch
// For a given new registration R, find all attested nodes which are authorized to
// distribute R’s identity.
func affectedAttNodeSpiffeIDs(spiffeID, parentID string, selectors []Selector) []string {
    // Set of attested node SPIFFE IDs that will receive this new registration
    var attNodeSpiffeIDs map[string]struct{}

    // 1) Find all attested nodes with a selector set that is a superset
    //    of the new registration’s selector set.
    for _, anID := range findSelectorSupersetAttNodeSpiffeIDs(spiffeID, selectors) {
        attNodeSpiffeIDs[anID] = struct{}{}
    }

    // 2) For all registration entries that have a selector set that is a
    //    superset of the new registration’s selector set, traverse the
    //    graph along the parent relationships to find any attested nodes
    //    whose SPIFFE ID == a registration’s parent ID.
    for _, ssRegEntry := range findSelectorSupersetRegEntries(spiffeID, selectors) {
        curPID := ssRegEntry.parentID
        for _, anID := range affectedParentAttNodeSpiffeIDs(curPID) {
            attNodeSpiffeIDs[anID] = struct{}{}
        }
    }

    // 3) Traverse the registration graph by trying to match the new
    //    registration’s parent ID to SPIFFE IDs of existing attested nodes
    //    and registrations.
    //    Capture all such attested nodes that are reachable via these
    //    parent relationships in the graph.
    for _, anID := range affectedParentAttNodeSpiffeIDs(parentID) {
        attNodeSpiffeIDs[anID] = struct{}{}
    }

    // Extracts all keys from map into string slice
    return mapKeyStringSlice(attNodeSpiffeIDs)
}

func affectedParentAttNodeSpiffeIDs(parentID string) []string {
    parentAttNodeSpiffeIDs := make(map[string]struct{}, 0)
    affectedParentAttNodeSpiffeIDs(parentID, parentAttNodeSpiffeIDs)

    // Extracts all keys from map into string slice
    return mapKeyStringSlice(parentAttNodeSpiffeIDs)
}

func affectedParentAttNodeSpiffeIDs(parentID, parentAttNodeSpiffeIDs map[string]struct{}) {
    // This registration chains up to the SPIRE Server root registration,
    // and thus does not chain to an attested node.
    if parentID == “spiffe://trustdomain/spire/server” {
         return
    }

    // See if the parent ID of the new registration is the SPIFFE ID
    // of an attested node.
    // If so, add the attested node SPIFFE ID to the map
    // and stop traversing this path in the graph.
    parentAttNode := getAttNodeBySpiffeID(parentID)
    if parentAttNode != nil {
        parentAttNodeSpiffeIDs[parentAttNode] = struct{}{}
        return
    }

    // See if the parent ID of the new registration is the SPIFFE ID
    // of any other registrations.
    for _, regEntry := range findRegEntriesBySpiffeID(parentID) {
        // If the registration has a parent registration(s), recursively
        // traverse up the registration hierarchy(ies) until we find an
        // attested node parent or a registration with the SPIRE Server
        // root registration.
        affectedParentAttNodeSpiffeIDs(regEntry.ParentID, parentAttNodeSpiffeIDs)
    }
}
```

### On update of a registration entry
Do the same procedure as described in the registration entry creation event, but also delete any existing relations which were not discovered in the latest authorization crawl(s).

### On deletion/purge of registration entry
1. Before deleting the registration entry, look in the registration entry relation table for all attested nodes that are authorized to the registration entry. Call the set of such attested nodes `A`.
1. Delete the registration entry, which should cascade delete all rows in the registration entry relation table.
1. For each affected registration entry in `A`, rediscover the graph of reachable entries using the steps described in steps 2 and 3 of the registration entry creation event section.

### On new agent attesting
When a new agent attests, we simply want to execute the authorization crawl and persist all reachable entries in the registration entry relation table after saving the attested node in the `attested_node_entries` table.

### On agent eviction
This case is pretty simple. Evicting an agent involves deleting its entry in the `attested_node_entries` table. This will cause a cascade delete for all mapping entries in the `registered_entry_relation` table.

## Open Questions
- How do these operations scale when there are many registrations in the database and many Agents? Do they complete in a reasonable amount of time (i.e. << gRPC timeout of 5 seconds)?
- Do we need to gracefully handle cycles in the registration graph when traversing the parent-child relationships? It seems that nothing in the database schema is preventing registrations from being created with circular relationships today. i.e. registration `A` declares `B`'s SPIFFE ID as its parent ID, and registration `B` declares `A`'s SPIFFE ID as its parent ID.

**Comment by evan2645** [comment]
I think this issue has been addressed by the in-memory cache. Going to go ahead and close this out as stale, please let us know if it's still valid.
