### ISSUE TITLE
Document how TTLs work

### ISSUE THREAD

**Issue by APTy** [spiffe/spire#997]
Currently, there are a few different ways to configure certificate TTLs:

- SVID TTLs through `svid_ttl` config flag
- SVID TTLs through registration entry (with CLI default)
- CA TTL (in-memory upstream ca) through `ca_ttl` config flag
- CA TTL (disk upstream ca) through `disk.plugin_data.ttl` config flag

It's also not guaranteed that SVID TTL will be honored unless it is 6x the CA TTL.

At the very least we should document this behavior and give guidance for making changes to TTLs.

There are some cases (like the CLI default TTL of 3600s) that could probably be fixed for the next release.

**Comment by azdagron** [comment]
I've done some playing around with TTLs this last week. I tuned up the internal interval for timers in the agent and server that check for whether or not rotation should occur. I set all such timers to 5 seconds.

What I observed is that the CA TTL and SVID TTL can be independently set (obviously if the SVID TTL is higher, it will get capped) and everything functions as long as either TTL is _at least_ twice as long as the check interval (i.e. 10 seconds). Obviously such a small TTL is no good from a resilience perspective (any downtime on agent or server will prevent rotation before the SVID expires).

With that, I think we can document the CA/SVID TTL's as independent, other than the capping behavior and explain minimums in terms of the check interval.

Regarding the upstream CA configurable, I explored maybe deprecating that configurable and providing the requested CA TTL through the global plugin configuration. However, currently the global plugin configuration is shared for both agent and server plugins and it felt a little gross to have a value provided to agent plugins that would never be set but we could probably do something to make it not quite as gross (lump all agent-specific global configuration into a single sub-message that is never set by the server and vice-versa).

I agree that we should probably remove the CLI default since 3600 seconds is already the default SVID TTL.

**Comment by evan2645** [comment]
> Regarding the upstream CA configurable, I explored maybe deprecating that configurable and providing the requested CA TTL through the global plugin configuration. However, currently the global plugin configuration is shared for both agent and server plugins and it felt a little gross to have a value provided to agent plugins that would never be set but we could probably do something to make it not quite as gross (lump all agent-specific global configuration into a single sub-message that is never set by the server and vice-versa).

Thinking about this a little further, perhaps we can address it by adding a `desired_ttl` field to the proto?

**Comment by azdagron** [comment]
Oh, to the signing request proto? That feels right to me.
